### ISSUE TITLE
Apache HTTP Components could shaded

### ISSUE THREAD

**Issue by d2a-raudenaerde** [rubenlagus/TelegramBots#100]
Currently it is a pain to include other libs (for example jenkins-client) in an project that also depends on telegrambots, because HttpComponents conflict easily.

Please shade/repackage the Apache Http client (see mvn shade plugin)

**Comment by rubenlagus** [comment]
mmm... I've never faced such an issue and therefore I'm not familiar with shade plugin. If you are, feel free to open a pull request with it.

**Comment by d2a-raudenaerde** [comment]
If I can fine time, I'll try to do this.
btw: more info can be found here: http://maven.apache.org/plugins/maven-shade-plugin/examples/class-relocation.html

**Comment by d2a-raudenaerde** [comment]
See the pull-request: #103

**Comment by d2a-raudenaerde** [comment]
Oh I see I needed to make a pull-request on DEV.. Thanks for fixing this!

**Comment by rubenlagus** [comment]
I took away this changes from lates version, it was messing up the dependencies. I'll try to have a deeper look when I have more time, sorry.
