### ISSUE TITLE
Forgot String argument on setDocument on  v.5.4.0.1

### ISSUE THREAD

**Issue by DSMan97** [rubenlagus/TelegramBots#1003]
Hi, I can't use setDocument with fileID String instead of InputFile

https://core.telegram.org/bots/api#senddocument

**Comment by recursiveribbons** [comment]
In the `SendDocument` class, you can set the document using an `InputFile`. Use the constructor `public InputFile(String attachName)` to send using a `FileID`.

**Comment by Qirol4006** [comment]
In the SendDocument class, you can set the document using an InputFile. Use the constructor public InputFile(String attachName) to send using a FileID. And sendPhoto SendVideo classes. how do i solve this

**Comment by recursiveribbons** [comment]
@Qirol4006 `SendPhoto` and `SendVideo` are exactly the same. Either put an `InputFile` in the constructor, or in the respective `setPhoto` and `setVideo` classes.

**Comment by DSMan97** [comment]
Thanks so much guys 👍
