### ISSUE TITLE
5.5.0 is not on Maven Central

### ISSUE THREAD

**Issue by fulopm** [rubenlagus/TelegramBots#1008]
5.5.0 is not available on Maven central.

![kép](https://user-images.githubusercontent.com/12369436/145255210-67ec6285-6b93-4cc1-b450-7878cc202f7a.png)

**Comment by recursiveribbons** [comment]
I checked again, it is there now.

<img width="407" alt="Screenshot 2021-12-11 at 21 04 26" src="https://user-images.githubusercontent.com/18372809/145690071-7c036b8b-52a9-458c-bfab-c67096cd918f.png">

**Comment by fulopm** [comment]
Thanks!
