### ISSUE TITLE
Support for menu button

### ISSUE THREAD

**Issue by nikolakurtic** [rubenlagus/TelegramBots#1015]
Hi, is menu button supported?
https://telegram.org/blog/animated-backgrounds#bot-menu

**Comment by Chijuk** [comment]
Add some commends to your bot in BotFather or you can use `SetMyCommands`  library method to do the same

**Comment by nikolakurtic** [comment]
Thanks for a quick answer, I would like to have custom commands per chatId. How is this SetMyCommands used? From where?

**Comment by Chijuk** [comment]
You can use `SetMyCommands` as parameter of `execute()` method of `DefaltAbsSender` class. Just like you send messages.
But this commands will be global for bot and its subscribers.
If I needed to have custom commands per chatId I'd show all commands to subscribers and check for permission inside my custom permission logic.
Or for example create `/showcommands` command that would show allowed for current chatId commands as inline buttons or smth like that.

**Comment by nikolakurtic** [comment]
Ok, got it thanks.
