### ISSUE TITLE
Description Failed to receive messages in a supergroup of more than 10,000 people

### ISSUE THREAD

**Issue by 4o4-Not-Found** [rubenlagus/TelegramBots#1016]
Version 5.5 is currently in use
When I was in a group of more than 10,000 people, the bot couldn't receive messages about new users joining,But groups of less than 10,000 people can.

**Comment by 4o4-Not-Found** [comment]
I use Message#getNewChatMembers().

**Comment by Chase22** [comment]
Bots will not receive new member updates for large groups. That's not an issue with the library, it's in the API

**Comment by 4o4-Not-Found** [comment]
> Bots will not receive new member updates for large groups. That's not an issue with the library, it's in the API

I know this is probably due to the API. So are there any new parameters available in this lib?

**Comment by Chase22** [comment]
This library is a client for the API. If the API can do something, the library can. If the API can't do something, the library can't.
