### ISSUE TITLE
I cannot find the class deleting the message in org.telegram.bot.api.deleteMessage

### ISSUE THREAD

**Issue by Programistich** [rubenlagus/TelegramBots#1018]

**Comment by Chase22** [comment]
That's because the class is `org.telegram.telegrambots.meta.api.methods.updatingmessages.DeleteMessage`
See [DeleteMessage](https://github.com/rubenlagus/TelegramBots/blob/master/telegrambots-meta/src/main/java/org/telegram/telegrambots/meta/api/methods/updatingmessages/DeleteMessage.java
