### ISSUE TITLE
Imposible to use API behind proxy

### ISSUE THREAD

**Issue by maloletniy** [rubenlagus/TelegramBots#102]
Hi, there is no chance to use your library if the server is behind the proxy. Could you please add the ability to read the default system proxy settings by HttpClient and RequestConfig.

**Comment by fcioffi** [comment]
I'm interested too.

RequestConfig supports proxy but I don't understand how to set.

Thank you, very much.

**Comment by maloletniy** [comment]
@fcioffi 
I use next temporary solution for request config:

```
requestConfig = RequestConfig.copy(RequestConfig.custom().build())
                .setProxy(
                        new HttpHost(
                                System.getProperty("http.proxyHost"),
                                Integer.parseInt(System.getProperty("http.proxyPort"))))
                .setSocketTimeout(SOCKET_TIMEOUT)
                .setConnectTimeout(SOCKET_TIMEOUT)
                .setConnectionRequestTimeout(SOCKET_TIMEOUT)
                .build();
```

**Comment by fcioffi** [comment]
With this solution you must edit source code?
I wouldn't edit source code ;)

**Comment by maloletniy** [comment]
Then you have no chance to use it behind a proxy sever :)

2016-07-01 11:33 GMT+03:00 Francesco Cioffi <notifications@github.com>:

**Comment by rubenlagus** [comment]
@maloletniy  I'll try to add it somehow as an option in the api. I'll go through this when I have a bit of free time.

**Comment by rubenlagus** [comment]
With last dev version you should be able to provide the proxy host and port within an BotOption.

**Comment by fcioffi** [comment]
Thank you.

I tried it, but it doesn't run :(

**Comment by rubenlagus** [comment]
Did u used correct BotOptions?

**Comment by fcioffi** [comment]
This is a code explanation of how I using it.
It's correct?

`
TelegramBotsApi telegramBotsApi = new TelegramBotsApi();
TelegramLongPollingBot myBot = new ProximShareBot();
myBot.getOptions().setProxyHost("http://myproxy.com");
myBot.getOptions().setProxyPort(8080);
telegramBotsApi.registerBot(myBot);
`

**Comment by rubenlagus** [comment]
Did the solution from @maloletniy worked for u before?

**Comment by fcioffi** [comment]
I have not tried that. I have not edited the source code for now.

**Comment by fcioffi** [comment]
I tried it and it don't run.

Debugging I have found that the code hangs on line 125 in TelegramBotsApi:

````
private static void setWebhook(String webHookURL, String botToken, String publicCertificatePath) throws TelegramApiException {
...
  try (CloseableHttpResponse response = httpclient.execute(httppost)) {
````

but I'm using LongPollingBot.

What's the error?


Thank you.

**Comment by eightnoteight** [comment]
@fcioffi the setWebhook is executed even if you are using LongPollingBot is because before polling for updates TelegramBots makes sure that the webhook of the bot is set to null by explicitly setting the webhook with an empty string.

so in your system it must be the case that the system can only access Internet through proxy. So the post request gets stuck on that line as the request doesn't follow proxy options.

I made a PR  #138 addressing this issue.

**Comment by rubenlagus** [comment]
@fcioffi and @maloletniy, can you check if it works with lates dev version?

@eightnoteight As explained in the pull request, I made the changes by hand in dev branch.

**Comment by fcioffi** [comment]
Yes, it works  :)

Thanks you....

**Comment by DenisWpk** [comment]
Hi, i read issues about proxy but dont understand how correct use it. 
I using LongPollingBot and add folowing code 
bot.getOptions().setProxyHost("https://10.30.40.19");
bot.getOptions().setProxyPort(3128);

But get error Error executing setWebook method

How correctly use proxy?

Thank you.

**Comment by DenisWpk** [comment]
I find my mistake, http directing me on 80 port. Now I get error: 
Error deserializing setWebhook method response 
A JSONObject text must begin with '{' at 1 [character 2 line 1]
