### ISSUE TITLE
Bot gets empty message text from group

### ISSUE THREAD

**Issue by omfg74** [rubenlagus/TelegramBots#1020]
When i try to send message from group my bot gets update.getMessage().getText() == null
Inline mode is disabled.
Yesterday all worked well. Seems like something wrong with bot or telegram

From direct chat all works well

**Comment by omfg74** [comment]
Found a solution. You need to reply something from bot if message has parameter .getGroupchatCreated()

**Comment by omfg74** [comment]
Finally found out. It is possible to reply null

**Comment by Chase22** [comment]
@omfg74 Then please close this issue
