### ISSUE TITLE
Callback cannot be confirmed

### ISSUE THREAD

**Issue by salat-23** [rubenlagus/TelegramBots#1039]
![image](https://user-images.githubusercontent.com/81823691/157498331-71f2c747-95e8-4bdc-be96-3253e309abed.png)
This clock does not disappear when my bot recieves callback data. Do i need to somehow answer it manually or is it a bug?

**Comment by Chijuk** [comment]
Yes, you need answer manually as official telegram bot api documentation says ([link](https://core.telegram.org/bots/api#callbackquery)).
Use `AnswerCallbackQuery` class for this.
