### ISSUE TITLE
Cyrillic text in InlineKeyboardButton

### ISSUE THREAD

**Issue by maystrovoy** [rubenlagus/TelegramBots#104]
Hi, i having a problem with the Cyrillic text in InlineKeyboardButton.
When i tried:
button.setText("Русский язык");
as the result will be button with "??????? ????" text.
I tried to change the encoding (UTF-8) - gave no results.
Someone can verify or give advice?

**Comment by antonu17** [comment]
Hello, i could not reproduce your error. That's how i built keyboard:
```
        InlineKeyboardMarkup replyKeyboard = new InlineKeyboardMarkup();

        InlineKeyboardButton button = new InlineKeyboardButton();
        button.setText("Russian Русский");
        button.setCallbackData("1");

        List<InlineKeyboardButton> row = new ArrayList<>();
        row.add(button);

        List<List<InlineKeyboardButton>> keyboard = new ArrayList<>();
        keyboard.add(row);

        replyKeyboard.setKeyboard(keyboard);
```
And that's result:
![Image](http://dl2.joxi.net/drive/2016/07/11/0015/0605/987741/41/3c8fcb5a3e.jpg)
Can you show your code in detail?

**Comment by maystrovoy** [comment]
Try send photo:
`if (update.getMessage().getText().equals("/rus")) {
SendPhoto photoMessage = new SendPhoto();
photoMessage.setChatId(update.getMessage().getFrom().getId().toString());
photoMessage.setCaption("Inline Button");
photoMessage.setNewPhoto("/Users/home/dev/telegramcache/72ed9fe3d3c1e563c5d70951d7fedd82.jpg","72ed9fe3d3c1e563c5d70951d7fedd82.jpg");
List<List<InlineKeyboardButton» rows = new ArrayList<>();
List<InlineKeyboardButton> row = new ArrayList<>();
InlineKeyboardButton button = new InlineKeyboardButton();
button.setCallbackData("Test1");
button.setText("Русский");
row.add(button);
button = new InlineKeyboardButton();
button.setCallbackData("Test2");
button.setText("Test2");
row.add(button);
rows.add(row);
InlineKeyboardMarkup markup = new InlineKeyboardMarkup();
markup.setKeyboard(rows);
photoMessage.setReplayMarkup(markup);
try {
sendPhoto(photoMessage);
} catch (TelegramApiException e) {
e.printStackTrace();
}

Then o will have "Test1" and "???????" two buttons.

**Comment by antonu17** [comment]
I think you are using old version of library. I tried to use my inline reply keyboard with `sendPhoto`, its working:
![SendPhoto cyrillic inline](http://dl2.joxi.net/drive/2016/07/12/0015/0605/987741/41/6300875b97.jpg)
Try to use  v2.3.3.4. 
Good luck!

**Comment by maystrovoy** [comment]
can u send me your code?
