### ISSUE TITLE
how to edit bot name with api

### ISSUE THREAD

**Issue by usecocoforhappy** [rubenlagus/TelegramBots#1043]

**Comment by usecocoforhappy** [comment]
i didn't find any method adbout it

**Comment by Chase22** [comment]
That's because there is no method about it. You can't edit the bot name using the api

**Comment by centralhardware** [comment]
you can write user bot that change bot name by sending message with command to the bot father bot, but it's a crutch

**Comment by usecocoforhappy** [comment]
ok thanks anyway
