### ISSUE TITLE
Library error

### ISSUE THREAD

**Issue by cheaterNo1** [rubenlagus/TelegramBots#1050]
My code:
![p1](https://user-images.githubusercontent.com/46472572/160753685-9dc2a40a-a390-4717-8a9c-1dc3001d44b6.PNG)

![p2](https://user-images.githubusercontent.com/46472572/160753691-c882f6ea-ab87-40b8-a36c-2d9096ce3ac1.PNG)

And I got this:

![p3](https://user-images.githubusercontent.com/46472572/160753726-34a4608d-6426-401d-8e78-ca6a546fd67b.PNG)

I found:

![p4](https://user-images.githubusercontent.com/46472572/160753799-2b92fb74-27ee-47d7-8d48-f6d667a552b2.PNG)

**Comment by centralhardware** [comment]
looks like wrong version of dependency. Do you build using maven?

**Comment by centralhardware** [comment]
are you trying to use this library in android. As far as i remember lib don't support android

**Comment by rubenlagus** [comment]
There was discussions about it already, this library is not build focusing on Android so can't ensure whether there is a way to use it

**Comment by rubenlagus** [comment]
Duplicate #1012
