### ISSUE TITLE
Please tell me when you remove this problem from your library?

### ISSUE THREAD

**Issue by MyTestPerson** [rubenlagus/TelegramBots#1063]
Please tell me when you remove this problem from your library?

https://github.com/MyTestPerson/pic/blob/main/Telegram.gif

**Comment by Chase22** [comment]
Okay from the comment i will just assume that you have no idea what the warning actually is:

The warning is a possible security vulnerability in a transitive dependency. In this case org.json:json. Which is a potential DDOS attack is someone send malicious json to the library, i don't know what the dependency is used for specifically in this library but it gets its data from telegram, this attack would have to be a directed attack against a specific bot that happens to have an unsecured webhook controller, that also happens to use this library for the json parsing. If you aren't using webhook you can ignore the warning for know.

@rubenlagus you might want to check what the dependency is used for and if its needed update it to a current version. The version in the pom is from 2018

**Comment by rubenlagus** [comment]
Already updated in Dev, will go with next release
