### ISSUE TITLE
Logger

### ISSUE THREAD

**Issue by dartwata** [rubenlagus/TelegramBots#107]
May be it would be better to use a more abstract entity for logging? I just use my logger and current static instance writes not that it is necessary...

**Comment by rubenlagus** [comment]
You just need to use `BotLogger. registerLogger` and register your own implementation, this way you can use the one you like.

**Comment by dartwata** [comment]
Does "registerLogger" sets logger for all bot instances?! I have logger factory, which extends log4j library for dynamic logger creation with custom filenames and I want to use separate logfile for each bot instance...

**Comment by rubenlagus** [comment]
Yes, it set it for every logger in the api. It receive a java.util.logging.Handler, this way I avoid using a third party library like log4j, this topic was discussed in issue  #74

**Comment by dartwata** [comment]
Ok.. I correctly understand, that I won't be able to register a separate logger for each bot? It one for all bots, right? 
In this case... May be it makes sense to give an opportunity to disable all built-in logging?

**Comment by rubenlagus** [comment]
1. Yes, there is one logger for every bot. 
2. You can disable it completely, just use `setLevel` method.

**Comment by dartwata** [comment]
thx! so simply!
