### ISSUE TITLE
Handle custom_query in Update object

### ISSUE THREAD

**Issue by nvk66** [rubenlagus/TelegramBots#1081]
According to Telegram Update object has a `custom_query` and answers on it should be supported via `answerCustomQuery`. Here are the links to this objects.

https://core.telegram.org/constructor/updateBotWebhookJSONQuery
https://core.telegram.org/method/bots.answerWebhookJSONQuery

It would be great if you will add it to the library

**Comment by rubenlagus** [comment]
@nvk66 you are looking at the wrong docs, the right ones are here: https://core.telegram.org/bots/api
