### ISSUE TITLE
There is no updates for deleted messages

### ISSUE THREAD

**Issue by Futurixel** [rubenlagus/TelegramBots#1084]
Hello there ! 
I was debugging the Update event to see if its fired when someone delete a message on a chat group. 
But i found there is no delete message update fired. 
Is it possible to implement it please ? https://core.telegram.org/constructor/updateDeleteMessages

**Comment by Chase22** [comment]
The bot api does not send updates for deleted messages. If you want this to be implemented you'll have to open an issue in the bot api repository first.

**Comment by Futurixel** [comment]
> The bot api does not send updates for deleted messages. If you want this to be implemented you'll have to open an issue in the bot api repository first.

What about the link i've sended ? This is not implemented on the telegram API ? 

About the bot api repo, is it this one? : https://github.com/tdlib/telegram-bot-api

**Comment by Chase22** [comment]
No, the telegram api and the telegram bot api are 2 different things. The repo is the correct one.

**Comment by Futurixel** [comment]
Ok thank you, sended here then: https://github.com/tdlib/telegram-bot-api/issues/286

Is there not any other way to get deleted messages using the telegram bot api right now ?

**Comment by rubenlagus** [comment]
@Futurixel all available methods are present in https://core.telegram.org/bots/api
