### ISSUE TITLE
After deploying my telegram bot app the connection to my chatbot get lost after a while

### ISSUE THREAD

**Issue by naserkaka** [rubenlagus/TelegramBots#1085]
My telegram bot session stops automatically after a while when deploying it to GCP Virtual machine
How can I keep the connection to my telegram active nonstop
my Main class 

    @Override
    public void run(String... args) throws Exception {
    	LOGGER.info("[run] {}");
        telegramFunc = new TelegramFunc();
        TradesDB.create();

        try {
            TelegramBotsApi botsApi = new TelegramBotsApi(DefaultBotSession.class);
            botsApi.registerBot(new TelegramFunc());

        } catch (TelegramApiException e) {
            e.printStackTrace();
        }
        LOGGER.info("finished running");
    }

**Comment by rubenlagus** [comment]
@naserkaka Enable debug log and it should help to show why it fail.

**Comment by naserkaka** [comment]
thanks for the quick answer!
