### ISSUE TITLE
How do I enforce users joining a specific channel before using my bot?

### ISSUE THREAD

**Issue by spiritLHLS** [rubenlagus/TelegramBots#1092]
**Is your feature request related to a problem? Please describe.**
[How do I enforce users joining a specific channel before using my bot?](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-requested-design-patterns#how-do-i-enforce-users-joining-a-specific-channel-before-using-my-bot)
↑
Similar to the function of python-telegram-bot above, does java have a similar practice method?

**Describe the solution you'd like**
Hopefully there is a way to support the ability to query if a user is in a channel or group.

**Describe alternatives you've considered**
[How do I enforce users joining a specific channel before using my bot?](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Frequently-requested-design-patterns#how-do-i-enforce-users-joining-a-specific-channel-before-using-my-bot)
↑
Similar to the function of python-telegram-bot above, does java have a similar practice method?

**Additional context**
NOTHING.

**Comment by rubenlagus** [comment]
GetChatMember is an standard method of the Telegram Bots API available in the library to check if an user is member of it

**Comment by spiritLHLS** [comment]
> GetChatMember is an standard method of the Telegram Bots API available in the library to check if an user is member of it

Thanks
