### ISSUE TITLE
any simpe exampe to work with GetChatAdministrators

### ISSUE THREAD

**Issue by PouriaParhami** [rubenlagus/TelegramBots#110]
Hello i looking for simple example to work with GetChatAdministrators , when i use this class like this 
  GetChatAdministrators getAmins = new GetChatAdministrators();
                   
                    getAmins.deserializeResponse();
it want a jsonObject , which jsonObjec ??

**Comment by rubenlagus** [comment]
Hi this should do it:


``` 
        GetChatAdministrators getAdmins = new GetChatAdministrators();
        getAdmins.setChatId("@yourchatusernameoryourchatid");
        List<ChatMember> admins = getChatAdministrators(getAdmins);
```

**Comment by PouriaParhami** [comment]
Dear Ruben , thank you so much
