### ISSUE TITLE
Can somebody PLEASE tell me why SendMediaGroup is not able to be used by sender.execute?

### ISSUE THREAD

**Issue by chrisstubbs1** [rubenlagus/TelegramBots#1140]
I have been stuck on this issue for WEEKS. For some reason I am not able to use a SendMediaGroup object inside of MessageSender.execute(). It works fine with all other message types just not this one. Is this a bug with the api? Has anyone else encountered this? 

![image](https://user-images.githubusercontent.com/48082925/198413257-31e0b0b2-f062-41f5-93f3-2df2c3bfbb56.png)

**Comment by laal28** [comment]
How did you solved that?
