### ISSUE TITLE
[Bug] Message not getting displayed

### ISSUE THREAD

**Issue by qeinz** [rubenlagus/TelegramBots#1160]
**Describe the bug**
When I try to fetch a user's message via `public void onUpdateReceived(Update update) {` I only get isolated messages, i.e. every 5 or 10 first.

**To Reproduce**
Use the following code:
```
@Override
    public void onUpdateReceived(Update update) {
        System.out.println("message rwecieved");
    }
```

We using debian server with java on it

**Comment by qeinz** [comment]
also using the latest api version

**Comment by qeinz** [comment]
WOW STOP!

made a very very very interesting discovery with my friend (telegram is very lost btw)

this error only occurs when using the telegram windows app

now come on:

as long as this is done in the web application IT WORKS 100%.

**Comment by Chase22** [comment]
Can you elaborate on the error? You are sending a message to the bot in a private chat(?) And the message is not received by the bot. Correct?

If it's a problem with a specific client I'm certain there's nothing we can do about it, the library is simply using an API from telegram, which doesn't even tell us which client is used.
