### ISSUE TITLE
Send sticker by sticker id

### ISSUE THREAD

**Issue by geriko2000** [rubenlagus/TelegramBots#1185]
Add the ability to send stickers not only via inputFile, but also via Telegram sticker id

**Comment by aminovmaksim** [comment]
You can do it by setting **Media** property of **InputFile** with existing sticker id.
For example:
```
var sticker = new InputFile();
sticker.setMedia("YOUR_STICKER_ID");

bot.execute(new SendSticker(chatId, sticker));
```
