### ISSUE TITLE
getPermissions and setPermissions not working

### ISSUE THREAD

**Issue by madoverflow** [rubenlagus/TelegramBots#1188]
Hi guys,
I've tried to get group permissions through getPermissions method of chat object but ti returned me a null value. 
I promoted my bot to administrator but i got the same result.
However, I've tried to set them thtrough setPermissions method (giving it a ChatPermissions object with the new rules) but nothing was changed.
Maybe, I was wrong to use the methods.
Can anyone help me with this issue?  

-Ubuntu 22.04LTS
-Brave

**Comment by timursergeevichname** [comment]
`permissions - Optional. Default chat member permissions, for groups and supergroups. Returned only in [getChat](https://core.telegram.org/bots/api#getchat).`

use example
```java 
final GetChat getChat = GetChat.builder()
                .chatId(message.getChatId())
                .build();
try {
            final Chat chat = execute(getChat);
            final ChatPermissions permissions = chat.getPermissions();
 } catch (TelegramApiException e) {
            e.printStackTrace();
 }
```

**Comment by madoverflow** [comment]
> `permissions - Optional. Default chat member permissions, for groups and supergroups. Returned only in [getChat](https://core.telegram.org/bots/api#getchat).`
> 
> use example
> ```java 
> final GetChat getChat = GetChat.builder()
>                 .chatId(message.getChatId())
>                 .build();
> try {
>             final Chat chat = execute(getChat);
>             final ChatPermissions permissions = chat.getPermissions();
>  } catch (TelegramApiException e) {
>             e.printStackTrace();
>  }
> ```
> 
> To set the chat permission use the SetChatPermissions class.
> 
> use example
> 
> ```java
> final SetChatPermissions setChatPermissions = SetChatPermissions.builder()
>                 .chatId(message.getChatId())
>                 .permissions(ChatPermissions.builder()
>                         .canAddWebPagePreviews(true)
>                         .canInviteUsers(false)
>                         .build()
>                 ).build();
> 
>  try {
>             Boolean success = execute(setChatPermissions);
>  } catch (TelegramApiException e) {
>             e.printStackTrace();
>  }
> 
> ```

Thanks for reply!
I had solved the problem but I forgot to edit my topic with the solution. I used the class SetChatPermission like you
