### ISSUE TITLE
update.getPollAnswer() returns null

### ISSUE THREAD

**Issue by HouZzzz** [rubenlagus/TelegramBots#1193]
**Description of the bug**
getPollAnswer method returns null value, but request from telegramAPI shows the poll answer

**To Reproduce**
1. Send not anonymous poll with allowed multiple answers.
2. vote for any option (one or many, doesn't matter)
3. see the null value from update.getPollAnswer()

**Screenshots**
request for updates from telegram api
![image](https://user-images.githubusercontent.com/105144213/221400247-5270b949-9885-4819-b344-f188e3d97592.png)

result in java when doing same action
![image](https://user-images.githubusercontent.com/105144213/221400380-93ad045b-9785-42d7-95ed-b7da6783b800.png)

**Project dependencies where can be conflict**
spring boot v2.7.1
hibernate v5.4.21
jackson databind v2.11.3
telegrambots v6.5.0

**Comment by Alpha2J** [comment]
I've encountered this issue as well, and I believe it's a bug caused by multithreading problems.

**Comment by migueltercero** [comment]
Same here. I can´t read answers.

spring boot 3.1.8
telegrambots 6.9.7.1 and 6.9.7.0

**Comment by rubenlagus** [comment]
I've added a test [here](https://github.com/rubenlagus/TelegramBots/pull/1307/files#diff-94950084bff8ed07095bbd7baf478f49567bd33819e1247c2c33fe5486d307beR58) to validate this case and data is properly generated. 

Do you have a quick test where this potential bug manifest?

**Comment by migueltercero** [comment]
Hi, I have this test:

```
public Ability simplePoll() {

        return Ability.builder()
                .name("poll")
                .info("Simple poll")
                .input(0)
                .locality(USER)
                .privacy(Privacy.ADMIN)
                .action(ctx -> {
                    var poll = SendPoll.builder()
                            .chatId(ctx.chatId())
                            .type("quiz")
                            .question("Question")
                            .option("option 1")
                            .option("option 2")
                            .correctOptionId(1)
                            .build();
                    try {
                        this.execute(poll);
                    } catch (Exception validation) {
                        log.error("Pregunta {}: {}", poll.getQuestion(), validation.getMessage());
                    }
                })
                .reply(
                        (bot, upd) -> {
                            log.debug("Update: {}", upd);
                        },
                        Flag.POLL_ANSWER)
                .setStatsEnabled(true)
                .build();
    }
```

When I select `Option 1` or `Option 2` in Telegram, `reply` don´t receive nothing. 

however, in log (in info level) I can see this when poll is answered (I replace ids with *):

```
2024-02-18T12:55:59.652+01:00  INFO 24136 --- [legram Executor] o.t.abilitybots.api.bot.BaseAbilityBot   : Update(updateId=****, message=null, inlineQuery=null, chosenInlineQuery=null, callbackQuery=null, editedMessage=null, channelPost=null, editedChannelPost=null, shippingQuery=null, preCheckoutQuery=null, poll=Poll(id=****, question=Question, options=[PollOption(text=option 1, voterCount=0), PollOption(text=option 2, voterCount=1)], totalVoterCount=1, isClosed=false, isAnonymous=true, type=quiz, allowMultipleAnswers=false, correctOptionId=1, openPeriod=null, closeDate=null, explanation=null, explanationEntities=null), pollAnswer=null, myChatMember=null, chatMember=null, chatJoinRequest=null, messageReaction=null, messageReactionCount=null, chatBoost=null, removedChatBoost=null)
```

As you can see in log, i received response event, but pollAnswer is null. 

What am I doing wrong?

Thank you!!!
