### ISSUE TITLE
InlineKeyboardButton's without url are not shown

### ISSUE THREAD

**Issue by vopv** [rubenlagus/TelegramBots#120]
Hi,

Inline buttons are not shown unless HTTP url is set which should to be optional.

Thank you.

**Comment by rubenlagus** [comment]
Can you provide a sample code to reproduce?

**Comment by vopv** [comment]
I just got (had to post it here to understand). You have to set either url or callBackData in order to show inline button. This is correct behaviour I think.

**Comment by rubenlagus** [comment]
Indeed, only text buttons (without any functionality) are not allowed. Closing this ;)
