### ISSUE TITLE
how to make a group link to share , and user click this link ,i can take it?

### ISSUE THREAD

**Issue by simply-lu** [rubenlagus/TelegramBots#1204]
i have a group , i think to make a link , like (https://t.me/group_link?invite=abc), users click the link to join my group . how to catch the invite？

**Comment by samosxin** [comment]
private group can get inviteLink from update.chatJoinRequest

**Comment by guozhenma** [comment]
> private group can get inviteLink from update.chatJoinRequest

How about public group?

**Comment by guozhenma** [comment]
> i have a group , i think to make a link , like (https://t.me/group_link?invite=abc), users click the link to join my group . how to catch the invite？

Have you solved the problem?

**Comment by chasonHgg** [comment]
> i have a group , i think to make a link , like (https://t.me/group_link?invite=abc), users click the link to join my group . how to catch the invite？

Have you solved the problem?

**Comment by rubenlagus** [comment]
You need to listen to the chat_member updates https://core.telegram.org/bots/api#update
