### ISSUE TITLE
Exception on sending message with underline character

### ISSUE THREAD

**Issue by azimot** [rubenlagus/TelegramBots#121]
i catch exception when i want to sending underline '_' to bot 

```
org.telegram.telegrambots.TelegramApiException: Error at sendmessage: 
Bad Request: Can't parse message text: Can't find end of the entity starting at byte offset 264
```

i find that happen when i had underline character in my message text 
it's seems underline is a special character in bot API like as '\' in java String that must be use '\\\\' for that
how can i to resolve ?

**Comment by rubenlagus** [comment]
Same as in java, what about escaping it too with '\'? Another option is that you don't use Markdown parse mode.

**Comment by azimot** [comment]
with the '\' not worked but after i used to set SendMessage.enableHtml(true) worked !

**Comment by rubenlagus** [comment]
I'm using '\' to escape character in the messages and works correctly. Maybe you are escaping too much or something. enabling html markdown just change the type of markdown.

**Comment by azimot** [comment]
yes it's worked ! i check in code and see i had a mistake by myself in end of SendMessage operation

**Comment by Clevero** [comment]
What was exactly your error?

Currently, my problem is that I want to list all my users. With their First, Last and username. It seems that one user has special characters in this name that is interpreted as a markdown thing. 

Since I get the same error message, I wonder If I do the same error as you did.

**Comment by azimot** [comment]
hmm in username phrase ! i dont think about it yet !! 
but i did catch that error when i want to send message to users because some message must be have some special characters and other dont need.

so in your case you could to create a Pattern Object and check username phrase with Regex if it's have markdown characters then enable markdown and if have html characters enable html 
i think in this way you could to resolve your problem

**Comment by hems** [comment]
For me scaping _ with \ isn't working!

**Comment by KilluaFein** [comment]
I also have problem like @hems, can't escape _ with \.

**Comment by hems** [comment]
@KilluaFein if i'm not mistaken i had to scape with \\ instead! like \\_

**Comment by Fotomultman** [comment]
Yes, the problem is not solved yet

**Comment by Clevero** [comment]
@Fotomultman do you escaped properly?

**Comment by Fotomultman** [comment]
I tried but no result :( I'm wondering, could you tell me how to do it right?

**Comment by Clevero** [comment]
```java

//should fail
String text = "My amazing text _ is really awesome";
sendMessage.setText(text);

```

```java

//escape the character
String text = "My amazing text \\_ is really awesome";
sendMessage.setText(text);

```


Some explanations in a Java [tutorial](https://docs.oracle.com/javase/tutorial/java/data/characters.html) at Oracle

**Comment by Fotomultman** [comment]
try this way... no result
`message.getFrom().getId().toString().replace("_","\\_l")`

**Comment by Fotomultman** [comment]
As you said before
```

//escape the character
String text = "My amazing text \\_ is really awesome";
sendMessage.setText(text);
```
works fine, but when I try to execute 

`sndMessage(message,message.getSticker().getFileId().replaceAll("_","\\_"))`
It it suitable to use replaceAll("_","\\_") ciuntruction in this way?

Sorry if it is a silly question :)

**Comment by Clevero** [comment]
Have tested similar code to yours, cannot reproduce your issue:

```java
String text = "My amazing text is _ awesome";
                	
sndMessage(message,text.replaceAll("_","\\_"));

```

Whereas ```sndMessage()``` is a method that creates a SendMessage object and fire its up with execute()

**Comment by Fotomultman** [comment]
I dont know how but it works with

 `sndMessage(message,message.getSticker().getFileId().replaceAll("_","\\\\_"))`

**Comment by Fotomultman** [comment]
yes, it works... dont no why I doesnt work yesterday...

**Comment by Fotomultman** [comment]
BTW

```
String mysticker;
                String mysticker_txt;
                mysticker_txt = message.getSticker().getFileId().replaceAll("_","\\\\_");
                sndMessage(message,mysticker_txt);
            ```

It wirks with `\\\\_` mask
