### ISSUE TITLE
Request Entity Too Large

### ISSUE THREAD

**Issue by Clownsw** [rubenlagus/TelegramBots#1215]
I sent a video with a size of 3285932 bytes, and an error occurred. The request body is too large. How can I solve it?

**Comment by centralhardware** [comment]
https://core.telegram.org/bots/faq#how-do-i-upload-a-large-file

**Comment by Clownsw** [comment]
> https://core.telegram.org/bots/faq#how-do-i-upload-a-large-file

Thank you

**Comment by centralhardware** [comment]
@Clownsw you can increase limits up to 2GB, if you connecting to self hosted telegram bot api server, theoretically https://hub.docker.com/r/aiogram/telegram-bot-api
