### ISSUE TITLE
/wiki/Getting-Started needs to be updated

### ISSUE THREAD

**Issue by iamgul** [rubenlagus/TelegramBots#1219]
[/wiki/Getting-Started](https://github.com/rubenlagus/TelegramBots/wiki/Getting-Started) needs to be Updated to call the constructor to pass the token instead of calling getBotToken() since it's deprecated.

Here are the changes:
```
	public MyAmazingBot() {
		super("Your Token");
	}
```

![Issue image](https://github.com/rubenlagus/TelegramBotsExample/assets/38118279/26b2299f-ddee-441f-85f9-4e8b9fe6c64d)

**Comment by Chase22** [comment]
I did propose a fix in #1194
