### ISSUE TITLE
[Bug] Bold not worked in HTML style and Markdown too

### ISSUE THREAD

**Issue by azimot** [rubenlagus/TelegramBots#123]
i test it by two way 
one is enabled HTML (Markdown is default) and passing <b> xxxx </b> 
two is enabled Markdown (HTML is default) and passing * xxxx * 
in both not difference in output 
inline , link and pre-formatted are OK 
in HTML style i tested by corresponding HTML entities too (  < with &lt;, > with &gt;   )

**Comment by rubenlagus** [comment]
I'm using this and it works as expected, can you give a code sample where it doesn't work?

```java
        SendMessage message = new SendMessage();
        message.setText("<strong>Bold text</strong>");
        message.enableHtml(true);
        sendMessage(message);
```

**Comment by azimot** [comment]
this is my test code :
`private void sendMessageToChannel(String username, String content) {
        SendMessage sendMessage = new SendMessage().enableHtml(true);
        sendMessage.setChatId(username.trim());
        sendMessage.setText("<strong> " + content + " </strong>");
        try {
            sendMessage(sendMessage);
        } catch (TelegramApiException e) {
            e.printStackTrace();
        }
    }`

**Comment by rubenlagus** [comment]
With that same code, it works correctly. Maybe your "content" variable has something that break the markdown or html. Don't forget to escape all necessary characters.

```
                    SendMessage sendMessage = new SendMessage().enableHtml(true);
                    sendMessage.setChatId("@myramdomnicechannel");
                    sendMessage.setText("<strong> My random content </strong>");//with the <b>tag is as same result
                    //also when i send *xxx* Markdown too but others are OK
                    try {
                        sendMessage(sendMessage);
                    } catch (TelegramApiException e) {
                        e.printStackTrace();
                    }
```

If you have any example of `content` that should work and doesn't, feel free to reopen the issue.
