### ISSUE TITLE
When I send message with photo, happens this:

### ISSUE THREAD

**Issue by ItzAnubis-hub** [rubenlagus/TelegramBots#1242]
![image](https://github.com/rubenlagus/TelegramBots/assets/68167253/86d4d577-1108-4791-a2d8-e4d9a9f50e15)
![image](https://github.com/rubenlagus/TelegramBots/assets/68167253/a4c26274-d68a-430b-869e-f3a00f00aad1)
![image](https://github.com/rubenlagus/TelegramBots/assets/68167253/bfe00fcf-b4ed-45c2-aa84-d27804462178)

Why is this happening?
P.S When We send message to bot WITHOUT photo, the message.hasText() = true; With photo - false.

**Comment by Longmanrus** [comment]
because it's caption, not text... differend field
