### ISSUE TITLE
Poll Answers

### ISSUE THREAD

**Issue by SaMssasd** [rubenlagus/TelegramBots#1244]
How can i get to know which options were selected in a poll (non anonymus and with multiple options enabled).
I don't even need to know how often they were voted for just if they were voted for at least once, so that i can work woth that.

My poll:
SendPoll poll = new SendPoll(update.getMessage().getChatId().toString(), "myQuestion", OP());
poll.setAllowMultipleAnswers(allowMultipleAnswers);
poll.setIsAnonymous(false);
try{
        execute(poll);
}catch (TelegramApiException e){
	// TODO Auto-generated catch block
	e.printStackTrace();
}

**Comment by NaveenB2004** [comment]
You need to listen to the `bot updates` and filter if it's a `poll update`. If it's a poll, you can identify it using `id`, _Unique poll identifier_ (see [Poll](https://core.telegram.org/bots/api#poll)). When you send the poll (as you mentioned above), store the return `id` of the poll. It will help you when it comes to identification processes (see [SendPoll](https://core.telegram.org/bots/api#sendpoll)).
