### ISSUE TITLE
HttpClient NPE

### ISSUE THREAD

**Issue by 4o4-Not-Found** [rubenlagus/TelegramBots#1246]
telegrambots-spring-boot-starter:6.7
springboot:2.6.5

The bot is implemented by inheriting the SpringWebhookBot.

```
    @Autowired
    public Bot(SetWebhook setWebhook, @Value("${telegrambot.token}") String botToken) {
        super(setWebhook, botToken);
    }
```

When using the defaultAbsSender.execute() method, sending a SendMessage is ok, but when sending a SendSticker the httpClient is null.

<img width="1079" alt="image" src="https://github.com/rubenlagus/TelegramBots/assets/28617648/e82c03a3-4707-4a84-8afe-32b6905924ae">

<img width="999" alt="image" src="https://github.com/rubenlagus/TelegramBots/assets/28617648/6a37cb73-2af6-4deb-92dd-007c4fb3e739">

**Comment by 4o4-Not-Found** [comment]
somebody help T.T

**Comment by rubenlagus** [comment]
Please check new version HttpClient is no used anymore
