### ISSUE TITLE
拉机器人进群的时候设置管理员无法收到进群时候的绑定消息

### ISSUE THREAD

**Issue by kunkunxiong** [rubenlagus/TelegramBots#1255]
![image](https://github.com/rubenlagus/TelegramBots/assets/42628350/c2c2c0c2-3932-4c79-8754-2a8e6e5f61e5)
进群链接中startgroup传参，在机器人进群自动发送，而发送的消息并未触发监听的onUpdateReceived方法

**Comment by centralhardware** [comment]
please use english

**Comment by kunkunxiong** [comment]
I have encountered a problem. When the robot enters the group as an administrator, the method of listening should receive three messages, but only one message is received. I would like to ask your help to find out what went wrong.

**Comment by samosxin** [comment]
这方面java api确实是缺失的，我也遇到了

**Comment by kunkunxiong** [comment]
> 这方面java api确实是缺失的，我也遇到了

Is there any good way to solve this problem? I found that many similar websites have this problem.

**Comment by rubenlagus** [comment]
Report again in English
