### ISSUE TITLE
Bug: Registering a command does not work in 2.3.3.6

### ISSUE THREAD

**Issue by sleighsoft** [rubenlagus/TelegramBots#126]
I just used the TelegramBotsExample project and set the version to v2.3.3.6 and this results in the CommandHandler not processing commands.

**Comment by alejandrocq** [comment]
I have the same issue. I have registered a start command, but it's not working in this version. I have moved my project back to 2.3.3.4 version of the API and all is working fine for the moment.

**Comment by azimot** [comment]
take a look at : https://github.com/rubenlagus/TelegramBots/issues/127

**Comment by rubenlagus** [comment]
Wrong true in wrong place. Should be fixed in next version.
