### ISSUE TITLE
How to register a command so that Telegram shows it?

### ISSUE THREAD

**Issue by sleighsoft** [rubenlagus/TelegramBots#127]
When I register a command I can use it but Telegram does not show it as being available like for example the Botfather bot does.

Is this simply not implemented yet or not possible?

**Comment by Clevero** [comment]
You need to set these commands at BotFather with ```/setcommands```.

After setting the commands it is sometimes useful the restart your client (if you don't see the commands after setting them)

**Comment by sleighsoft** [comment]
Ah, thank you :)
