### ISSUE TITLE
api 如何获取到公开频道新的关注信息，我的getupdate 一直都没有进来，检测不到新的关注啊

### ISSUE THREAD

**Issue by buhuanyi** [rubenlagus/TelegramBots#1277]
api 如何获取到公开频道新的关注信息，我的getupdate 一直都没有进来，检测不到新的关注啊

**Comment by OpticalEngineering** [comment]
使用英文提问，这是对社区的基本尊重，这样你的问题所有人都看得懂，同时也利于其他遇到相似问题人搜索

you can add "chat_member" in DefaultBotOptions's allowedUpdates when you create a AbilityBot, codes likes:
``` java
botOptions.setAllowedUpdates(Arrays.asList("chat_member"));
```
notes: you need to add other update types that you want your bot to receive too

The reason for this is  Specify an empty list to receive all update types **except** chat_member (default), you can refer to allowed_updates's description in getUpdates.
