### ISSUE TITLE
Setting httpClient directly without using TelegramHttpClientBuilder

### ISSUE THREAD

**Issue by DmitryFedorov7** [rubenlagus/TelegramBots#1280]
**Is your feature request related to a problem? Please describe.**
As a bot I use a class inherited from DefaultAbsSender. I want to be able to configure httpClient myself, because the functionality of TelegramHttpClientBuilder is very limiting for me. For example, I want to set my own implementation of SystemDefaultRoutePlanner and use system properties (useSystemProperties function). There is also no way to close httpClient after the bot exits, because the field is private (although this is supported for ExecutorService exe).

**Describe the solution you'd like**
Perhaps it is worth adding the ability to specify httpClient directly (via the constructor or DefaultBotOptions) and make it protected? And also support this in the DefaultBotSession class

**Comment by rubenlagus** [comment]
HttpClient is not used anymore in the library
