### ISSUE TITLE
Whether maxConnTotal can be modified as a configurable item

### ISSUE THREAD

**Issue by prog-ape** [rubenlagus/TelegramBots#1281]
org.telegram.telegrambots.facilities.TelegramHttpClientBuilder

public static CloseableHttpClient build(DefaultBotOptions options) {
        HttpClientBuilder httpClientBuilder = HttpClientBuilder.create()
                .setSSLHostnameVerifier(new NoopHostnameVerifier())
                .setConnectionManager(createConnectionManager(options))
                .setConnectionTimeToLive(70, TimeUnit.SECONDS)
                .setMaxConnTotal(100);
        return httpClientBuilder.build();
    }

Whether maxConnTotal can be modified as a configurable item？

**Comment by rubenlagus** [comment]
Related to <7.0 versions
