### ISSUE TITLE
No documentation for new version.

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [rubenlagus/TelegramBots#129]
Hello.

I had first version of this library and I have just updated it to latest release. Now all my `SendMessage` codes does not work. And there is no proper exmplanation of how to use this lib.

Please, add some documentation, not only for creating bot client, but for `sending messages`, `sending files` and `custom keyboards.`

**Comment by Clevero** [comment]
Currently, there is a HOWTO in progress with a FAQ section. There is also an open PR at #124 for it
It is not really perfect at the moment, but I would appreciate feedback :) There is also an answered question about sending custom keyboards

So, if you want an another example to be mentioned, please tell me then I'm going to add this :)

The codebase from this project was slightly changed where Bot API 2.0 was implemented. All Send{type} (e.g. SendMessage, SendVoice) were moved from `api/methods/SendMessage.java` to `api/methods/`**send**`/SendMessage.java` [All changes here](https://github.com/rubenlagus/TelegramBots/commit/c587f832040413fb5935b7599b8ab085b04cc56c)

If you have further questions about a specific problem, feel free to open a new issue if your question was not already answered

**Comment by Clevero** [comment]
And for more info's on how to use this lib, you can check out the [TelegramBotseample](https://github.com/rubenlagus/TelegramBotsExample) Repo. 

Which bot uses wich part of this library can be found in the README under "[Example bots](https://github.com/rubenlagus/TelegramBots#example-bots)"

**Comment by rubenlagus** [comment]
I have merged the HOWTO to dev branch, will be in master soon. 

I think that @Clevero already explained everything, in any case feel fee to join our Telegram group if you need exact questions.

P.S: If you moved from first version to latest one, I'd say it is something normal that it doesn't work directly... There have been tons of changes since then.
