### ISSUE TITLE
Upload file to telegram servers and use it afterwards

### ISSUE THREAD

**Issue by igolyudov** [rubenlagus/TelegramBots#1332]
InputFile class have javadoc described "Input file used to upload a file to Telegram server and use it afterwards".
But how i can get file_id for uploaded file and use it afterwards for send user?

**Comment by NaveenB2004** [comment]
If you're using the bot to upload (literally send) [`Document`](https://core.telegram.org/bots/api#document) (general file, as opposed to [photos](https://core.telegram.org/bots/api#photosize), [voice messages](https://core.telegram.org/bots/api#voice) and [audio files](https://core.telegram.org/bots/api#audio)), you will receive the [`Message`](https://core.telegram.org/bots/api#message) object that holding the mentioned `Document` object after successful execution. You can get the `file_id`, _Identifier for this file, which can be used to download or reuse the file_ from that object.

```java
// bot token
final String BOT_TOKEN = "123456xxxxxy";
// assign the client
TelegramClient telegramClient = new OkHttpTelegramClient(BOT_TOKEN);

// target chat id that file should be sent (String/Long)
final String CHAT_ID = "123456xxxxx";
// java.io.File (solid file) or String (URL to the target file) or String (file_id of the target file - your question)
final java.io.File FILE = new File("location");
// final String FILE = "https://example.com/targetFile";

SendDocument doc = SendDocument.builder()
   .chatId(CHAT_ID)
   .document(new InputFile(FILE))
   .build();
// other doc settings

Message message = null;
try {
     message = telegramClient.execute(doc);
} catch (TelegramApiException e) {
     // handle the exception
}
        
if (message != null) {
     String fileId = message.getDocument().getFileId();
     // other operations
}
```

Or, you can send your target file to the bot and get the update using the `consume(Update update)` method by invoking `String fileId = update.getMessage().getDocument().getFileId();`.

Now you have the `fileId`. Use it in the `SendDocument` builder as `.document(new InputFile(fileId))` to send it. 👍  See also [InputFile](https://core.telegram.org/bots/api#inputfile).

Maybe this is out of the question, but you can use bots like [Telegram Bot Raw](https://t.me/RawDataBot) to get the `Message` object details (in JSON format) without configuring your own bot.
