### ISSUE TITLE
Get all users from Bot

### ISSUE THREAD

**Issue by Elias177Dev** [rubenlagus/TelegramBots#1341]
Hey,

currently i try to code a TelegramBot with the Java API.
I want to send a broadcast Message to all users, but how?

Does anyone know how i can get a list of users, who send the Bot a message? (User who have a open conversation with the bot)

**Comment by WildTigerrr** [comment]
The only way is to store each user in DB (or somewhere). Telegram doesn't provide this information

**Comment by Elias177Dev** [comment]
Okay, but it would be enough to save the username and chat id in the database, wouldn't it? So I can then write to the user again with?

**Comment by Chase22** [comment]
Yes that will be enough. Just make sure to throttle your bot when doing broadcasts
