### ISSUE TITLE
can not find v7.2.0 in maven central repository and gitpack

### ISSUE THREAD

**Issue by littson** [rubenlagus/TelegramBots#1342]
1. maven central repository does not have v7.2.0.
2. jitpack only have `.pom` but no `.jar` file: https://jitpack.io/com/github/rubenlagus/TelegramBots/Bots/7.2.0/

**Comment by niekarends** [comment]
Just wanted to chip in. Currently, the [latest available version of Telegrambots](https://central.sonatype.com/artifact/org.telegram/telegrambots) in Maven Central is 6.9.7.1

**Comment by rubenlagus** [comment]
As part of v7, there are changes in dependencies and ask to the Jars: https://rubenlagus.github.io/TelegramBotsDocumentation/how-to-update-7.html
