### ISSUE TITLE
SetParseMode for SendMessage?

### ISSUE THREAD

**Issue by johnyleebrown** [rubenlagus/TelegramBots#135]
How to set parse_mode for SendMessage object?

**Comment by Clevero** [comment]
Currently, Telegram supports two parse modes. Markdown and HTML.

You can set each of them in this lib with their own methods:

```SendMessage.enableMarkdown(enable: boolean)```
and
```SendMessage.enableHtml(enable: boolean)```

**Comment by johnyleebrown** [comment]
Yes, that's right. But how to pass the HTML field for example to use it?
