### ISSUE TITLE
how to Create a menubutton in the code

### ISSUE THREAD

**Issue by hurra2025** [rubenlagus/TelegramBots#1351]
i want to create a BotCommand ,how to use   SetMyCommands.
eg
public void registerCommands() {
        List<BotCommand> commands = Arrays.asList(
                new BotCommand("/start", "start"),
                new BotCommand("/help", "help"));
        SetMyCommands setMyCommands = new SetMyCommands();
        setMyCommands.setCommands(commands);
        try {
            execute(setMyCommands);
        } catch (TelegramApiException e) {
            e.printStackTrace();
        }
    }

**Comment by rubenlagus** [comment]
There are docs for it already: https://rubenlagus.github.io/TelegramBotsDocumentation/lesson-6.html
