### ISSUE TITLE
InputKeyboardButtonUserProfile not found

### ISSUE THREAD

**Issue by qwguagua** [rubenlagus/TelegramBots#1357]
InputKeyboardButtonUserProfile not found

https://core.telegram.org/constructor/inputKeyboardButtonUserProfile
https://docs.pyrogram.org/telegram/types/input-keyboard-button-user-profile#pyrogram.raw.types.InputKeyboardButtonUserProfile

**Comment by rubenlagus** [comment]
That's not the Bots API, so not relevant
