### ISSUE TITLE
Why does my code keep reporting this error?

### ISSUE THREAD

**Issue by freeoptions** [rubenlagus/TelegramBots#1361]
### Why does my code keep reporting this error?

<img width="1277" alt="image_2024-05-20_17-57-42" src="https://github.com/rubenlagus/TelegramBots/assets/48871610/ca4ab5fc-01bb-4603-864c-995c414fe341">
2024-05-15 19:55:29.394 ERROR 426 --- [gram Connection] o.t.t.u.DefaultBotSession: api.telegram.org:443 failed to respond
org.apache.http.NoHttpResponseException: api.telegram.org:443 failed to respond

### Below is my code
<img width="1051" alt="image_2024-05-20_17-58-54" src="https://github.com/rubenlagus/TelegramBots/assets/48871610/527cc992-2bcd-42d1-9427-436aa43ada0e">
<img width="1144" alt="image_2024-05-20_18-01-27" src="https://github.com/rubenlagus/TelegramBots/assets/48871610/829b6aaa-ae36-429c-884d-8ee77563b303">

> 

> 

> 

> 

I just want to use Java to send some messages to Telegram regularly. Although it does not affect the use, the program will keep reporting errors, which makes me very unhappy. How should I solve it?
Please help me solve my doubts, thank you!

**Comment by Chase22** [comment]
Is this happening constantly or occasionally?

You should make sure to run on the newest version. We have switch over to using OkHttp to send requests. 

This might also be caused by the goverment blocking connections to telegram.org.

**Comment by freeoptions** [comment]
It's not accidental, it's always reporting this error

The version I am using is 6.1.0. Following your suggestion, I changed to 6.9.7.1
![image](https://github.com/rubenlagus/TelegramBots/assets/48871610/3f1b0195-ffa4-4b65-af7d-242dbd1152f5)


Maybe it was intercepted by the government, but I'm not sure.

thank you~

**Comment by freeoptions** [comment]
> Is this happening constantly or occasionally?
> It's not accidental, it's always reporting this error

> You should make sure to run on the newest version. We have switch over to using OkHttp to send requests.
> The version I am using is 6.1.0. Following your suggestion, I changed to 6.9.7.1
![image](https://github.com/rubenlagus/TelegramBots/assets/48871610/e24d4781-3ca9-402a-960d-8003674dd296)


> This might also be caused by the goverment blocking connections to telegram.org.
Maybe it was intercepted by the government, but I'm not sure.






thank you~

**Comment by Chase22** [comment]
The current version is 7.2. Checkout the docs on how to update:
https://rubenlagus.github.io/TelegramBotsDocumentation/how-to-update.html#to-version-7-0-0

**Comment by freeoptions** [comment]
> The current version is 7.2. Checkout the docs on how to update: https://rubenlagus.github.io/TelegramBotsDocumentation/how-to-update.html#to-version-7-0-0


Oh, are you talking about Telegram Bots Meta? The latest version of Telegram Bots Meta is indeed 7.2.1. I am currently using the latest version of Telegram Bots 6.9.7.1. Then I will try version 7.2.1 of Telegram Bots Meta first. Thank you.

![image](https://github.com/rubenlagus/TelegramBots/assets/48871610/96b701f7-bcd1-46ca-b1d6-02a2c013d965)

**Comment by Chase22** [comment]
No. I'm talking about the whole library. It is split into multiple modules now. The teleframbots dependency is deprecated

**Comment by freeoptions** [comment]
> No. I'm talking about the whole library. It is split into multiple modules now. The teleframbots dependency is deprecated

So the latest dependency is Telegram Bots Meta 7.2.1? It seems that I need to change the Telegram Bots dependency to Telegram Bots Meta.

thank you！
