### ISSUE TITLE
Unresolved reference: update.getCallbackQuery().getMessage().getText()

### ISSUE THREAD

**Issue by nikmax42** [rubenlagus/TelegramBots#1362]
**Describe the bug**
I want to change inline keyboard markup, but keep message text unchanged. So I'm using EditMessageText() and setting new replyMarkup and old text. 
In debugger I see that `getCallbackQuery().getMessage()` object contains field `text` with my original message. If I do `message.toString()` result string contains `text` filed with my message. But I cannot access it because library allows me to get only `chatId`, `messageId`, `chat` and `date` fields in `callbackQuery.message` object, but not `text` field (Unresolved reference).

**To Reproduce**
1. get callbackQuery after inline keyboard button click
2. get callback query message
3. try to access `text` field
4. get` Unresolved reference` compiler error

**Expected behavior**
Access to `callbackQuery.message.text` field

**Desktop (please complete the following information):**
 - Version [7.2.1]

**Comment by aNNiMON** [comment]
`getCallbackQuery().getMessage()` [returns](https://github.com/rubenlagus/TelegramBots/blob/9ab02a367f1de57a4be3bb24de32e0619d41d430/telegrambots-meta/src/main/java/org/telegram/telegrambots/meta/api/objects/CallbackQuery.java#L60) a type [`MaybeInaccessibleMessage`](https://github.com/rubenlagus/TelegramBots/blob/9ab02a367f1de57a4be3bb24de32e0619d41d430/telegrambots-meta/src/main/java/org/telegram/telegrambots/meta/api/objects/message/MaybeInaccessibleMessage.java#L41-L47) which can be either `Message` or `InaccessibleMessage`. You need to check a type first, then cast to `Message`:

```java
if (update.getCallbackQuery().getMessage() instanceof Message msg) {
    msg.getText();
}
```

**Comment by nikmax42** [comment]
@aNNiMON oh, thanks! My bad. When I'm casting `update.getCallbackQuery().getMessage()` as `Message` it works.
