### ISSUE TITLE
How to send an advertisement to one hundred thousand users within 10 minutes?

### ISSUE THREAD

**Issue by nieanlei123** [rubenlagus/TelegramBots#1363]
"I have 100,000 members, and I'm sending out an advertisement to them every 30 minutes using the telegramBot.executeAsync API. However, after sending out 100,000 ads, the process has severely timed out, and it's been several hours now."

**Comment by Chase22** [comment]
Short answer, you can't. 

Longer answer:

Telegram imposes api and sending restrictions to prevent misuse by for example mass spamming users. 

Therefore you need to stretch out those messages over a longer time.

Also just as a second thought: sending that many messages to users is bound to get your account banned

**Comment by nieanlei123** [comment]
> Short answer, you can't.
> 
> Longer answer:
> 
> Telegram imposes api and sending restrictions to prevent misuse by for example mass spamming users.
> 
> Therefore you need to stretch out those messages over a longer time.
> 
> Also just as a second thought: sending that many messages to users is bound to get your account banned

What can I do to solve my problem? I was complained by a customer that the ad placement was too slow, and there is no way to batch send messages. Not only 60,000 users, but even 6,000 users, the message pile-up is very serious.

**Comment by Chase22** [comment]
Short Answer: you can't.

Long Answer:
This is not an issue with this library. The rate limits are enforced on API level. (see here: https://core.telegram.org/bots/faq#my-bot-is-hitting-limits-how-do-i-avoid-this)

Telegram has a separate way of advertising: https://ads.telegram.org/

If you want to mass send messages, you have to throttle your output. There's nothing we can do to fix this. Try contacting the telegram support, use the official channels for advertising or stretch out messages over a longer period.

**Comment by nieanlei123** [comment]
> Short Answer: you can't.
> 
> Long Answer: This is not an issue with this library. The rate limits are enforced on API level. (see here: https://core.telegram.org/bots/faq#my-bot-is-hitting-limits-how-do-i-avoid-this)
> 
> Telegram has a separate way of advertising: https://ads.telegram.org/
> 
> If you want to mass send messages, you have to throttle your output. There's nothing we can do to fix this. Try contacting the telegram support, use the official channels for advertising or stretch out messages over a longer period.

Here's the translation:

"Why is it that the same robot, with over 8000 users, can send messages to over 8000 people within 20 minutes, or even more? The bot's handle is: https://t.me/Ytxzs_bot. What's going on?"

**Comment by Chase22** [comment]
I can't tell you. This in an API issue and not relevant to this library

**Comment by nieanlei123** [comment]
> 我不能告诉你。这是一个 API 问题，与此库无关

"Why do I need it? It's because it's done through an API. That's exactly the functionality I need."  Which library is related to this? I'll go find that library to ask my questions.
