### ISSUE TITLE
Add support Telegram Stars Payments

### ISSUE THREAD

**Issue by megoRU** [rubenlagus/TelegramBots#1370]
Pass an empty string for payments in [Telegram Stars](https://core.telegram.org/bots/api#sendinvoice). 

```java
org.telegram.telegrambots.meta.exceptions.TelegramApiValidationException: ProviderToken parameter can't be empty
```

**Comment by Chase22** [comment]
The feature was announced 20 minutes ago. Calm down. 

You are free to commit a PR

**Comment by megoRU** [comment]
@Chase22 By the way, you can write any in setProviderToken and this will solve the problem

**Comment by rubenlagus** [comment]
Done
