### ISSUE TITLE
RefundStarPayment is not a BotApiObject

### ISSUE THREAD

**Issue by Chase22** [rubenlagus/TelegramBots#1373]
RefundStarPayment is a method in the Api, not an Object. See: https://core.telegram.org/bots/api#refundstarpayment

https://github.com/rubenlagus/TelegramBots/blob/31832c85d2e58e1f034895390e0d0dfeb2bd58d7/telegrambots-meta/src/main/java/org/telegram/telegrambots/meta/api/objects/payments/RefundStarPayment.java#L24

**Comment by aNNiMON** [comment]
@rubenlagus `userId` should be  `Long` https://github.com/rubenlagus/TelegramBots/blob/725c84c527c71ed66e2dd252a853568e1c8b132f/telegrambots-meta/src/main/java/org/telegram/telegrambots/meta/api/methods/payments/RefundStarPayment.java#L41
