### ISSUE TITLE
Telegram Game: telegram.error.BadRequest: Reply_markup_game_empty

### ISSUE THREAD

**Issue by NtemKenyor** [rubenlagus/TelegramBots#1389]
```

async def send_game(update: Update, context: CallbackContext):
    user_id = update.message.chat.id
    game_url = f'https://example.com'
    keyboard = [
        [InlineKeyboardButton("Play Now", url=game_url )],
    ]
    markup = InlineKeyboardMarkup(keyboard)
    await update.message.reply_game(game_short_name, reply_markup=markup)

```

I really do not understand the problem with this code but I want to open my game that is already registered with the BotFather inside telegram not with the inner browser extension.

I get the error: telegram.error.BadRequest: Reply_markup_game_empty and I have tried different things but nothing works.

**Comment by Chase22** [comment]
Are you sure you're at the right repository? This is for the Java library. I don't recognise the language used
