### ISSUE TITLE
inlinekeyboardbutton can not set SwitchInlineQueryChosenChat

### ISSUE THREAD

**Issue by zhanghzong** [rubenlagus/TelegramBots#1391]
```xml
<dependency>
    <groupId>org.telegram</groupId>
    <artifactId>telegrambots</artifactId>
    <version>6.9.7.1</version>
</dependency>
```

![image](https://github.com/rubenlagus/TelegramBots/assets/4384876/d7954b0d-bc3c-4e3a-8093-a9fbb7305400)

**Comment by Chase22** [comment]
Please update to 7.0 and check if the issue persists

**Comment by zhanghzong** [comment]
I have found push versions 7.0 and above in the Maven central warehouse.

![image](https://github.com/rubenlagus/TelegramBots/assets/4384876/bb902b5b-64d6-4d97-8ebc-bf6da783b082)


If I just reference the Maven package. So there's no problem

```
<dependency>
  <groupId>org.telegram</groupId>
  <artifactId>telegrambots-longpolling</artifactId>
  <version>7.2.0</version>
</dependency>

<dependency>
  <groupId>org.telegram</groupId>
  <artifactId>telegrambots-webhook</artifactId>
  <version>7.2.0</version>
</dependency>

<dependency>
  <groupId>org.telegram</groupId>
  <artifactId>telegrambots-client</artifactId>
  <version>7.2.0</version>
</dependency>

<dependency>
  <groupId>org.telegram</groupId>
  <artifactId>telegrambots-extensions</artifactId>
  <version>7.2.0</version>
</dependency>
```

Could you please take a look at the specific version number used?  Thank you.

```
<dependency>
  <groupId>org.telegram</groupId>
  <artifactId>telegrambots</artifactId>
  <version>???</version>
</dependency>
```

**Comment by rubenlagus** [comment]
There was a big refactoring and telegrambots dependency is now gone, see https://rubenlagus.github.io/TelegramBotsDocumentation/how-to-update-7.html
