### ISSUE TITLE
somthings wrong when i sendPhoto

### ISSUE THREAD

**Issue by xia0ne** [rubenlagus/TelegramBots#1424]
```
SendPhoto  sendPhoto = new SendPhoto();
sendPhoto.setChatId(chatId);
sendPhoto.setReplyToMessageId(replyToMessageId);
sendPhoto.setPhoto(new InputFile(url));
sendPhoto.setCaption(caption);
this.execute(sendPhoto);
 ```
 
` caption` & `url` is a String, when it execute, it told me that
 " Cannot invoke "org.telegram.telegrambots.bots.DefaultBotOptions.getHttpContext()" because "this.options" is null"
what can i do! :(((((((((

**Comment by SarinXo** [comment]
Hi, maybe you didn't configure DefaultBotOptions?

**Comment by xia0ne** [comment]
> Hi, maybe you didn't configure DefaultBotOptions?

Thank you!  But other functions of my bot are normal, do you mean that sendphoto has a separate configuration?

**Comment by SarinXo** [comment]
Then that's not the point. I assume that you are using the Spring Framework. Then this error can occur due to incorrect dependency injection. I had a similar situation, when I tried to inject my `TelegramBot` into other classes, and instead of it I injected a class with all null fields.

**Comment by xia0ne** [comment]
> Then that's not the point. I assume that you are using the Spring Framework. Then this error can occur due to incorrect dependency injection. I had a similar situation, when I tried to inject my `TelegramBot` into other classes, and instead of it I injected a class with all null fields.


Thank you very much for your reply. You provided a very clear direction, and I think I have a similar question. I will carefully check it !!!!

**Comment by klisano** [comment]
> > Then that's not the point. I assume that you are using the Spring Framework. Then this error can occur due to incorrect dependency injection. I had a similar situation, when I tried to inject my `TelegramBot` into other classes, and instead of it I injected a class with all null fields.
> 
> Thank you very much for your reply. You provided a very clear direction, and I think I have a similar question. I will carefully check it !!!!

Hello! Could you please tell me how you were able to solve this problem?

**Comment by JavoxirJava** [comment]
> klisano

```
public static void main(String[] args) throws TelegramApiException {
        ConfigurableApplicationContext run = SpringApplication.run(OsiyoXuApplication.class, args);
        TelegramBotsApi telegramBotsApi = new TelegramBotsApi(DefaultBotSession.class);
        BotMethods botMethods = new BotMethods(run.getBean(BotSettings.class), run.getBean(ButtonSettings.class), run.getBean(ScienceService.class), run.getBean(SubjectService.class), run.getBean(ContentService.class));
        telegramBotsApi.registerBot(new BotSettings(botMethods));
    }
```
I suddenly created one bean out of my internal classes without doing getBean.
