### ISSUE TITLE
Chat.getId()  returns long while Integer is enough and all other methods for returning id return Integer.

### ISSUE THREAD

**Issue by aranmohyeddin** [rubenlagus/TelegramBots#143]
please fix this. and make it more standard. well done for you job btw;)

**Comment by eightnoteight** [comment]
from telegram bot api official page https://core.telegram.org/bots/api#chat

> Chat.id => Unique identifier for this chat. This number may be greater than 32 bits and some programming languages may have difficulty/silent defects in interpreting it. But it smaller than 52 bits, so a signed 64 bit integer or double-precision float type are safe for storing this identifier.

**Comment by rubenlagus** [comment]
As @eightnoteight states, it can't be a integer due to Telegram api restrictions.
