### ISSUE TITLE
Cannot construct instance of `org.telegram.telegrambots.meta.api.objects.WriteAccessAllowed`

### ISSUE THREAD

**Issue by ghost** [rubenlagus/TelegramBots#1442]
**Describe the bug**
When my telegram bot activates the myapps feature. I used TelegramLongPollingBot to listen to my messages and encountered the following error:
![1237fcd5fccf0c3b9c05b769c7cb6ef7](https://github.com/user-attachments/assets/28362406-dabc-4de3-b7bb-07de0dbdad1d)

**Additional context**
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.telegram.telegrambots.meta.api.objects.WriteAccessAllowed` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (String)"{"ok":true,"result":[{"update_id":78338603,
"message":{"message_id":280,"from":{"id":671533xxxx,"is_bot":false,"first_name":"y","username":"yxxx","language_code":"zh-hans"},"chat":{"id":671533xxxx,"first_name":"y","username":"yxxx","type":"private"},"date":1728469848,"write_access_allowed":{"web_app_name":"Txxx"}}}]}"; line: 2, column: 263] (through reference chain: org.telegram.telegrambots.meta.api.objects.ApiResponse["result"]->java.util.ArrayList[0]->org.telegram.telegrambots.meta.api.objects.Update["message"]->org.telegram.telegrambots.meta.api.objects.Message["write_access_allowed"])

**Comment by aNNiMON** [comment]
#1312

**Comment by ghost** [comment]
thanks
