### ISSUE TITLE
Why is it that when creating a group, "type" is always "supergroup"? Will update.getMessage().getChat().isGroupChat() always be invalid?

### ISSUE THREAD

**Issue by LenBryan** [rubenlagus/TelegramBots#1449]
I create a group in Telegram. I don't care whether it is a private group or a public group. When I send messages to the group and then listen through webhook, the "type" is always "supergroup".

`    @Override
    public BotApiMethod<?> onWebhookUpdateReceived(Update update) {
        if (update.hasMessage() && update.getMessage().hasText()) {
            String messageText = update.getMessage().getText();
            Long chatId = update.getMessage().getChatId();
            if (update.getMessage().getChat().isGroupChat()) {
                String response = "group message: " + messageText;
                sendMessageToGroup(chatId, response);
            }
        }
        return null;
    }`

I'm using: 
<dependency>
<groupId>org.telegram</groupId>
<artifactId>telegrambots-spring-boot-starter</artifactId>
<version>6.8.0</version>
</dependency>

**Comment by rubenlagus** [comment]
Group type is kind of deprecated by Telegram itself, hence you receive supergroup in general
