### ISSUE TITLE
GetChatMemberCount Error

### ISSUE THREAD

**Issue by Mouamle** [rubenlagus/TelegramBots#147]
in GetChatMemberCount
![image](https://cloud.githubusercontent.com/assets/10764639/18814133/9a5a4aaa-8319-11e6-89f7-259c57f35a4a.png)

**Comment by rubenlagus** [comment]
That's already solved, check https://github.com/rubenlagus/TelegramBots/blob/master/src/main/java/org/telegram/telegrambots/api/methods/groupadministration/GetChatMemberCount.java#L19

You many need to update to latest version
