### ISSUE TITLE
Jar TelegramBots with dependencies

### ISSUE THREAD

**Issue by DenisWpk** [rubenlagus/TelegramBots#153]
Hi! 
Link is broken. Please add jar. 
https://github.com/rubenlagus/TelegramBots/releases/tag/v2.4.0

**Comment by rubenlagus** [comment]
I'm sure you are able to find version 2.4.0 from the list of releases: https://github.com/rubenlagus/TelegramBots/releases ;)

**Comment by DenisWpk** [comment]
Thank you )
