### ISSUE TITLE
Question on retrieving files.

### ISSUE THREAD

**Issue by UselessMnemonic** [rubenlagus/TelegramBots#16]
I want to be able to save received photos to the disk where my Bot is running, but I honestly don't where to start on getting the file path to download from the server.

**Comment by Clevero** [comment]
I hope I didn't misunderstand the code from @rubenlagus , but I just created a pull request #18 for that cause I couldn't find anything from where I can get the file path. 

In my environment this is working. Is it possible that you can test my code in the pr?

**Comment by UselessMnemonic** [comment]
I'll get on that right now.

**Comment by UselessMnemonic** [comment]
Sorry for the *super* late reply.
This works very well. Thank you.
