### ISSUE TITLE
No implementation for org.telegram.telegrambots.generics.BotSession was bound

### ISSUE THREAD

**Issue by dpisarenko** [rubenlagus/TelegramBots#161]
How can I fix the following problem?

```
Exception in thread "main" com.google.inject.ConfigurationException: Guice configuration errors:

1) No implementation for org.telegram.telegrambots.generics.BotSession was bound.
  while locating org.telegram.telegrambots.generics.BotSession

1 error
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1045)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1004)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
	at org.telegram.telegrambots.ApiContext.getInstance(ApiContext.java:25)
	at org.telegram.telegrambots.TelegramBotsApi.registerBot(TelegramBotsApi.java:83)
```

**Comment by rubenlagus** [comment]
Please follow the steps as explained: https://github.com/rubenlagus/TelegramBots/wiki/How-To-Update#to-version-242

**Comment by dpisarenko** [comment]
Thanks!

**Comment by segator** [comment]
same problem, How to update doesn't work in my case
I'm using spring boot and Maybe is causing conflicts.

`@SpringBootApplication
public class AutoDownloaderApplication implements CommandLineRunner {

    @Autowired
    private MovieGrabber movieGrabber;

    @Override
    public void run(String... args) throws Exception {
        ApiContextInitializer.init();
        TelegramBotsApi botsApi = new TelegramBotsApi();
        botsApi.registerBot(movieGrabber);

    }

    public static void main(String[] args) throws Exception {
        SpringApplication.run(AutoDownloaderApplication.class, args);
    }
}
`

**Comment by drunckoder** [comment]
Try moving `ApiContextInitializer.init();` to a static {} block. Or put it somewhere to run earlier.

**Comment by segator** [comment]
Thank you, it works :)

**Comment by sslavian812** [comment]
@drunckoder can you please explain, why `ApiContextInitializer.init();` should be moved to static block?
I used the following code in PostConstruct-annotated method of my bot-Bean class in SpringBoot.
```
ApiContextInitializer.init();
TelegramBotsApi botsApi = new TelegramBotsApi();
botsApi.registerBot(this);
```
I got the same error and your advice did help me too. Why?)

**Comment by v1as** [comment]
@sslavian812 This is because it is necessary to init ApiContextInitializer before constructor of your bot. In your case you calling it in PostConstruct block, which executing after constructor executing.

**Comment by charmstead** [comment]
I solved this by removing the annotation @Component or @Service from myBots class

**Comment by lawrence615** [comment]
@charmstead I also solved the same problem by removing the annotations; but what if you would want to autowire something like a repository in myBots class. How would you go about it?

**Comment by the-elf** [comment]
@charmstead I solved this problem by putting ApiContextInitializer.init() before SpringApplication.run

**Comment by IgorVolg1n** [comment]
@charmstead any idea, why does it work?
and are there some hidden pitfalls in this solution?
thanks in advance

**Comment by pengchenxue** [comment]
@SpringBootApplication
public class AutoDownloaderApplication implements CommandLineRunner {

    @Autowired
    private MovieGrabber movieGrabber;

    @Override
    public void run(String... args) throws Exception {
        TelegramBotsApi botsApi = new TelegramBotsApi();
        botsApi.registerBot(movieGrabber);

    }

    public static void main(String[] args) throws Exception {
        ApiContextInitializer.init();
        SpringApplication.run(AutoDownloaderApplication.class, args);
    }
}

in this way,i slove the problem

**Comment by pengchenxue** [comment]
@Log4j2
@Service
public class TelegramBotService extends TelegramLongPollingBot  {
    @Autowired
    private TelegrambotConfig telegrambotConfig;
    @Autowired
    private TelegramInvoker telegramInvoker;

    @PostConstruct
    public void registerBot(){
        TelegramBotsApi botsApi = new TelegramBotsApi();
        try {
            botsApi.registerBot(this);
            log.info("==================================TelegramBotService.afterPropertiesSet:registerBot finish");
        } catch (TelegramApiException e) {
            e.printStackTrace();
        }
    }


    @Override
    public void onUpdateReceived(Update update) {
        
        if (update.hasMessage() && update.getMessage().hasText()) {
            telegramInvoker.action(update);
        }
    }

    @Override
    public String getBotUsername() {
        return telegrambotConfig.getName();
    }

    @Override
    public String getBotToken() {
        return telegrambotConfig.getToken();
    }

}



@SpringCloudApplication
public class Application {

    public static void main(String[] args) {
        ApiContextInitializer.init();
        SpringApplication.run(Application.class, args);
    }

   
}


In this way ,I find the sloution

**Comment by alexIslander** [comment]
In Springboot Telegram starter version 4.1, you don't need to register your bot! It is done automatically!

**Comment by mhkarimi** [comment]
I had a same problem, just add this to your main springboot class :
```

@PostConstruct
    public void init(){
        ApiContextInitializer.init();
    }
```

**Comment by AppLoidx** [comment]
Suddenly someone will help. I had such an error when there was such a piece of code:
```java
DefaultBotOptions botOptions = ApiContext.getInstance(DefaultBotOptions.class);
```
Maybe you, too, have lost something like this or something similar.

What is the coolest thing is that I called it up to the bot constructor 😫

**Comment by heroys6** [comment]
As @sslavian812 mentioned, the problem is in that Bot(`TelegramLongPollingBot` in my case) constructor was called before the `ApiContextInitializer.init();`.
Bot constructor expects that context is already initialized. 
In my case constructor was called because of Spring DI.
So, if you want to use `@Service`, `@Component`, etc. annotations inside the bot class, put 
```java
static {
    ApiContextInitializer.init();
}
```
into bot class to initialize context API context at static initialization stage.
Or like in @pengchenxue example, run this code inside `main()` before `SpringApplication.run(Application.class, args);`.

**Comment by JimyDeveloper** [comment]
> Try moving `ApiContextInitializer.init();` to a static {} block. Or put it somewhere to run earlier.

thak you. it worked

**Comment by torvicv** [comment]
I solved removing Autowired of TelegramBot class.

`/*@Autowired
    private TelegramBot telegramBot;*/

TelegramBotsApi botsApi = new TelegramBotsApi();
            botsApi.registerBot(new TelegramBot());`
