### ISSUE TITLE
answer to press inlinekeyboardbutton

### ISSUE THREAD

**Issue by jordhi** [rubenlagus/TelegramBots#170]
It's not possible generate a answer after press a inlinekeyboardbutton, is it?

**Comment by Clevero** [comment]
Sure it's possible to react after the user pressed an InlineKeybordButton.

You just have to listen for that with an example of mine is available [here](https://github.com/rubenlagus/TelegramBotsExample/pull/30/commits/c0ba49576342abbfb587a7543296eee8b558a13d#diff-62f4ad061c25527fb624adbc8d0b4066R100) as a pull request for the example repo.

Disclaimer: This given example was written with the the old version of this API, don't know if this is runnung out of the box.

**Comment by jordhi** [comment]
Thanks, it's running!
