### ISSUE TITLE
problem with understanding telegram bot creation

### ISSUE THREAD

**Issue by mbarzegar93** [rubenlagus/TelegramBots#172]
hi
i did not understand how to create a bot
i means i should use this library to create a software and then run it on server and manage the bot with software that i wrote?
software should have button and textfield and ... for controlling bot? like write a message in textfield and then press send button and it will send the message to users?
please help me
i'm confused

**Comment by Clevero** [comment]
You write some code and run it. And then you can start a new conversation with your bot.
To "manage" your bot, just change the code behind your bot. 

So for example, send a message to a user:
```java
SendMessage message = new SendMessage();
message.setChatId(update.getMessage().getChatId());
message.setText("Some text you want to send him :)");
sendMessage(message);
```


Take a look at our wiki, there are instructions how to simply write your first telegram bot.


Also I advise you to download the [TelegramBotsExample](https://github.com/rubenlagus/TelegramBotsExample) repo, run those example bots and browse through their code. 


If you have further questions, feel free to ask :)

**Comment by Clevero** [comment]
Are your understanding problems solved? :)

**Comment by mbarzegar93** [comment]
now i understand more but still not fully understand
i think i need more coding and practice to fully understand
if i have more question i will ask
thanks for help

**Comment by rubenlagus** [comment]
Looks answered, closing
