### ISSUE TITLE
BotLogger

### ISSUE THREAD

**Issue by WinSide** [rubenlagus/TelegramBots#173]
How to set custom formatter to BotLogger?

**Comment by rubenlagus** [comment]
Just extending from java.util.logging.Handler and then registering in BotLogger.

**Comment by ronindev** [comment]
Sad but true, it use JUL instead of slf4j. I use bridge http://stackoverflow.com/questions/9117030/jul-to-slf4j-bridge

**Comment by rubenlagus** [comment]
There are a few logging frameworks around there so I decided to use default one. At least for now there won't be a change for that.
