### ISSUE TITLE
How can I replace inlineKeyBoardButton for another?

### ISSUE THREAD

**Issue by jordhi** [rubenlagus/TelegramBots#174]
When I press a **inlineKeyboardButton** I need a new answer like a new inlineKeyboardButtons but I want to remove first buttons and replace for the new.

**Comment by Clevero** [comment]
In this case, you just have to edit the message with the old InlineKeyboardButton's and set the new buttons you want to show the user. You cannot "just" replace a specific button with another one, you have to set the whole modified `InlineKeyboardMarkup`

Example: available here as a [pull request](https://github.com/rubenlagus/TelegramBotsExample/pull/30) in the example repo.

If you have further questions, feel free to ask :)

**Comment by jordhi** [comment]
Great!
