### ISSUE TITLE
RaeBot Inline 

### ISSUE THREAD

**Issue by JJTheo** [rubenlagus/TelegramBots#175]
Hi,
I'm trying to create my own InlineQueryBot and I'm looking at your
RaeBot to understand how inline queries works.
I can't find on your RaeHandlers what does the answerInlineQuery() refer to (lines 76, 78) :

[https://github.com/rubenlagus/TelegramBotsExample/blob/e7ada17749ac8e5ba195e10f3d0e57b077bf1e3d/src/main/java/org/telegram/updateshandlers/RaeHandlers.java](url)

Am I that bad at Java or is there a problem ?

Thx

**Comment by addo37** [comment]
Erm, answerInlineQuery is the method itself inherited from the TelegramLongPollingBot/TelegramWebhookBot. A quick look at its signature and you'll find that most methods are implemented through the parent class (DefaultAbsSender).

The library is quite clean. If you have an IDE, you'll be able to easily navigate.

**Comment by JJTheo** [comment]
Yeah getting it on an IDE could be great -_- didn't think about
inheritance... Thank you ;)
