### ISSUE TITLE
webhook

### ISSUE THREAD

**Issue by massimiliano76** [rubenlagus/TelegramBots#178]
Hi,

I trued to create my own bot using you example as template, when I make the project I receive this error:

--- exec-maven-plugin:1.2.1:exec (default-cli) @ botapi ---
Dec 18, 2016 1:12:57 PM org.telegram.telegrambots.logging.BotLogger severe
SEVERE: MAIN
org.telegram.telegrambots.exceptions.TelegramApiRequestException: Error removing old webhook: [404] Not Found
	at org.telegram.telegrambots.bots.TelegramLongPollingBot.clearWebhook(TelegramLongPollingBot.java:50)
	at org.telegram.telegrambots.TelegramBotsApi.registerBot(TelegramBotsApi.java:82)
	at org.telegram.Main.main(Main.java:45)

Dec 18, 2016 1:12:57 PM org.telegram.telegrambots.logging.BotLogger severe
SEVERE: MAIN
org.telegram.telegrambots.exceptions.TelegramApiRequestException: Error removing old webhook: [404] Not Found
	at org.telegram.telegrambots.bots.TelegramLongPollingBot.clearWebhook(TelegramLongPollingBot.java:50)
	at org.telegram.telegrambots.TelegramBotsApi.registerBot(TelegramBotsApi.java:82)
	at org.telegram.Main.main(Main.java:45)

How can I do?
Thank you very much.
P.s. I'm using Netbeans 8.2 Maven Project

**Comment by TLAngus** [comment]
Check if in your TelegramLongPollingCommandBot implementation the methods getBotUsername and getBotToken are configured correctly.

**Comment by rubenlagus** [comment]
Since there is no answer, I assume it is solved.

**Comment by dazzbourgh** [comment]
I face the same issue. getBotUsername and getBotToken are configured correctly

**Comment by Rebelllious** [comment]
I have run into the same error when I copied the example from your repository and added my own bot name and API key. Bot name and API key are indicated properly. How can this be fixed?

**Comment by nicholas-nimak** [comment]
I got same bug when wrote username instead of token and vice versa.

**Comment by carmuno** [comment]
you must specifify the token and user in the same class bot
