### ISSUE TITLE
Retrieve file_id of new Photo sent with sendPhoto(SendPhoto msg)

### ISSUE THREAD

**Issue by orasonoalladucati** [rubenlagus/TelegramBots#179]
Hi,

i'm using this library for building my bot and I've a problem when I upload a new photo on Telegram server. For first time i send a photo like this:
sendPhotoMessage.setNewPhoto (new File (pathPhoto));

and after i do:

Message msg = sendPhoto (sendPhotoMessage);

At this point, how can i retrieve the file id from the Message obtained above'

Thanks for your help.

**Comment by liketechnik** [comment]
I'm not sure, but sendPhotoMessage.getPhoto() should return a String that is file_id (if I understood the documentation of SendPhoto class right).

**Comment by rubenlagus** [comment]
`msg.getPhoto()` should return the list of [PhotoSize](https://github.com/rubenlagus/TelegramBots/blob/master/telegrambots-meta/src/main/java/org/telegram/telegrambots/api/objects/PhotoSize.java)  generated and there you should find the `file_id`

**Comment by rubenlagus** [comment]
Closing, since there is no answer, assuming it is solved
