### ISSUE TITLE
Location and SendLocation

### ISSUE THREAD

**Issue by The28AWG** [rubenlagus/TelegramBots#184]
Hello!
Need equal type latitude and longitude in class Location and SendLocation
https://github.com/rubenlagus/TelegramBots/blob/master/telegrambots-meta/src/main/java/org/telegram/telegrambots/api/methods/send/SendLocation.java#L35
https://github.com/rubenlagus/TelegramBots/blob/master/telegrambots-meta/src/main/java/org/telegram/telegrambots/api/objects/Location.java#L19

Optional need constructor new SendLocation(Location), or need method setLocation(Location).
Hmmm... its not optimal idea.

**Comment by rubenlagus** [comment]
If Location and SendLocation are not the same, not the best option to add them...

**Comment by The28AWG** [comment]
Need one type! It is important!
Double not equals Float!

**Comment by rubenlagus** [comment]
I'll change the Location ones to Float to match the correct type in docs for next release.
