### ISSUE TITLE
ApiConstants.class Error

### ISSUE THREAD

**Issue by vladimir123** [rubenlagus/TelegramBots#193]
Hi!
I just wanted to create some application for my telegramm bot, and when I build example code from here => https://github.com/rubenlagus/TelegramBots/wiki/Getting-Started
I am getting an Error:
`Error:PARSE ERROR:
Error:unsupported class file version 52.0
Error:...while parsing org/telegram/telegrambots/ApiConstants.class
Error:1 error; aborting
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException`

So I  want to ask, is this error erro in my code, or it is something else?

P.S Android Studio 2.2.3  + use Gradle repo

**Comment by rubenlagus** [comment]
I'm not sure you will be able to use this library with Android. It requires Java8

**Comment by rubenlagus** [comment]
@vladimir123 Were you able to use it in Android? I'm not sure it will be possible but would like to get some feedback if you could manage it.
