### ISSUE TITLE
connect to database

### ISSUE THREAD

**Issue by mbarzegar93** [rubenlagus/TelegramBots#194]
hi
i want to connect my robot to my site database so people can search in robot and find content of my site;
but how i should connect my robot to my site database?
my site use wordpress cms;
please help
thanks;

**Comment by MonsterDeveloper** [comment]
Wordpress uses MySQL so you need to know host, port, username, password and database name and then connect to MySQL server with this data with the help from [Java MySQL Driver](https://dev.mysql.com/downloads/connector/j/).

**Comment by rubenlagus** [comment]
For MySQL, you may find useful the samples project: https://github.com/rubenlagus/TelegramBotsExample

**Comment by mbarzegar93** [comment]
thanks for the help
