### ISSUE TITLE
Problem sending large audiofile

### ISSUE THREAD

**Issue by cfreemoser** [rubenlagus/TelegramBots#195]
Hi,

first of all thank you for this great lib. I am facing some problem, when I try to send a large audiofile - arround 100MB. First I thought it may be a problem with the timeout, so I tried to impl. my own AbsSender but even with increasing the timeout I am still facing this problem :(

`Feb 25, 2017 2:08:59 PM org.apache.http.impl.execchain.RetryExec execute`
`INFORMATION: I/O exception (java.net.SocketException) caught when processing request to {s}->https://api.telegram.org:443: Connection reset`

Do you know if there are some limitations by the api? or do you have any idea how I can work around this?

Thank you

Cem

**Comment by rubenlagus** [comment]
Limitations are enforced by Telegram API, please check official docs: https://core.telegram.org/bots/api#sending-files

**Comment by MonsterDeveloper** [comment]
Photo - max. 5MB and other files 20MB max.

**Comment by cfreemoser** [comment]
thank you :) you can close this issue
