### ISSUE TITLE
If the Inet connection is lost, the bot gets frozen

### ISSUE THREAD

**Issue by turlygazhy** [rubenlagus/TelegramBots#202]
in my case internet connection was lost before method sendMessage().
this method begins and bot got frozen, without any exception, the most sad is when connection come back bot did not continue work.

steps: 
1) register bot
2) lose internet connection
3) execute sendMessage method

**Comment by MonsterDeveloper** [comment]
Do you surround it with try catch?

**Comment by turlygazhy** [comment]
yes, but there is no exception

**Comment by rubenlagus** [comment]
I have been trying your steps and this is what I get. It always throws an exception. In any case, I noticed that default request config options are not been correctly used in the `DefaultAbsSender.java` so I'll fix that in the next version.

<img width="919" alt="screen shot 2017-03-20 at 01 27 10" src="https://cloud.githubusercontent.com/assets/2874352/24086274/db966724-0d0c-11e7-83dc-9eda2edc086c.png">

**Comment by rubenlagus** [comment]
@turlygazhy I have make few improvements regarding this topic in last versions, can you check it and confirm it is fixed?

**Comment by rubenlagus** [comment]
Inactive, closing
