### ISSUE TITLE
add TelegramBotsApi extends support

### ISSUE THREAD

**Issue by vahpetr** [rubenlagus/TelegramBots#203]
Hello

Please change access modificators in TelegramBotsApi to protected

private static final String webhookUrlFormat = "{0}callback/";
private boolean useWebhook; ///< True to enable webhook usage
private Webhook webhook; ///< Webhook instance
private String extrenalUrl; ///< External url of the bots
private String pathToCertificate; ///< Path to public key certificate

**Comment by rubenlagus** [comment]
The only field that is not possible to modify it is the "webhookUrlFormat" that is just a suffix to the url to ensure it can be identified by the api.

All other fields can be overwrite in constructors.
