### ISSUE TITLE
Typo in setOneTimeKeyboard

### ISSUE THREAD

**Issue by gerd2002** [rubenlagus/TelegramBots#206]
instead it is setOneTimeKeyboad

**Comment by MonsterDeveloper** [comment]
You can create a pull request. I think @rubenlagus will accept it. Is that `telegrambots-meta` or just `telegrambots` package?

**Comment by rubenlagus** [comment]
Will be fixed in next version

**Comment by rubenlagus** [comment]
Was already fixed, wasn't it?
