### ISSUE TITLE
12 Mega Byteeeeeeeeeee :////

### ISSUE THREAD

**Issue by smaznet** [rubenlagus/TelegramBots#208]
hi to programmer of this good library bot i have a problem with it and my problem is

 BIG SIZE OF .jar output

why this out put is very big?

**Comment by MonsterDeveloper** [comment]
Maybe there are lot's of dependencies? Try to make `.jar` with the help from my [book](https://monsterdeveloper.gitbooks.io/writing-telegram-bots-on-java/content/lesson-5.-deploy-your-bot.html).

**Comment by smaznet** [comment]
this not helped me... 

i have a server and i can build jar


witch link should i download your library.? 

i downloaded this:
Download the jar(including all dependencies) from here


what is difference?

**Comment by MonsterDeveloper** [comment]
I linked my book. Read it. 
![image](https://cloud.githubusercontent.com/assets/16190582/24156656/2a13895c-0e68-11e7-84b4-58c02f468575.png)

**Comment by MonsterDeveloper** [comment]
You know, my JAR is big too. 
![image](https://cloud.githubusercontent.com/assets/16190582/24156718/61d4dd5a-0e68-11e7-9b4e-ba1588682354.png)

**Comment by smaznet** [comment]
yes i say it too😐

my android apps size is only 3 mb
but i dont know why your library is big 😕

**Comment by MonsterDeveloper** [comment]
Why do you care about jar size? It's server-side so user can't see difference between 3mb and 13mb

**Comment by smaznet** [comment]
yes it is true, bot uploading to server in my network took 15 mins

**Comment by smaznet** [comment]
witch dependencies  increased this library size? 

you can use alternatives


i want make your library better😆

**Comment by MonsterDeveloper** [comment]
My library? What do you mean? And if it takes 15 mins to upload 13 mb, I recommend you to change your network provider before coding. 😆

**Comment by smaznet** [comment]
😂 😂 😂 😂 

yes your library (https://github.com/rubenlagus/TelegramBots)

**Comment by MonsterDeveloper** [comment]
If you don't know, this is not my library. This library is developer by @rubenlagus. I am just contributor.

**Comment by smaznet** [comment]
@MonsterDeveloper :|||||||||||

**Comment by smaznet** [comment]
@rubenlagus hi , are you hear me????

**Comment by rubenlagus** [comment]
So, the problem is that the Jar is 13MB big? Sorry about that. You can see the dependencies that it has at https://github.com/rubenlagus/TelegramBots/blob/2.4.4.5/telegrambots/pom.xml.

**Comment by smaznet** [comment]
@rubenlagus are all of libraries is required?

**Comment by smaznet** [comment]
i want fork your library and remove unnecessary libraries

**Comment by rubenlagus** [comment]
They are required for my implementation.

You can use TelegramBots-meta only (https://github.com/rubenlagus/TelegramBots/tree/master/telegrambots-meta) and then implement the concrete version of `BotSession` and `Webhook` on your own. TelegramBots-Meta jar is only 4.6MB (https://github.com/rubenlagus/TelegramBots/releases).

**Comment by smaznet** [comment]
please follow my account, a new fork comming soon.... 😉😉😉
