### ISSUE TITLE
How to use SendChatAction?

### ISSUE THREAD

**Issue by brunocassio** [rubenlagus/TelegramBots#210]
Hello,

I've been creating a bot when the user types and submit the data, the bot takes a while to consume the service.
So, I would like to show the "typing..." message when the bot is doing something.
I know that is something like this:

`SendChatAction sendChatAction = new SendChatAction();`
`sendChatAction.setChatId(message.getChatId());`
`sendChatAction.setAction(ActionType.TYPING);`

But I don't know how/where to use this SendChatAction.
Does anybody know how to use SendChatAction class?

**Comment by Clevero** [comment]
If I understood you correctly, that you don't know how to use this SendChatAction object:

From the principle, it's the same as sending a normal message
You can use the method "sendChatAction(SendChatAction sendChatAction)" from [AbsSender](https://github.com/rubenlagus/TelegramBots/blob/b3828accbe0a6941491ede4d0bac1d46d0750c60/telegrambots-meta/src/main/java/org/telegram/telegrambots/bots/AbsSender.java#L78)

The code could look like this
```java
SendChatAction sendChatAction = new SendChatAction();
sendChatAction.setChatId(message.getChatId());
sendChatAction.setAction(ActionType.TYPING);
sendChatAction(sendChatAction);
```

**Comment by brunocassio** [comment]
Hello @Clevero , 

Thank you for your answer!!! It worked now. 
I didn't know that I had to use the sendChatAction(sendChatAction) method.
