### ISSUE TITLE
I'm having problems with webhook

### ISSUE THREAD

**Issue by onixred** [rubenlagus/TelegramBots#212]
I do not understand why t me need a certificateStore
```
public static final String pathToCertificateStore = "./YOURSTORE.jks"; //self-signed and non-self-signed.
public static final String certificateStorePassword = "yourpass"; //password for your certificate-store
```
and 
`public static final String pathToCertificatePublicKey = "./YOURPEM.pem"; //only for self-signed webhooks`
This is the path to the file to the public certificate Or my private key?

**Comment by Tar4s** [comment]
Maybe this is answer?

![Magic!!!](http://i.imgur.com/jMHIYhb.png)

**Comment by rubenlagus** [comment]
Public key is used to be sent to Telegram servers in case you are using a self-signed one. 

Store and password are user to build up the HTTPS server where request will be received.

**Comment by onixred** [comment]
ok. I use these lines to create a certificate and store
`
openssl req -newkey rsa:2048 -sha256 -nodes -keyout private.key -x509 -days 365 -out public_cert.pem -subj "/C=RU/ST=State/L=Location/O=Organization/CN=37.194.56.137"
openssl pkcs12 -export -in public_cert.pem -inkey private.key -certfile public_cert.pem -out keystore.p12
keytool -importkeystore -srckeystore keystore.p12 -srcstoretype pkcs12 -sigalg SHA1withRSA -destkeystore keystore.jks -deststoretype JKS
rm keystore.p12
rm private.key
`
`
EXTERNALWEBHOOKURL = "https://37.194.56.137:" + 8443;
INTERNALWEBHOOKURL = "https://localhost:" + 8443;
`

37.194.56.137 -it is my domen
Webhook does not work.

**Comment by Tar4s** [comment]
Set your INTERNALWEBHOOK = EXTERNAL

**Comment by onixred** [comment]
Good news! I want to say thank you! I've specified an internal INTERNALWEBHOOKURL  192.168.0.3 
it is ip my computer.

**Comment by Clevero** [comment]
@onixred so, is your problem solved? can this issue be closed?

**Comment by Tar4s** [comment]
@onixred not at all

**Comment by onixred** [comment]
yes my problem solved!
