### ISSUE TITLE
The best way to generate a broadcast

### ISSUE THREAD

**Issue by Tar4s** [rubenlagus/TelegramBots#215]
Whether there is an optimal code for sending broadcast messages that does not slow down the main work of the bot and without freezes would send out messages to users. Now I'm using:

new Thread(() -> mailingFunc()).start(); 

In mailingFunc I use simple sendMessage method.  Nevertheless, with such mailing the main work of the bot is slowed down, and the broadcast periodically stops for a few seconds

**Comment by rubenlagus** [comment]
You should be hitting limits: https://core.telegram.org/bots/faq#broadcasting-to-users

**Comment by Tar4s** [comment]
Yes, thnx
