### ISSUE TITLE
Stateful bot

### ISSUE THREAD

**Issue by Ozymandy** [rubenlagus/TelegramBots#216]
I want to access secured resource server. Authentication on this resource server is provided by /login command. But how to store state? In my case it's cookie from HttpClient. Maybe anyone can suggest me any solutions on this case.

**Comment by MonsterDeveloper** [comment]
How is this connected with telegram bots?

**Comment by rubenlagus** [comment]
I don't see the relation with the library. @Ozymandy, reopen it with more information if it is somehow related.
