### ISSUE TITLE
Is there expiration time to file_ids ?

### ISSUE THREAD

**Issue by shadkani** [rubenlagus/TelegramBots#217]
before every thing , I should say thank you for your Great Api and fantastic support;

I saved a file_id for sending a photo; everything is OK  and photo successfully send , But after a Weak or More i receive this Error 
"Error sending photo: [400] Bad Request: wrong file identifier/HTTP URL specified" 
i should send a photo to each client , for each request .
thank you .
and sorry for my weak English skill.

**Comment by shadkani** [comment]
I find the solution I use a URL for send the photo .  but please response the question . 
Is there expiration time to file Ids ? 
if yes how much the time?

**Comment by Clevero** [comment]
The FAQ of the Bots API states: https://core.telegram.org/bots/faq#can-i-count-on-file-ids-to-be-persistent

**Comment by rubenlagus** [comment]
@Clevero already pointed the answer, closing.
