### ISSUE TITLE
Sending keyboard with game

### ISSUE THREAD

**Issue by huksley** [rubenlagus/TelegramBots#219]
I am trying to send custom button to start game.
However if I add keyboard API responds with [400] Bad Request: REPLY_MARKUP_GAME_EMPTY

```javascript
SendGame g = new SendGame();
g.setChatId(chatId);
g.setGameShortName(applicationId);
InlineKeyboardButton b = new InlineKeyboardButton();
b.setCallbackData(applicationId);
b.setCallbackGame(new CallbackGame());
b.setText(buttonTitle);
InlineKeyboardMarkup mm = new InlineKeyboardMarkup();
List<List<InlineKeyboardButton>> keyboard = new ArrayList<>();
List<InlineKeyboardButton> row = new ArrayList<>();
keyboard.add(row);
row.add(b);
mm.setKeyboard(keyboard);
g.setReplyMarkup(mm);
```

As per [specification](https://core.telegram.org/bots/api#games):

> You can manually add multiple buttons to your game message. Please note that the first button in the first row must always launch the game, using the field callback_game in InlineKeyboardButton. You can add extra buttons according to taste: e.g., for a description of the rules, or to open the game's official community.

Please help, is it problem with code, library or spec?

**Comment by huksley** [comment]
I`ve found problem:
```javascript
b.setCallbackData(applicationId);
```
This line is the culprit. Removing it everything works ok!

**Comment by saticModif** [comment]
Key message, REPLY_ MARKUP_ GAME_ EMPTY, I used two methods, setUrl and setCallbackData, but I also encountered this problem. After trying many times, I found that only setText was retained and setCallbackGame was not the problem
