### ISSUE TITLE
throw "TelegramApiRequestException"

### ISSUE THREAD

**Issue by MyNameIsMy** [rubenlagus/TelegramBots#222]
Can someone describe to me what happening when this error is thrown and how it solve, thanks: 
"date and time" org.telegram.telegrambots.logging.BotLogger severe
SEVERE: BOTSESSION
org.telegram.telegrambots.exceptions.TelegramApiRequestException: Error getting updates: [409] Conflict: terminated by other long poll or webhook
	at org.telegram.telegrambots.api.methods.updates.GetUpdates.deserializeResponse(GetUpdates.java:119)
	at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$ReaderThread.run(DefaultBotSession.java:208)

**Comment by Clevero** [comment]
Did you tried to search for a solution?
The error is described and solved in the wiki under ```Errors Handling```...

**Comment by MyNameIsMy** [comment]
Yes I tried but not there and I have understood now, thanks.

**Comment by Clevero** [comment]
Great
Can this issue now be closed?
