### ISSUE TITLE
how to create buttons

### ISSUE THREAD

**Issue by Pie133** [rubenlagus/TelegramBots#223]
hi
i know my question is stupid but i'm new so sorry about that
can i know how can i send a keyboard button with this api ?

**Comment by Clevero** [comment]
Did you tried to find/search a solution? Maybe in the wiki?

KeyboardButtons are in the wiki explained
InlineKeyboardButtons are explained in the referenced book by MonsterDeveloper

**Comment by Pie133** [comment]
but i'm asking for something like this 
https://core.telegram.org/file/811140184/1/5YJxx-rostA/ad3f74094485fb97bd
can u please help me how can i  do this ?

**Comment by Clevero** [comment]
Those are normal KeyboardButtons

**Comment by Pie133** [comment]
so how can i create them ?
can u give me a link that explain normal keyboardbuttons? :(

**Comment by Clevero** [comment]
As I stated above, you can find explanation about KeyboardButtons in the wiki

FAQ -> [How to use custom keyboards?](https://github.com/rubenlagus/TelegramBots/wiki/FAQ#how_to_use_custom_keyboards)

**Comment by Clevero** [comment]
@Pie133 is your problem solved? can this issue be closed?
