### ISSUE TITLE
inline keyboards

### ISSUE THREAD

**Issue by Pie133** [rubenlagus/TelegramBots#224]
Hi! sorry for asking too much questions 
But i have a question about inline keyboards 
` SendMessage message = new SendMessage() // Create a message object object
                        .setChatId(chat_id)
                        .setText("You send /start");
                InlineKeyboardMarkup markupInline = new InlineKeyboardMarkup();
                List<List<InlineKeyboardButton>> rowsInline = new ArrayList<>();
                List<InlineKeyboardButton> rowInline = new ArrayList<>();
                rowInline.add(new InlineKeyboardButton().setText("Update message text").setCallbackData("update_msg_text"));
                // Set the keyboard to the markup
                rowsInline.add(rowInline);
                // Add it to the message
                markupInline.setKeyboard(rowsInline);
                message.setReplyMarkup(markupInline);
                try {
                    sendMessage(message); // Sending our message object to user
                } catch (TelegramApiException e) {
                    e.printStackTrace();
                }`
with this code i can send glass buttons on only 1 row 
how can i send it like this?
![image](https://cloud.githubusercontent.com/assets/28263027/25654399/1c793e44-3006-11e7-9b77-a884adfd9c5d.png)

**Comment by Clevero** [comment]
Understand ```List<List<InlineKeyboardButton>>``` as a structure like a table.

Every entry of ```rowsInline``` represents a column/row of the "table". And every entry of e.g. ```rowInline``` represents a cell in a column. Just like a table.

You need to add a second  ```List<InlineKeyboardButton>``` to ```rowsInline```. 
For example
```java
List<List<InlineKeyboardButton>> rowsInline = new ArrayList<>();
List<InlineKeyboardButton> firstRowInline = new ArrayList<>();
List<InlineKeyboardButton> secondRowInline = new ArrayList<>();

//add your buttons to both rows
firstRowInline.add(new InlineKeyboardButton().setText("ok"));
secondRowInline.add(new InlineKeyboardButton().setText("bye"));


rowsInline.add(firstRowInline);
rowsInline.add(secondRowInline);
```

Disclaimer: I don't have tested the code above. See it as a pseudo-code

**Comment by Clevero** [comment]
@Pie133 Is your problem solved? 
can this issue now be closed?

**Comment by Pie133** [comment]
Yes it is 
Thank you
I though its spam if i say something like "thank u" or "got it"
