### ISSUE TITLE
Support Java 7 or maybe Java 6

### ISSUE THREAD

**Issue by mrk1989** [rubenlagus/TelegramBots#227]
Hi.
I notice that your library is defined in Java 8 on pom.xml (https://github.com/rubenlagus/TelegramBots/blob/master/telegrambots/pom.xml) .

I kindly ask you to adapt it to Java 7 if Is possible.
I download the project TelegramBots and I changed the pom for adapt Java 7.
I notice that I get error for lambda's function and also for Integer::compareTo or BiConsumer.

I can spent my time if is helpful for support Java 7. I dont' know if I can....

**Comment by rubenlagus** [comment]
Neither Java6 or Java7 are supported by Oracle any more:

![image](https://cloud.githubusercontent.com/assets/2874352/25800138/52db6d50-33e8-11e7-9275-8671d17c815c.png)


i don't think that we should downgrade libraries to an obsolete version, much better to update obsolete software ;)

**Comment by mrk1989** [comment]
I agree with you and the support by Oracle.
Also if we did a downgrade libraries, you library can support major platform.
I can't ask my client for upgrade Java installation.
The same reason will be for a system operating.
I still use Windows XP or 7 and I know that is not supported (update software "security" ) from Microsoft.

I can say another thing, Seems that your project is much used from other.

**Comment by rubenlagus** [comment]
@mrk1989 The problem is that I'd need to make changes in the code to support java6 or java7. And also be really careful when developing new stuff so I don't include non-supported features.
