### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/http/HttpEntity

### ISSUE THREAD

**Issue by agorunucu** [rubenlagus/TelegramBots#228]
I take this exception while running code that explained in wiki page. I googled solutions but I found nothing. Please help! Entire error is below;

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/http/HttpEntity
	at TelegramBOT.TelegramBotMain.main(TelegramBotMain.java:22)
Caused by: java.lang.ClassNotFoundException: org.apache.http.HttpEntity
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

**Comment by rubenlagus** [comment]
Are you correctly adding all the dependencies?

**Comment by sooshee94** [comment]
Hi, I'm having this issue aswell.
You can see the full stacktrace here: https://pastebin.com/TR53VU9n

**Comment by agorunucu** [comment]
I solved the problem. I was trying to do it with Intellij Idea & MAVEN. It gave this error. Then I tried to do with Eclipse & External Jar File. It worked.

**Comment by rubenlagus** [comment]
Do you have the pom file you were using? I'm using Intellij and Maven and i have not a single problem

**Comment by agorunucu** [comment]
Here, my pom.xml file;

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.gorunucu.mavenDeneme</groupId>
  <artifactId>gorunucu</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>jar</packaging>

  <name>gorunucu</name>
  <url>http://maven.apache.org</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <dependencies>
      <dependency>
          <groupId>org.telegram</groupId>
          <artifactId>telegrambots</artifactId>
          <version>2.4.4.5</version>
      </dependency>
  </dependencies>
</project>
