### ISSUE TITLE
Do i have to send a message only when i receive a update? 

### ISSUE THREAD

**Issue by Pie133** [rubenlagus/TelegramBots#229]
Hi
Do u have to send a message only when i receive a update ?
For example i want to send a message when bot run , but it seems its impossible because i can only send message when an update received

**Comment by Clevero** [comment]
That's possible, for sure^^

This question was previously asked in #204 

@Ruben gave an [example code](https://github.com/rubenlagus/TelegramBots/issues/204#issuecomment-289251041) for it

**Comment by Clevero** [comment]
that's nice to hear! :)
