### ISSUE TITLE
Can't send photo

### ISSUE THREAD

**Issue by rovkinmax** [rubenlagus/TelegramBots#23]
I try send new photo.
But receive error from server: `{"ok":false,"error_code":400,"description":"[Error]: Photo has unsupported extension. Use one of .jpg, .jpeg, .gif, .png, .tif or .bmp"}`
I use jpg image.

**Comment by Clevero** [comment]
Possible that post a snippet of your code that produce this error?

**Comment by rovkinmax** [comment]
Sorry. Its my mistake. I'm set incorrect file name.
