### ISSUE TITLE
Change message text and inline keyboards together

### ISSUE THREAD

**Issue by Pie133** [rubenlagus/TelegramBots#235]
Sorry for asking an other question i really searched for this but i cant find any answer
I want to know how can i change a message text and inline keyboard together for a single message?
I tried to use EditMessageText and EditMessageReplyMarkup together but didn't work :(
@Clevero :D

**Comment by rubenlagus** [comment]
@Pie133 EditMessageText accept both, the new text and the new markup: https://core.telegram.org/bots/api#editmessagetext

**Comment by ViktorVx** [comment]
Look in my working example:
public void replyToEditPersonalData(long chatId, User user, Update upd) throws TelegramApiException {
        if (upd.hasCallbackQuery()) {
            long message_id = upd.getCallbackQuery().getMessage().getMessageId();
            long chat_id = upd.getCallbackQuery().getMessage().getChatId();
            String inline_message_id = upd.getCallbackQuery().getInlineMessageId();

            EditMessageText new_message = new EditMessageText().
                    setChatId(chat_id).
                    setMessageId(toIntExact(message_id)).
                    setInlineMessageId(inline_message_id).
                    setText("Text!");
            new_message.setReplyMarkup(KeyboardFactory.getInfoPersonEditKeyboard());
            try {
                sender.execute(new_message);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
