### ISSUE TITLE
Channel members

### ISSUE THREAD

**Issue by Pie133** [rubenlagus/TelegramBots#236]
Hi i want to force users to join a channel before they can use my bot
is there any way that i can get channel members chat_id in a array?

**Comment by Clevero** [comment]
It's not possible to get all ChatMembers.

You can get only the Administrators (see offical Bot API docs [getChatAdministrators](https://core.telegram.org/bots/api#getchatadministrators))

But what you could do is to check if a specific user is in your channel by using ```getChatMember``` (see offical Bot API docs [here](https://core.telegram.org/bots/api#getchatmember))

Also I recommend you to look through the offical Bot API docs. Anything what is offical described there is also implemented/possible with this library.

**Comment by Pie133** [comment]
Sorry but how can use getChatMember in your API ?

**Comment by Clevero** [comment]
All methods of the offical Bot API are basically also just methods in @rubenlagus's lib.

And you should also know an example for that. [sendMessage](https://core.telegram.org/bots/api#sendmessage)
sendMessage is a method in the API, here also
```sendMessage``` -> ```sendMessage(message);```

The same with [sendAudio](https://core.telegram.org/bots/api#sendaudio)
```sendAudio``` -> ```sendAudio(audio);```

And the list goes on, and on, and on...^^

So for getChatMember
```java
GetChatMember getChatMember = new GetChatMember():
		
//id of the chat (in your case the channel id)
getChatMember.setChatId(chatId);
		
//id of the user
getChatMember.setUserId(userId);

                   //run the actual method getChatMember
ChatMember member = getChatMember(getChatMember);
```

**Comment by fx2xf** [comment]
what happens if a user isn't a member of a channel, does it return an exception?
I tried this method and it seems it's not working :-(

**Comment by Clevero** [comment]
Don't have tested it yet, but it should return **null** if the user isn't a member of the targeted chat.

```Returns a ChatMember object on success.``` [getChatMember](https://core.telegram.org/bots/api#getchatmember)

**Comment by Fotomultman** [comment]
Please, can you make an example with getChatMembersCount ... Dont inderstand how it works

**Comment by Clevero** [comment]
@Fotomultman try to do the same scheme like in this example
https://github.com/rubenlagus/TelegramBots/issues/236#issuecomment-302244907

**Comment by Fotomultman** [comment]
```
   GetChatMemberCount getChatMemberCount = new GetChatMemberCount();
   getChatMemberCount.setChatId(ChatID);
  String  members_count = getChatMemberCount (getChatMemberCount).toString();
```
Thank you. Nice. 

the  I tried to get ArrayList of  ChatMember to getChatAdministrators

```
GetChatAdministrators getChatAdministrators = new GetChatAdministrators();
getChatAdministrators.setChatId(ChatID);
ArrayList<ChatMember> lst = getChatAdministrators (getChatAdministrators);
```

but I doesnt work...
