### ISSUE TITLE
How to start in WebHook mode?

### ISSUE THREAD

**Issue by DanikKamilov** [rubenlagus/TelegramBots#242]
Hello. Pull bot works fine, but I can't start bot in the WebHook mode. Can you add some example? 
(i got 

> May 23, 2017 9:53:00 AM org.glassfish.grizzly.http.server.NetworkListener start
> INFO: Started listener bound to [localhost:8443]
> May 23, 2017 9:53:00 AM org.glassfish.grizzly.http.server.HttpServer start
> INFO: [HttpServer] Started.

) but Telegram Bot doesn't answer me.

**Comment by pouryafard75** [comment]
Hi i have same problem too 
i have another questions too.
 public String getBotPath()  ?  whats this function , what should i do ? cuz i should impelement that.
public BotApiMethod onWebhookUpdateReceived  ?  while i used LongPollingBot this fucntion's return type was void and now i dont know what should i return . Could  u give me some help?

**Comment by DanikKamilov** [comment]
You should return your message. https://github.com/rubenlagus/TelegramBotsExample

**Comment by pouryafard75** [comment]
after implementing those functions , what should i do?

**Comment by DanikKamilov** [comment]
for example

**Comment by rubenlagus** [comment]
@pouryafard75 In example repo there is a case for that: https://github.com/rubenlagus/TelegramBotsExample/blob/master/src/main/java/org/telegram/updateshandlers/WebHookExampleHandlers.java

After implementing it, you should be able to use it

**Comment by turboSlowPoke** [comment]
Hello!  I can't make a correct .pem and .jks .... Please write or give a link to HowTo

**Comment by dapoldi** [comment]
Try here:

**Comment by turboSlowPoke** [comment]
**@dapoldi**, I tried, but didn't work out.  I need self-signed certificate. The certificate must be in PEM format (ASCII BASE64), and the file itself must contain only the public key (including the BEGIN and END lines).
And correctly written here:  https://habrahabr.ru/post/318882/  

openssl req -newkey rsa:2048 -sha256 -nodes -keyout private.key -x509 -days 365 -out public_cert.pem -subj "/C=RU/ST=State/L=Location/O=Organization/CN=**IP-SERVER-HOST**"

openssl pkcs12 -export -in public_cert.pem -inkey private.key -certfile public_cert.pem -out keystore.p12

keytool -importkeystore -srckeystore keystore.p12 -srcstoretype pkcs12 -sigalg SHA1withRSA -destkeystore keystore.jks -deststoretype JKS

rm keystore.p12
rm private.key

In the process, enter the password for the keystore, and the resulting: public_cert.pem keystore.jks

**Comment by inventoramin** [comment]
in telegram api https://core.telegram.org/bots/api#setwebhook said it's optional to send certificate but when i program with this library , i HAVE to specify .jks and .pem files.
i am using ngrok for receiving telegram's update and i don't have any .pem or .jks file of it's address.
when i set the address by postman to http://example.ngrok.com it work correctly.
what should i do?
