### ISSUE TITLE
Make sendMessage static

### ISSUE THREAD

**Issue by EverMineServer** [rubenlagus/TelegramBots#243]
Is there a way for use the sendMessage method in an external class?

**Comment by rubenlagus** [comment]
You can just pass the bot as a parameter to that external class and then execute the method from there. They are public.

**Comment by EverMineServer** [comment]
Can you tell me how?
I tried:
```
public class Answer extends TelegramLongPollingBot{

	private static Answer instance;
```

**Comment by EverMineServer** [comment]
Please can you show me how i can pass my Answer as a parameter? :'(

**Comment by rubenlagus** [comment]
http://www.c4learn.com/java/java-passing-object-as-parameter-to-method/

**Comment by EverMineServer** [comment]
`Answer ans = new Answer();`
I have this problem D:
http://prntscr.com/fea4ms

**Comment by EverMineServer** [comment]
Can you give me a small help? :(

**Comment by rubenlagus** [comment]
Why are you calling `new` on a simple method?  I don't really understand what you are trying to achieve. But if you have an instance of your `Answer` class called `myAnswer`, you can send messages just with: ``myAnswer.sendMessage(....)`

**Comment by EverMineServer** [comment]
Bot class (Answer):
```
/* 54 */ public static Answer myAnswer;
/* 55 */ Utility.countdownError(id);
```

External class (Utility):
```
	public static void countdownError(Long id) throws TelegramApiException
	{
		int[] ints = getTime(Main.countdown.get(id));
		String message = ints[1]+" minuti "+ints[2]+" secondi";
		if (ints[0] == 0 && ints[1] == 0)
		{
			message= ints[2]+" secondi";
		}
/* 31 */    Answer.myAnswer.sendMessage(new SendMessage().setText("⛔️ Aspetta "+message+" per riprovare, ti sarà inviato un messaggio alla scadenza.").setChatId(id).enableHtml(true));
	}
```
Error:
Jun 06, 2017 10:38:49 AM org.telegram.telegrambots.logging.BotLogger severe
SEVERE: BOTSESSION
java.lang.NullPointerException
        at TelegramSBOT.Utility.countdownError(Utility.java:31)
        at TelegramSBOT.Answer.onUpdateReceived(Answer.java:55)
        at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$HandlerThread.run(DefaultBotSession.java:274)

**Comment by EverMineServer** [comment]
Solved thanks :)
