### ISSUE TITLE
Sending Messages by usernames

### ISSUE THREAD

**Issue by fx2xf** [rubenlagus/TelegramBots#245]
i can't send message by putting usernames in setchatId function argument,
and also I can't send messages to channels, I am receiving this exception : Forbidden: bot is not a member of the channel chat

**Comment by rubenlagus** [comment]
According to documentation:

```
Unique identifier for the target chat or username of the target channel
```

Meaning that you can only use usernames for channels, not for normal users. And, of course, you can only send messages to channels where you bot is an admin.

**Comment by fx2xf** [comment]
I know, but my bot IS a channel admin, and though I can't send messages in it :-(

**Comment by fx2xf** [comment]
I am really sorry, I got that, You can now close this issue !!

**Comment by Clevero** [comment]
What was the problem?
You also can always close the issue by yourself^^
