### ISSUE TITLE
android problem

### ISSUE THREAD

**Issue by soshiant1992** [rubenlagus/TelegramBots#251]
i dont even know if i should be puting it here. so excuse me if i'm way off.
i'm tring to add this library to android app in android studio. when i add it by jar it will not give me errors but it will try to build but never finishes. when i try to adding it by the gradle      
compile "org.telegram:telegrambots:3.0.1"
it will builds but gives me some runtime err

`AGPBI: {"kind":"error","text":"Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Predicate","sources":[{"file":"C:\\Users\\soshiant\\AndroidStudioProjects\\Glassbutton3\\DefaultBotSession.java","position":{"startLine":215,"endLine":216}}]}
AGPBI: {"kind":"error","text":"Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.function.Function","sources":[{"file":"C:\\Users\\soshiant\\AndroidStudioProjects\\Glassbutton3\\DefaultBotSession.java","position":{"startLine":216,"endLine":217}}]}
AGPBI: {"kind":"error","text":"Lambda coming from jar file need their interfaces on the classpath to be compiled, unknown interfaces are java.util.Comparator","sources":[{"file":"C:\\Users\\soshiant\\AndroidStudioProjects\\Glassbutton3\\DefaultBotSession.java","position":{"startLine":217,"endLine":218}}]}
`
while building it gives warnings like this :

`WARNING: WARNING: Dependency org.apache.httpcomponents:httpclient:4.5.3 is ignored for release as it may be conflicting with the internal version provided by Android.
         In case of problem, please repackage it with jarjar to change the class packages
WARNING: WARNING: Dependency org.json:json:20160810 is ignored for release as it may be conflicting with the internal version provided by Android.
         In case of problem, please repackage it with jarjar to change the class packages`

**Comment by rubenlagus** [comment]
please, check #193, #213, #214
