### ISSUE TITLE
Payments API

### ISSUE THREAD

**Issue by DenisWpk** [rubenlagus/TelegramBots#254]
Hi! 

I try to use payments API. 
I catch error: 
```java
июн 19, 2017 1:07:33 PM org.telegram.telegrambots.logging.BotLogger severe
SEVERE: BOTSESSION
java.lang.NullPointerException
	at org.telegram.telegrambots.api.methods.send.SendInvoice.validate(SendInvoice.java:354)
	at contactBot.botCreator2.handleIncomingMessage(botCreator2.java:229)
	at contactBot.botCreator2.onUpdateReceived(botCreator2.java:71)
	at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$HandlerThread.run(DefaultBotSession.java:274)
```

Below my code:
```java
List<LabeledPrice> price = new List<LabeledPrice>();
price.add(new LabeledPrice("label", 10000));

SendInvoice inv = new SendInvoice(Integer.parseInt(message.getChatId().toString()), "Hello", "Hello", "111", "#########:TEST:###", "StartParam", "RUB", price);
try {
	inv.validate();
} catch (TelegramApiValidationException e2) {
	e2.printStackTrace();
}
try {
	sendInvoice(inv);
} catch (TelegramApiException e1) {
	e1.printStackTrace();
}
```
Do you have example code of payments or where is my mistake?
Thank you!

**Comment by rubenlagus** [comment]
Which api version are you using?

**Comment by DenisWpk** [comment]
Thanks for fast answer. 

Now works, but image not displayed. 
I use direct link (I try use gdrive links also)
Please, give me advice about correct use setPhotoUrl. 
Below my code: 
```java
SendInvoice inv = new SendInvoice(Integer.parseInt(message.getChatId().toString()), "Hello", "Hello", "111", "#########:TEST:###", 
      "StartParam", "RUB", price).setPhotoUrl("https://1fichier.com/?m1grvfz34i");
```
Result:
![0c7f2c85-56bd-46c5-b4df-b79c3acd31d9](https://user-images.githubusercontent.com/8546089/27279449-14b9bfc2-54fe-11e7-9c90-ddbddf04ed39.jpg)


Thank you!

**Comment by rubenlagus** [comment]
Check your image, it doesn't point to an `image/jpeg` file.

**Comment by DenisWpk** [comment]
Why? 
If go to link https://1fichier.com/?m1grvfz34i downloaded .jpg file. 
Or I dont understand...

**Comment by rubenlagus** [comment]
But it is not a correct `image/jpeg`:

![image](https://user-images.githubusercontent.com/2874352/27279917-6ed4dfd6-54e6-11e7-8115-75ac108fec31.png)

**Comment by DenisWpk** [comment]
Another link with ```image/jpeg``` content-type.
https://drive.google.com/uc?export=download&id=0BydBkApd9R5PQWdlQTcwWDh4SjA

Invoice disaplayed with white image also.
When I click on image for display it on screen a catch error:
```java
org.telegram.telegrambots.exceptions.TelegramApiRequestException: Error getting updates: [409] Conflict: terminated by other long poll or webhook
	at org.telegram.telegrambots.api.methods.updates.GetUpdates.deserializeResponse(GetUpdates.java:119)
	at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$ReaderThread.run(DefaultBotSession.java:208)
```

**Comment by rubenlagus** [comment]
https://github.com/rubenlagus/TelegramBots/wiki/Errors-Handling#terminated-by-other-long-poll-or-webhook

**Comment by DenisWpk** [comment]
Sorry for stupid error((

Now error is dissapear, but image still white. When I tap on image it loaded endless.
I test my internet connection - all works, I test invoice in bot @shopbot - image is displayed.

Its very strange. I dont understand whats wrong.

**Comment by rubenlagus** [comment]
@DenisWpk still no way to show the images? Have you tried using some random image from internet as a test?

**Comment by DenisWpk** [comment]
Hi! 
I try to use different image hosting but there is no result. The image is still white (

**Comment by EXL** [comment]
Same bug. Image are white on mobile, but normal on the desktop client.

Any suggestions? Thanks.

**Comment by EXL** [comment]
@DenisWpk 

> @shopbot - image is displayed

I tested now @shopbot on Android client and image in the invoice is not displayed. But on Desktop client all OK. Maybe there is a bug in Android client of Telegram?

Android:
![screenshot_2017-07-09-22-08-09](https://user-images.githubusercontent.com/232116/27995182-4a8f497c-64f4-11e7-8ed7-fb33bc445cd4.png)

Desktop:
![screenshot_20170709_221502](https://user-images.githubusercontent.com/232116/27995183-543e6214-64f4-11e7-9cd5-08f36af7ff69.png)

**Comment by minecraft8997** [comment]
plz give me full working code
