### ISSUE TITLE
Incorrect filename after upload if it contains cyrillic symbols

### ISSUE THREAD

**Issue by sinnus** [rubenlagus/TelegramBots#257]
I'm trying to sendDocument where filename contains cyrillic symbols.
The actual filename is "Маркетинг_план.pptx". After upload it looks like "?????????_????.pptx".

![default](https://user-images.githubusercontent.com/144127/27428562-1e46600a-574b-11e7-903f-a47964439165.png)

**Comment by rubenlagus** [comment]
Maybe related to #256 ?

**Comment by devbridie** [comment]
Indeed, #256 fixes this issue in the cases I have seen.

**Comment by rubenlagus** [comment]
#274 should fix this completely
