### ISSUE TITLE
how get user name and name in bot

### ISSUE THREAD

**Issue by mbarzegar93** [rubenlagus/TelegramBots#258]
hi
i want to get my users user names and their name
right now i cat save their chat id [update.getMessage().getChatId()]
how can i get their user name and their name too??
please with example
tnx

**Comment by rubenlagus** [comment]
Inside [Message](https://core.telegram.org/bots/api#message) object returned by `getMessage()` you will find a the `from` field with the user information.

**Comment by mbarzegar93** [comment]
i don't have `from` field in `getMessage()`
i use telegrambots 2.4.4.5 library? is the library version is a problem???or it not implemented yet?

**Comment by rubenlagus** [comment]
As you can see, it is present, everything defined in the official docs API is present: https://github.com/rubenlagus/TelegramBots/blob/2.4.4.5/telegrambots-meta/src/main/java/org/telegram/telegrambots/api/objects/Message.java#L55

**Comment by mbarzegar93** [comment]
problem solved tnx
i should use `update.getMessage().getFrom().getUserName()` for getting user name
