### ISSUE TITLE
Updating messages with inline bot

### ISSUE THREAD

**Issue by kmare** [rubenlagus/TelegramBots#259]
Hello, first of all thank you for this awesome library! 
I have an inline bot issuing inline queries. I get the callback response just fine, add an few inline buttons and update the message using editMessageText. This works just fine for text, but what I'd like to do is updating that message sending a photo instead of text. Is this even possible with the API or a limitation of the library?
Thank you in advance.

**Comment by rubenlagus** [comment]
As you can see in the docs, there is no API method to update non-text messages: https://core.telegram.org/bots/api#updating-messages

**Comment by liketechnik** [comment]
It's possible to achieve the same behaviour by deleting the message and sending a different version of the message which has another picture.

**Comment by kmare** [comment]
@rubenlagus Thank you, thought as much, wasn't 100% sure as I believed I might have missed something.
@liketechnik thank you for your answer. My problem is that I'm processing the callback using an inlinequery, so I don't have a chatID to send the photo. That would work when interacting with the bot directly, but I guess not inline. Unless I misunderstood what you meant.

**Comment by liketechnik** [comment]
It should also work with inline, you can get the message ID of inline messages too (though I don't remember how). 

Am 27. Juni 2017 00:13:55 MESZ schrieb Ioannis Panteleakis <notifications@github.com>:
>@rubenlagus Thank you, thought as much, wasn't 100% sure as I believed
>I might have missed something.
>@liketechnik thank you for your answer. My problem is that I'm
>processing the callback using an inlinequery, so I don't have a chatID
>to send the photo. That would work when interacting with the bot
>directly, but I guess not inline. Unless I misunderstood what you
>meant.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/rubenlagus/TelegramBots/issues/259#issuecomment-311197142

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
