### ISSUE TITLE
Bot can't promote admin with change info permission

### ISSUE THREAD

**Issue by kanphis** [rubenlagus/TelegramBots#264]
Found bug in code
https://github.com/rubenlagus/TelegramBots/blob/master/telegrambots-meta/src/main/java/org/telegram/telegrambots/api/methods/groupadministration/PromoteChatMember.java#L28
https://core.telegram.org/bots/api#promotechatmember

parameter in Bot API named can_change_info, not can_change_information

Cause of that I can't promote admins with this permission through bot
Please, fix this 🙏

**Comment by rubenlagus** [comment]
I'll make a hotfix tonight, thx
