### ISSUE TITLE
Update queue processed backwards (receivedUpdates.pollLast) and batch updates processing

### ISSUE THREAD

**Issue by vantuz-subhuman** [rubenlagus/TelegramBots#269]
[This line of code](https://github.com/rubenlagus/TelegramBots/blob/master/telegrambots/src/main/java/org/telegram/telegrambots/updatesreceivers/DefaultBotSession.java#L264) takes the queue of all new incoming messages and polls **the last** one from the queue.

The main effect of this code is that when bot experiences some network problems, or was  down for some time - it receives all missed updates in backward order (from newest to oldest). That seems super weird and hard to process.

Is it a specified feature that I've missed? Or is it a bug?

**Comment by vantuz-subhuman** [comment]
В целом было бы полезной фичей при желании давать возможность получать ВСЕ висящие апдейты. А то у меня юзкейс такой:
1. Выполнять реальные команды по старым запросам нельзя, потому что это может быть опасно
2. При возврате бота в рабочий режим нужно уведомить авторов пропущенных запросов, что бот снова в рабочем состоянии
3. Просто проверять апдейт на старость и отвечать нельзя, потому что в одном чате могло быть пропущено несколько сообщений, и тогда бот будет при включении присылать сразу пачку извинений, что выглядит ужасно

В итоге единственным нормальным решением, не залезая в служебные классы остаётся - копить апдейты, приходящие в `onUpdateReceived`, пока время их отправки старее лимита, а потом ждать какое-то время в отсутствие новых сообщений и обрабатывать накопленное сразу пачкой. Но тут возникают две проблемы:
1. Сообщения приходят задом наоборот, а значит я могу получить сперва пропущенное сообщение не старее лимита, а потом пропущенное сообщение старее лимита. Что клинически неадекватно.
2. Кажется бессмысленным писать складывание приходящих единичных уведомлений в очередь, если знаешь, что к тебе в метод они приходят **ИЗ** очереди.

Т.ч. единственным дейтствительно адекватным решением будет скопипастить половину классов фреймворка и переделать всё так, чтобы бот мог получать сразу всю пачку накопившихся сообщений.

**Comment by vantuz-subhuman** [comment]
Собсна, так и сделал, пришлось скопипастить `DefaultBotSession` и немного изменить `HandlerThread`, и запилить свой `BatchLongPollingBot`, с методом, принимающим коллекцию, вместо одного единственного апдейта.

Зато теперь всё работает, как часы. Апдейты приходят сразу пачкой и в правильном порядке, т.ч. я могу легко отсортировать их по чатам и обрабатывать уже в отдельном контексте.

Если у кого-то возникла такая же проблема, то могу попробовать запилить пуллрек авторам. А дальше на их усмотрение.

**Comment by Clevero** [comment]
I think it would be better to write in English if you want that we can understand you (probably most of us)

**Comment by vantuz-subhuman** [comment]
Wow, super sorry O_o
Just got carried away for a while.
I will fix it shortly.

**Comment by Clevero** [comment]
thanks :)

**Comment by rubenlagus** [comment]
@vantuz-subhuman Sounds like a but indeed, a pull request would be nice ;)

**Comment by vantuz-subhuman** [comment]
Will do this week. @rubenlagus, would you like me to include the `TelegramBatchLongPollingBot`, described in the second comment?

**Comment by vantuz-subhuman** [comment]
Will do this week.
