### ISSUE TITLE
Enhancement: setters to builder style

### ISSUE THREAD

**Issue by Pixelase** [rubenlagus/TelegramBots#27]
Hi!
Would it be appropriate to make setters in the builder style?
Like this: 
```java
    public SomeClass setField(String field) {
        this.field = field;
        return this;
    }
```
In my opinion, this will add a bit of usability.
```java
sendMessage(new SendMessage().setChatId(chatId).setText("Text"));
````
If you need it, i can handle it and send you pull request.
Regards.

**Comment by rubenlagus** [comment]
Looks nice, not that I like to return always a pointer, but indeed it may be helpful in those cases. Feel free to go ahead with it ;)

**Comment by rubenlagus** [comment]
But please, make the pull request agains dev branch ;)

**Comment by Pixelase** [comment]
@rubenlagus ok ;)
