### ISSUE TITLE
How can i send a KeyBoardButton object?

### ISSUE THREAD

**Issue by Pie133** [rubenlagus/TelegramBots#278]
how can i send this object to my client?

KeyboardButton keyboardButton = new KeyboardButton();
        keyboardButton.setRequestContact(true);
        keyboardButton.setText("Send your number");

**Comment by Clevero** [comment]
Did you read the wiki?

https://github.com/rubenlagus/TelegramBots/wiki/FAQ#how_to_use_custom_keyboards

and also this example bot  in MonsterDevelopers book (also referenced in the wiki) uses custom keyboards
https://monsterdeveloper.gitbooks.io/writing-telegram-bots-on-java/content/lesson-2.-photobot.html

**Comment by Pie133** [comment]
But i cant add a KeyboardButton object to a KeyboardRow
i need to use keyboardbutton object because i need to ask for client number
Can you just give me an example to how send a button that request client number?
sorry for my bad english

**Comment by Clevero** [comment]
Why you cannot add a KeyboardButton to a KeyboardRow?

**Comment by Clevero** [comment]
@Pie133 is your problem solved?

**Comment by Clevero** [comment]
@rubenlagus I think this issue can be closed due to inactivity

**Comment by vse-prosto** [comment]
Аналогичный вопрос

`$data['reply_markup'] = (new Keyboard(
                        (new KeyboardButton('Share Contact'))->setRequestContact(true)
                    ))`
Не работает
