### ISSUE TITLE
Webhook update without responce

### ISSUE THREAD

**Issue by turboSlowPoke** [rubenlagus/TelegramBots#282]
I would like the bot not to respond to some messages. I use, webhook. In the method _BotApiMethod onWebhookUpdateReceived(Update update)_, I must return the answer so that the telegram considers the update to be accepted. Empty String in SendMesage or null do not match. As far as I understand, the telegram does not close the http session until it receives an responce, and for the next message creates a new one ... until the bot sessions ends. . After the bot restart, the telegram again sends all the unanswered messages

**Comment by inventoramin** [comment]
i got a problem like this , i set everything and test the webhook with a ruby program and it works fine , bot when i start my own webhook program ( that it's code is like longpolling) i got 520 error

**Comment by rubenlagus** [comment]
@turboSlowPoke Doesn't a `return null;` solves it, It should return a 204 status code that should be valid for Telegram servers.

**Comment by inventoramin** [comment]
@rubenlagus can u give an example?
