### ISSUE TITLE
Save chat_id

### ISSUE THREAD

**Issue by djmanbr** [rubenlagus/TelegramBots#285]
Anyone knows how to save all chat_id has used the bot and then do a broadcast?

**Comment by Clevero** [comment]
You need to save them manually.

If a message comes in:
Is this user in my list of users?
    yes: go ahead
    no: add him to the list

If you then want to make a broadcast, grab that list and iterate through it while sending the messages. Please be aware of the [API limits](https://core.telegram.org/bots/faq#my-bot-is-hitting-limits-how-do-i-avoid-this)
