### ISSUE TITLE
Delete all messages sent in group?

### ISSUE THREAD

**Issue by djmanbr** [rubenlagus/TelegramBots#286]
There is any method to delete all messages from a group?

**Comment by Clevero** [comment]
Try to go through the official docs of the Telegram Bot API

https://core.telegram.org/bots/api

Absolutely everything that described there, is also implemented in this library here.

If you search in the docs, you will see that there is a method called ```deleteMessage```
For that, you need to know the message_id of the targeted message.

**Comment by rubenlagus** [comment]
There is no method like that in the API, so it won't be added to this library.
