### ISSUE TITLE
Android studio Error in project execution

### ISSUE THREAD

**Issue by pouriajava** [rubenlagus/TelegramBots#287]
![untitled](https://user-images.githubusercontent.com/30587682/29001084-20b31010-7a94-11e7-918f-42f35bd9bab1.png)

**Comment by rubenlagus** [comment]
please, check #193, #213, #214

**Comment by DhiaSyahmie** [comment]
![image](https://user-images.githubusercontent.com/29621392/29573264-1d598e8a-8791-11e7-8f57-7667ad59cbc8.png)

I'm trying to make a very simple apps that will run the bot and shows the logs on the screen. I used Android Studio 3.0 beta 2 which is the latest for now.

"Android Studio 3.0 Preview 1 and later supports all Java 7 language features and a subset of Java 8 language features that vary by platform version. This page describes the Java 8 language features you can use, how to properly configure your project to use them, and any known issues you may encounter."

The paragraph above is the first paragraph written in the page about Android Studio 3.0 beta 2 features. https://developer.android.com/studio/write/java8-support.html

Still, I got errors as shown in the screenshot when executed.

**Comment by rubenlagus** [comment]
Do you really need the Abilities? if not, you can omit that project. 

Maybe it is also a good idea to add this library as described in the [readme](https://github.com/rubenlagus/TelegramBots#usage). This way should needed dependencies.

**Comment by DhiaSyahmie** [comment]
![image](https://user-images.githubusercontent.com/29621392/29598075-40b50202-87f9-11e7-809e-7f385a534a01.png)

This one got successfully installed but it wont run. It crashed right after opening the apps and I dont have any idea why

**Comment by DhiaSyahmie** [comment]
I found out my apps crash when constructing my Bot.class that extends TelegramLongPollingBot

**Comment by rubenlagus** [comment]
Do you have any exception or information of the type of crash?

**Comment by rubenlagus** [comment]
Close due to inactivty
