### ISSUE TITLE
build bot

### ISSUE THREAD

**Issue by vort3xdev** [rubenlagus/TelegramBots#289]
the learning was very simple.in the onUpdateReceived() method i need to response a message that depends to the older message.what shoud i do?

**Comment by vort3xdev** [comment]
example:there are three different buttons:1 and 2 and 3
if he click at 1 show 4 and 5 and 6
if he click at 4 show 5 and 7 and 8.its too much and i havn't a list from them to create a listener for each of them.in my project and for example they are directories and 2 and 3 and four are sub directory of 1

**Comment by vort3xdev** [comment]
also can any body say what it is WebhookBot and how use it?
i need to learn all of this but i cant

**Comment by fedochet** [comment]
@vort3xdev you can find some useful information here: [https://github.com/rubenlagus/TelegramBots/wiki/Getting-Started#build-our-first-bot](url).

**Comment by MonsterDeveloper** [comment]
@fedochet You link is not working, @vort3xdev try to go here: https://monsterdeveloper.gitbooks.io/writing-telegram-bots-on-java/content/lesson-5.-deploy-your-bot.html

**Comment by rubenlagus** [comment]
The liink is https://github.com/rubenlagus/TelegramBots/wiki/Getting-Started, that's a basic version of a bot
