### ISSUE TITLE
why is getfile Deprecated and what is the alternative?

### ISSUE THREAD

**Issue by aranmohyeddin** [rubenlagus/TelegramBots#290]

**Comment by rubenlagus** [comment]
https://github.com/rubenlagus/TelegramBots/wiki/Changelog#310

**Comment by memerioo** [comment]
I'm sorry but I really can't find anything about getfile in the changelog.

**Comment by Clevero** [comment]
@aranmohyeddin is your problem solved? Do you have any further questions?
If no, can you close this issue?

**Comment by MetaiR** [comment]
@Clevero 
I'm new in this framework and I didn't realize what is the alternative of `getfile`

**Comment by Clevero** [comment]
https://github.com/rubenlagus/TelegramBots/wiki/FAQ#method-sendmessage-or-other-is-deprecated-what-should-i-do
