### ISSUE TITLE
Cant GetStickerSet into SetSticker object Need help

### ISSUE THREAD

**Issue by Fotomultman** [rubenlagus/TelegramBots#298]
Hi, I need to get telegram sticker set  info...
` GetStickerSet getStickerSet = new GetStickerSet();`
`getStickerSet.setName("Betsey"); `
` SetSticker setSticker =  getStickerSet (getStickerSet);`

But theere is a mistake.

What's my mistake? or  How to get StickerSet info anyway?
Thanks in advance!

**Comment by Clevero** [comment]
What do you mean with "But theere is a mistake."?

**Comment by Fotomultman** [comment]
`SetSticker setSticker = getStickerSet (getStickerSet);`

**Comment by Clevero** [comment]
Yeah, what mistake? Do you get any errors?

**Comment by rubenlagus** [comment]
Close due to inactivity
