### ISSUE TITLE
Bot reacts on commands in past. What can we do?

### ISSUE THREAD

**Issue by Fotomultman** [rubenlagus/TelegramBots#300]
The situation...
The bot in the group.
I'm turning it off,,, It stops reacting of couse. Then users put some commands in chat...
Then I turn bot on... and it begins to react on past messages... 
How to solve the problem with past messages reaction? Is it possible? 
Thank you in advance!

P.S. Maybe have to compare message date-time  in the begin with current date-time?

**Comment by Clevero** [comment]
You could check the date of the receiving message before you process it

See ```date``` field in the Message object offical [Telegram Bot API docs](https://core.telegram.org/bots/api#message)

**Comment by Fotomultman** [comment]
Yes, thank you.  It works.
