### ISSUE TITLE
NoClassDefFoundError for TelegramApiException when trying to execute .jar file

### ISSUE THREAD

**Issue by atharvjoshi** [rubenlagus/TelegramBots#301]
Hello. When I try to execute my jar file, it does not execute and gives the following error message:

Error: Unable to initialize main class Main
Caused by: java.lang.NoClassDefFoundError: org/telegram/telegrambots/exceptions/TelegramApiException

How to work around this issue? Thanks.

**Comment by Clevero** [comment]
How do you added the jar to your project? maven, gradle? by hand?

**Comment by keeper32** [comment]
I've built a Servlet-based project using the jar and encontered the same issue when redeploing the project on apache Tomcat. Cleaning/restarting solved it, but it a bit of hurdle doing it every time you change something in a class. No problems in jetty, btw.

**Comment by MortezaTaghaddomi99** [comment]
![image](https://user-images.githubusercontent.com/43267281/55481317-5aea3800-5637-11e9-9eb3-c0ca36ffde6c.png)

I have the same problem, I've packaged the project by mvn package. but when I run it this exception throws.

**Comment by rubenlagus** [comment]
@MortezaTaghaddomi99 Are you setting the classpath so you have all the jar libraries availables?

**Comment by AlexanderKositsyn** [comment]
i have the same problem. Not solved?

**Comment by borodatyidrug** [comment]
The same problem. I've already broken my whole head - I can't decide in any way. Everything is according to the instructions from the Maven documentation, but it does not work.
