### ISSUE TITLE
getFieldID throws exception  [400] Bad Request: can't parse entities in message text

### ISSUE THREAD

**Issue by Fotomultman** [rubenlagus/TelegramBots#303]
Hi, when I try to get FieldID of the sticker method getFieldID throws exception t: Can't find end of the entity starting at byte offset 19. 
It happens on current stickers. Is it possible that there are some special symbols ?? 

Here is the code:

>  private void sndMessage(Message message, String text) {
>     SendMessage sendMessage = new SendMessage();
>     sendMessage.enableMarkdown(true);
>     sendMessage.setChatId(message.getChatId().toString());
>     sendMessage.disableNotification();
>     sendMessage.setText(text);
> 
>     try {
>         execute(sendMessage);
>     } catch (TelegramApiException e) {
>         e.printStackTrace();
>     }
> 

> Message message = update.getMessage(); //get message object 
>    if (message != null && message.getSticker() != null) 
> sndMessage(message,message.getSticker().getFileId());
> }

Any ideas?

**Comment by Fotomultman** [comment]
The problem because of 
> sendMessage.enableMarkdown(true);
Some stickers fileds id have symbol "_" inside...
for example. CAADBQADBgEAAukKyAN**_**KpeTpTLWTAI
How to solve this problem with hat symbol and stay Markdown (true)?

**Comment by Clevero** [comment]
Please see https://github.com/rubenlagus/TelegramBots/issues/121
