### ISSUE TITLE
TelegramApiException message.

### ISSUE THREAD

**Issue by smartdeath** [rubenlagus/TelegramBots#310]
I have a problem with **TelegramApiException**  when I send a message with bad chat id, exception message just is `Error sending message`  i need return why can't send the message.

**Comment by Clevero** [comment]
Could you please provide a code snippet?

**Comment by smartdeath** [comment]
`SendMessage sendMessage = new SendMessage();
        sendMessage.setChatId(chatId);
        sendMessage.setText(text);
        sendMessage.setParseMode("html");
        execute(sendMessage);`

**Comment by smartdeath** [comment]
@Clevero  Hello. Did you see my code !?

**Comment by Clevero** [comment]
@smartdeath Sorry, was a bit busy last days. Will look into it after work!

**Comment by Clevero** [comment]
Try to print the StackTrace (or analyze) rather than just reading the exception message
#### e.getMessage()
```java
SendMessage ms = new SendMessage();
    ms.setChatId(133333337L); //bad chat id
    ms.setText(text);
    try {
        execute(ms);
    } catch (TelegramApiException e) {
        System.out.println(e.getMessage());
    }
```
Will cause the following error message:
```
Error sending message
```
#### e.printStackTrace()
```java
SendMessage ms = new SendMessage();
    ms.setChatId(133333337L); //bad chat id
    ms.setText(text);
    try {
        execute(ms);
    } catch (TelegramApiException e) {
        e.printStackTrace();
    }
```
Will cause the following error message:
```
org.telegram.telegrambots.exceptions.TelegramApiRequestException: Error sending message: [400] Bad Request: chat not found
	at org.telegram.telegrambots.api.methods.send.SendMessage.deserializeResponse(SendMessage.java:170)
	at org.telegram.telegrambots.api.methods.send.SendMessage.deserializeResponse(SendMessage.java:24)
	at org.telegram.telegrambots.bots.DefaultAbsSender.sendApiMethod(DefaultAbsSender.java:605)
	at org.telegram.telegrambots.bots.AbsSender.execute(AbsSender.java:53)
	at MyClass.sndMessage(MyClass.java:97)
	at MyClass.onUpdateReceived(MyClass.java:38)
	at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$HandlerThread.run(DefaultBotSession.java:271)

```

**Comment by smartdeath** [comment]
@Clevero I know can use of **printStackTrace** I want to get just message exception.

**Comment by KyouinDev** [comment]
Try this way:
`public String stackTrace(Exception e) {
        StringWriter sw = new StringWriter();
        PrintWriter pw = new PrintWriter(sw);

        e.printStackTrace(pw);
        String stacktrace = sw.toString();
        pw.close();

        try {
            sw.close();
        } catch (IOException e1) {
            e1.printStackTrace();
        }

        return stacktrace;
    }`

**Comment by smartdeath** [comment]
@Clevero , @KyouinDev  Thank you .
But I fixed it with this way : 
```
    public void text(SendMessage sendMessage) throws TelegramApiException {
        try {
            execute(sendMessage);
        } catch (TelegramApiRequestException e) {
            logger.error(e.getApiResponse() + " " + e.getErrorCode());
            logger.error(sendMessage.toString());
        }
    }
```
