### ISSUE TITLE
RuntimeException while sending large audio files

### ISSUE THREAD

**Issue by dazzbourgh** [rubenlagus/TelegramBots#311]
I've encountered following exception while sending large audio files (around 150mb, ~1h long):

`java.lang.RuntimeException: Error sending audio`

Small files are sent ok, but for larger one this occurs every time. My class extends `TelegramLongPollingBot` and uses method `sendAudio(SendAudio sendAudio)`, the `SendAudio` object contains a link to a file. Am I doing something wrong, is there any restriction on size/length of the file?

Thanks!

**Comment by Clevero** [comment]
The offical Telegram Bot API doc states:

```Provide Telegram with an HTTP URL for the file to be sent. Telegram will download and send the file. 5 MB max size for photos and 20 MB max for other types of content.```

```Post the file using multipart/form-data in the usual way that files are uploaded via the browser. 10 MB max size for photos, 50 MB for other files.```

For for information please read through the docs [Sending files](https://core.telegram.org/bots/api#sending-files)

**Comment by dazzbourgh** [comment]
Thank you
