### ISSUE TITLE
How Format Text

### ISSUE THREAD

**Issue by damorosodaragona** [rubenlagus/TelegramBots#312]
Hi, i have a little problem, i would that my bot respond in some situations with a bold formatted message, i try to do it with html tag but don't work, where is the problem?
`
       
	public void processNonCommandUpdate ( Update update ) {
		// TODO Auto-generated method stub
		
			SendMessage m = new SendMessage (update.getMessage ().getChatId () , "&lt;b&gt;"+ update.getMessage ().getText () + "&lt;/b&gt;");
			//<b>text</b>

			m.enableHtml ( true );

			
			try {
				execute ( m );
				
			} catch ( TelegramApiException e ) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
	}
`

But i have answer like this: 
![image](https://user-images.githubusercontent.com/15249587/31090513-281bca9a-a7a8-11e7-9fe3-a045775ad9da.png)

P.S
I use the latest jar, 3.3.

**Comment by Clevero** [comment]
Don't need to obfuscate your code 😅

Try simply the following:
```java
SendMessage ms = new SendMessage();
    ms.setChatId(update.getMessage().getChatId());
    String myText = "<b>This is bold</b>";
    ms.enableHtml(true);
    ms.setText(myText);
    try {
         execute(ms);
    } catch (TelegramApiException e) {
         e.printStackTrace();
    }

```

![photo_2017-10-02_23-23-56](https://user-images.githubusercontent.com/6106081/31100251-fe04042c-a7c8-11e7-948f-e9742330c2b4.jpg)


Note: You can see a list of suppoted HTML tags in the offical Telegram Bot API docs [HTML style](https://core.telegram.org/bots/api#html-style)
