### ISSUE TITLE
How can i create menu on a button?

### ISSUE THREAD

**Issue by damorosodaragona** [rubenlagus/TelegramBots#313]
There is a way to create a menu when the user press on a button that the bot have send?

**Comment by Clevero** [comment]
![sojdhs](https://user-images.githubusercontent.com/6106081/31102495-ab8af386-a7d2-11e7-963a-45f52b44e073.PNG)

you mean like this? or do you want a pop up when a user pressed into a button?

**Comment by damorosodaragona** [comment]
A pop up when the user press the button!

**Comment by Clevero** [comment]
That's not really possible

But a workaround would be if you use Inline mode
https://core.telegram.org/bots/inline

**Comment by damorosodaragona** [comment]
Ok. Thank's so much!
