### ISSUE TITLE
How i test my bot ?

### ISSUE THREAD

**Issue by damorosodaragona** [rubenlagus/TelegramBots#315]
Hi, i have a class MyBot that extends TelegramLongPollingCommandBot implements LongPollingBot, know i want write test, i have try with Mockito but i can't understand to use it for testing the bot.
I have find an example test class here https://github.com/addo37/ExampleBots/blob/master/src/test/java/org/telegram/examplebots/ExampleBotTest.java but it work only if i use AbilityBot API, there is a way to do this without using that API?

**Comment by Clevero** [comment]
1. Why do you extend ```TelegramLongPollingCommandBot``` and implement ```LongPollingBot```. You only need to extend TelegramLongPollingCommandBot. 

2. The easiest way would be to create instances of Update, fill it it that it fits your needs(chat id, message text, etc.) and then pass it to ```onUpdateReceived```

**Comment by damorosodaragona** [comment]
1) you are right! Since know i have used old api, and with old api you must extend TelegramLongPollingBot and implements LonPollingBot.
2)I have try to do it, but when you create an istance of update you can't set the message or the chatID..

**Comment by damorosodaragona** [comment]
1. Ok, maybe i'm wrong, I have checked but in the examples there isn't a class that use that interfaces. I don't know why i have added.. 
2. Thank's so much. I have do this: `test(){
Update update = new Update();
`
but i can't understand how set the fields which i need, because i find only getMethods on update object.

**Comment by rubenlagus** [comment]
Hi @damorosodaragona , have a look at those tests: https://github.com/rubenlagus/TelegramBots/blob/master/telegrambots/src/test/java/org/telegram/telegrambots/test/TestRestApi.java
