### ISSUE TITLE
/delete

### ISSUE THREAD

**Issue by iatomatt** [rubenlagus/TelegramBots#318]
Hi! My code is:
```
SendSticker sticker = new SendSticker();
sticker
    .setChatId(chat_id)
    .setSticker("AAQCABNQBBAOAAT5KuJRo0p48iiJAAIC");
try {
    execute(sticker); //here is mistake
}catch (TelegramApiException e) {
    e.printStackTrace();
}
```
in line 
`execute(sticker);`
i've got a mistake:

> execute (Method) in AbsSender cannot be applied to
> (org.telegram.telegrambots.api.methods.send.SendSticker)
> 
>  reason: no instance(s) of type variable(s) T exist so that SendSticker conforms to BotApiMethod<T>

How can i fix it? Thx!

**Comment by iatomatt** [comment]
Ок, i find solution. I need too use sendSticker method.

**Comment by Clevero** [comment]
@iatomatt your problem is solved, right? Then please close this issue^^
