### ISSUE TITLE
The resourceconfig does not contain any root resource classes

### ISSUE THREAD

**Issue by Pinokevin** [rubenlagus/TelegramBots#321]
I'm making a bot for bitbucket with the telegram bot included. If I'm working with a rest plugin module from atlassian and if I add the dependency to the pom for org.telegram.telegrambots and import the libraby .jar I got this error:

`[INFO] [talledLocalContainer] 2017-10-26 10:28:55,144 ERROR [http-nio-7990-exec-9] admin @16I38G3x628x66x5 e9lp6p 0:0:0:0:0:0:0:1 "GET /rest/hotfixmesadmin/1.0/application.wadl HTTP/1.1" c.s.j.s.i.a.RootResourceUriRules The ResourceCo
nfig instance does not contain any root resource classes.
[INFO] [talledLocalContainer] okt 26, 2017 10:28:55 AM com.sun.jersey.server.impl.application.RootResourceUriRules <init>
[INFO] [talledLocalContainer] SEVERE: The ResourceConfig instance does not contain any root resource classes.
[INFO] [talledLocalContainer] 2017-10-26 10:28:55,368 ERROR [http-nio-7990-exec-9] admin @16I38G3x628x66x5 e9lp6p 0:0:0:0:0:0:0:1 "GET /rest/hotfixmesadmin/1.0/application.wadl HTTP/1.1" c.a.p.s.DefaultServletModuleManager Unable to c
reate new reference LazyLoadedFilterReference{descriptor=com.atlassian.bitbucket.plugin.HotfixMes.HotfixMes-Plugin:hotfixmesadmin-filter (The hotfixmesadmin Plugin), filterConfig=com.atlassian.plugin.servlet.filter.PluginFilterConfig@
22247b54}
[INFO] [talledLocalContainer] com.atlassian.util.concurrent.LazyReference$InitializationException: com.sun.jersey.api.container.ContainerException: The ResourceConfig instance does not contain any root resource classes.
[INFO] [talledLocalContainer]   at com.atlassian.util.concurrent.LazyReference.getInterruptibly(LazyReference.java:149) ~[atlassian-util-concurrent-3.0.0.jar:na]
[INFO] [talledLocalContainer]   at com.atlassian.util.concurrent.LazyReference.get(LazyReference.java:112) ~[atlassian-util-concurrent-3.0.0.jar:na]
[INFO] [talledLocalContainer]   at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24) [applinks-plugin-5.2.2_1472687958000.jar:na]
[INFO] [talledLocalContainer]   at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24) [applinks-plugin-5.2.2_1472687958000.jar:na]
[INFO] [talledLocalContainer]   at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24) [applinks-plugin-5.2.2_1472687958000.jar:na]
[INFO] [talledLocalContainer]   at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24) [applinks-plugin-5.2.2_1472687958000.jar:na]
[INFO] [talledLocalContainer]   at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24) [applinks-plugin-5.2.2_1472687958000.jar:na]
[INFO] [talledLocalContainer]   at com.atlassian.analytics.client.filter.UniversalAnalyticsFilter.doFilter(UniversalAnalyticsFilter.java:92) [analytics-client-5.2.9_1472687958000.jar:na]
[INFO] [talledLocalContainer]   at com.atlassian.analytics.client.filter.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:39) [analytics-client-5.2.9_1472687958000.jar:na]
[INFO] [talledLocalContainer]   at com.atlassian.labs.httpservice.resource.ResourceFilter.doFilter(ResourceFilter.java:59) [httpservice-bridge-0.6.2.jar:na]
[INFO] [talledLocalContainer]   at com.atlassian.plugin.connect.plugin.auth.scope.ApiScopingFilter.doFilter(ApiScopingFilter.java:81) [atlassian-connect-plugin-1.1.86-bitbucket-04.jar:na]
[INFO] [talledLocalContainer]   at com.atlassian.stash.internal.spring.security.StashAuthenticationFilter.doFilter(StashAuthenticationFilter.java:88) [classes/:na]
[INFO] [talledLocalContainer]   at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doInsideSpringSecurityChain(BeforeLoginPluginAuthenticationFilter.java:109) [classes/:na]
[INFO] [talledLocalContainer]   at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:75) [classes/:na]
[INFO] [talledLocalContainer]   at com.atlassian.security.auth.trustedapps.filter.TrustedApplicationsFilter.doFilter(TrustedApplicationsFilter.java:94) [atlassian-trusted-apps-core-4.2.0.jar:na]
[INFO] [talledLocalContainer]   at com.atlassian.oauth.serviceprovider.internal.servlet.OAuthFilter.doFilter(OAuthFilter.java:67) [atlassian-oauth-service-provider-plugin-2.0.3_1472687958000.jar:na]
[INFO] [talledLocalContainer]   at com.atlassian.core.filters.ServletContextThreadLocalFilter.doFilter(ServletContextThreadLocalFilter.java:21) [atlassian-core-4.6.19.jar:na]
[INFO] [talledLocalContainer]   at com.atlassian.core.filters.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:31) [atlassian-core-4.6.19.jar:na]
[INFO] [talledLocalContainer]   at com.atlassian.plugin.connect.plugin.auth.user.ThreeLeggedAuthFilter.doFilter(ThreeLeggedAuthFilter.java:109) [atlassian-connect-plugin-1.1.86-bitbucket-04.jar:na]
[INFO] [talledLocalContainer]   at com.atlassian.fastdev.AutoReloadFilter.doFilter(AutoReloadFilter.java:63) [fastdev-plugin-2.6_1509006308867.jar:na]
[INFO] [talledLocalContainer]   at com.atlassian.jwt.internal.servlet.JwtAuthFilter.doFilter(JwtAuthFilter.java:32) [jwt-plugin-1.5.11-0002_1472687958000.jar:na]
[INFO] [talledLocalContainer]   at com.atlassian.analytics.client.filter.DefaultAnalyticsFilter.doFilter(DefaultAnalyticsFilter.java:38) [analytics-client-5.2.9_1472687958000.jar:na]
[INFO] [talledLocalContainer]   at com.atlassian.analytics.client.filter.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:39) [analytics-client-5.2.9_1472687958000.jar:na]
[INFO] [talledLocalContainer]   at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doBeforeBeforeLoginFilters(BeforeLoginPluginAuthenticationFilter.java:87) [classes/:na]
[INFO] [talledLocalContainer]   at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:73) [classes/:na]
[INFO] [talledLocalContainer]   at com.atlassian.stash.internal.request.DefaultRequestManager.doAsRequest(DefaultRequestManager.java:86) ~[bitbucket-service-impl-4.9.1.jar:na]
[INFO] [talledLocalContainer]   at com.atlassian.stash.internal.hazelcast.ConfigurableWebFilter.doFilter(ConfigurableWebFilter.java:38) ~[classes/:na]
[INFO] [talledLocalContainer]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_144]
[INFO] [talledLocalContainer]   at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_144]
[INFO] [talledLocalContainer]   ... 216 frames trimmed
[INFO] [talledLocalContainer] Caused by: com.sun.jersey.api.container.ContainerException: The ResourceConfig instance does not contain any root resource classes.
[INFO] [talledLocalContainer]   at com.sun.jersey.server.impl.application.RootResourceUriRules.<init>(RootResourceUriRules.java:99) ~[atlassian-rest-module-3.0.14_1472687956000.jar:na]
[INFO] [talledLocalContainer]   at com.atlassian.util.concurrent.LazyReference$Sync.run(LazyReference.java:325) ~[atlassian-util-concurrent-3.0.0.jar:na]
[INFO] [talledLocalContainer]   at com.atlassian.util.concurrent.LazyReference.getInterruptibly(LazyReference.java:143) ~[atlassian-util-concurrent-3.0.0.jar:na]
[INFO] [talledLocalContainer]   ... 29 common frames omitted`

Can someone explain why this happens if I add telegrambots and how I can fix this problem?

**Comment by rubenlagus** [comment]
I don't see any relation between this error and the library.
