### ISSUE TITLE
Why SendMessage does not implement equals() and hashCode()?

### ISSUE THREAD

**Issue by rustamzh** [rubenlagus/TelegramBots#325]
I was writing tests for the bot, checking the output and found out that there is no equals() and hashCode() method. So I would need to use refEq from Mockito framework to pass the test. Is there a particular reason not to implement equals() and hashCode() methods?

**Comment by rubenlagus** [comment]
I didn't need such a methods at the moment. Be my guest to create a pull request with them and I'll merge them.
