### ISSUE TITLE
Get Message ID from bot's message

### ISSUE THREAD

**Issue by Nicot3** [rubenlagus/TelegramBots#343]
Is possible to get the ID before sending it, because i have enabled the privacy mode, so i can't get the latest message from a chat

Any possible solution?

**Comment by Clevero** [comment]
If you send a message, you get a Message object as a return wich is containing the message_id

**Comment by Nicot3** [comment]
How is the methot? I can't find it

**Comment by Clevero** [comment]
you just send the message and as a return you get the Message object. Like sending normally the message

example:

```java
SendMessage sm = new SendMessage();
//add chat_id and text
Message mes = execute(sm);
```

**Comment by Nicot3** [comment]
So, an example for saving the message id can be something like that?
```javascript
SendMessage msj= new SendMessage();

int mid;
msj.setChatID();
msj.setText();
try {
Message mes = execute(msj);
mid = mes.getMessageId();
}
catch (TelegramApiException e) {
            }
```
PS: I tried to define Message out of the try, but message object needs a throw exception

**Comment by Clevero** [comment]
Don't have tested the code, but should be.

Yes, ```execute()``` is throwing an exception

**Comment by Nicot3** [comment]
Okay, the code i used above is working fine, thanks for the help @Clevero
