### ISSUE TITLE
how can i make a simple fucking telegram bot!!

### ISSUE THREAD

**Issue by SaeidDavoody** [rubenlagus/TelegramBots#345]
where the fuck is  org.telegram.telegrambots!!!
if you change something , you should change documentation of it!!!

**Comment by Clevero** [comment]
Please, don't get rude. The more you are rude, the more likely it is that nobody is answering you...

Did you went through the wiki? especially "Getting Started"?
Did you imported the .jar(s) via maven, gradle or by hand?

**Comment by SaeidDavoody** [comment]
:) I was just kidding , yeah of course i read wiki and examples , i added the jar by hand in intelijIdea and in the jar file tree there is no telegrambots folder in telegram folder 
i think that they changed many things and now i don't know how to create a bot with this ....

**Comment by SaeidDavoody** [comment]
i think i got a mistake , i will try to see it resolved or not... thanks

**Comment by SaeidDavoody** [comment]
i was an idiot , excuse me :/

**Comment by Clevero** [comment]
xD
