### ISSUE TITLE
Add proxy connection to BotSession

### ISSUE THREAD

**Issue by zipangulu** [rubenlagus/TelegramBots#349]
It's possible to create a BotSession using a proxy (host, port, user and password for authentication)?

**Comment by addo37** [comment]
Yes, you may specify a RequestConfig with the proxy address.

[BotSession](https://github.com/rubenlagus/TelegramBots/blob/master/telegrambots-meta/src/main/java/org/telegram/telegrambots/generics/BotSession.java) -> [BotOptions](https://github.com/rubenlagus/TelegramBots/blob/master/telegrambots/src/main/java/org/telegram/telegrambots/bots/DefaultBotOptions.java) -> RequestConfig

Let us know if you still can't figure it out. I'll add a simple snippet. Cheers!

**Comment by kagari2613** [comment]
@addo37  i set a proxy and can receive messages from my bot but can't reply, method execute (send Message) still unknown host api.telegram.org

**Comment by bvn13** [comment]
@kagari2613 try to inherit options from DefaultBotOptions

**Comment by bvn13** [comment]
proxy support added since 3.6.1.

issue should be closed
