### ISSUE TITLE
Pleas update for bot api 2

### ISSUE THREAD

**Issue by nabeghe** [rubenlagus/TelegramBots#35]
hi
pleas update for bot api 2

**Comment by Clevero** [comment]
This is already updated for API version 2.
@rubenlagus pushed the support for the new API version right after the new API specification were official released

**Comment by rubenlagus** [comment]
@nabeghe The update for bots api 2.0 was pushed to the dev branch (and merged to master) just 20 minutes after official Bot API 2.0 release. As @Clevero suggested, have a look to releases ;)
