### ISSUE TITLE
Please fix Wiki page 

### ISSUE THREAD

**Issue by bvn13** [rubenlagus/TelegramBots#352]
Page Simple Ability Bot contains dependency of plugin:

> compile group: 'org.telegram', name: 'telegrambots-**abilties**', version: '3.5'

please, look at the error: telegrambots-abilties -> abilties -> LT

fix it with: compile group: 'org.telegram', name: 'telegrambots-**abilities**', version: '3.5'

**Comment by addo37** [comment]
A PR #347 is already pending. Thanks for the notice though!

**Comment by rubenlagus** [comment]
This should be already merged and fixed.
