### ISSUE TITLE
How to use Abilities?

### ISSUE THREAD

**Issue by bvn13** [rubenlagus/TelegramBots#353]
Wiki is so cut for me, so I cann't understand where to place Ability-construction method.

Could you give me a full working example?

I tried to place the method described into the Wiki
`public Ability sayHelloWorld() {
    return Ability
              .builder()
              .name("hello")
              .info("says hello world!")
              .locality(ALL)
              .privacy(PUBLIC)
              .action(ctx -> silent.send("Hello world!", ctx.chatId()))
              .build();
}`

as a method of my class extended of TelegramLongPollingBot like this:
`public class TelegramBot extends TelegramLongPollingBot {

        private static Logger logger = LoggerFactory.getLogger(TelegramBot.class);

        private TelegramBotManager manager;
        private String name;
        private String token;
        private String masterName;

        public TelegramBot(TelegramBotManager manager, String name, String token, String masterName) {
            this.manager = manager;
            this.name = name;
            this.token = token;
            this.masterName = masterName;
        }

        public Ability sayHelloWorld() {
            return Ability
                    .builder()
                    .name("hello")
                    .info("says hello world!")
                    .locality(ALL)
                    .privacy(PUBLIC)
                    .action(ctx -> {
                        try {
                            this.send("Hello world!", ctx.chatId());
                        } catch (TelegramApiException e) {
                            e.printStackTrace();
                        }
                    })
                    .build();
        }

        @Override
        public void onUpdateReceived(Update update) {
            // We check if the update has a message and the message has text
            if (update.hasMessage() && update.getMessage().hasText()) {
                logger.debug("CHAT ID: "+update.getMessage().getChatId().toString()+" / MESSAGE: "+update.getMessage().getText());
                SendMessage message = new SendMessage() // Create a SendMessage object with mandatory fields
                        .setChatId(update.getMessage().getChatId())
                        .setText(update.getMessage().getText());
                try {
                    execute(message); // Call method to send the message
                } catch (TelegramApiException e) {
                    e.printStackTrace();
                }
            }
        }

        @Override
        public void onUpdatesReceived(List<Update> updates) {
            super.onUpdatesReceived(updates);
        }

        @Override
        public String getBotUsername() {
            return this.name;
        }

        @Override
        public String getBotToken() {
            return this.token;
        }

        public void send(String message, Long chatId) throws TelegramApiException {
            SendMessage sm = new SendMessage();
            sm.setChatId(chatId);
            sm.enableMarkdown(true);
            sm.enableWebPagePreview();
            sm.setText(message);
            this.execute(sm);
        }
    }`

but it does not answer 'hello world' on either 'hello' or '/hello'.

What did I wrong?

**Comment by addo37** [comment]
Hey @bvn13! We're glad you're trying to use AbilityBot.

In order to use abilities, your bot must extend AbilityBot! It is mentioned as the first section in the[ simple example ](https://github.com/rubenlagus/TelegramBots/wiki/Simple-Example)

Once your class extends AbilityBot (which itself extends TelegramLongPollingBot), then you'll be able to declare and use abilities.

Lemme know if you face anymore issues. Thanks!

**Comment by bvn13** [comment]
@addo37 Thanks you for explanations. I've created full simple work example: https://github.com/bvn13/SimpleTelegramAbilityBot

You could provide a link to my repo into docs page https://github.com/rubenlagus/TelegramBots/wiki/Simple-Example

**Comment by addo37** [comment]
The wiki already references a full [implementation](https://github.com/addo37/ExampleBots/blob/master/src/main/java/org/telegram/examplebots/HelloBot.java). Thanks though!
