### ISSUE TITLE
Wiki Maven

### ISSUE THREAD

**Issue by ruslan1071995** [rubenlagus/TelegramBots#355]
Hello! You have typo in maven dependency in Wiki page.
See screenshot 
![export](https://user-images.githubusercontent.com/10988334/34327072-c141667c-e8ed-11e7-85a6-5c6831c707b1.png)

**Comment by addo37** [comment]
A PR #347 is already pending. Thanks for the notice though!

**Comment by rubenlagus** [comment]
Should be already merged and fixed
