### ISSUE TITLE
How to access an old message from the chat?

### ISSUE THREAD

**Issue by fran-mv** [rubenlagus/TelegramBots#356]
Hello, I would like to access a specific message in a supergroup to edit it and copy it. Is there any method to get the text of a message through its messageid for example?

Thx.

**Comment by addo37** [comment]
I don't believe there is. I made a bot a few months ago that keeps track of message edits. I used an embedded DB and saved the last X number of messages (with their IDs and all) to keep track of.

Once a message is received by the bot, it's dropped from the server-side. Your bot must handle it in a clever manner.

**Comment by fran-mv** [comment]
Yes, I disabled the privacy mode for my bot but anyway the text of every message when I restart it is always null :(

Thanks for your answer ;).

**Comment by matiniamirhossein** [comment]
@fran-mv I don't know if you are interested or not but you can try the telegram api (not bot api).
Libraries:
Java:
https://github.com/rubenlagus/TelegramApi (By author of this repository)

Python:
https://github.com/LonamiWebs/Telethon (By another author)
