### ISSUE TITLE
Ability bot does not answer in a supergroup

### ISSUE THREAD

**Issue by falc0n33** [rubenlagus/TelegramBots#359]
Hi everyone, i have a trouble with Ability bot. Locality of bot is "ALL", when i send /hello in chat or supergroup with bot it answer me, but when i send /hello@mybotname from suggestions in a supergroup it is silent. How to fix it?

**Comment by addo37** [comment]
Have you supplied the username (correctly) to the bot in-code?

**Comment by falc0n33** [comment]
Yes, i am write there random symbols. My fault, change them to correct name. Now it works! Thank you very much and Happy New Year!

**Comment by addo37** [comment]
Great! ^^

Have fun and Happy New Year!
