### ISSUE TITLE
Cannot download picture

### ISSUE THREAD

**Issue by falc0n33** [rubenlagus/TelegramBots#360]
I need to download picture via bot. I got the path to it, then i used downloadFile(<path>) method and then got java.io.File. But from it i got image with 90x90 resolution. When i opened link in my browser - https://api.telegram.org/file/bot<token>/<file_path>, smth like that but with my parameters, i got error (cannot display image because it contains errors). How to fix this problem?

**Comment by rubenlagus** [comment]
When you get a Message with a photo (https://core.telegram.org/bots/api#message) you will receive several sizes, make sure you are downloading the one with the biggest size to get the higher resolution.
