### ISSUE TITLE
 how to create a button InlineKeyboardButton

### ISSUE THREAD

**Issue by ptzumba** [rubenlagus/TelegramBots#363]
I do not know how to speak English, but come on.
Does anyone have any examples of creating an inline button with the InlineKeyboardButton function?

**Comment by Clevero** [comment]
There is a book referenced in the wiki that has also in a chapter that is discussing InlineKeyboards
https://monsterdeveloper.gitbooks.io/writing-telegram-bots-on-java/content/lesson-6.-inline-keyboards-and-editing-message%27s-text.html

In the Example repository is also a example bot that is using InlineKeyboardButtons
https://github.com/rubenlagus/TelegramBotsExample/blob/master/src/main/java/org/telegram/updateshandlers/ElektrollArtFanHandler.java



Feel free to join our [chat group](https://telegram.me/JavaBotsApi) if you have further questions or ask here on GitHub :)

**Comment by Clevero** [comment]
@ptzumba is your question solved?
If yes, please close the issue.
