### ISSUE TITLE
Error AbilityBot - NoClassDefFoundError LongArrayList

### ISSUE THREAD

**Issue by BlackRose01** [rubenlagus/TelegramBots#365]
Hello there,

I've got a problem with starting my AbilityBot. When I try to start the code below I get the following error. Even the ExampleBot doesn't work. The TelegramBot-Package is from Maven in Version 3.5.

`Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/collections/impl/list/mutable/primitive/LongArrayList
	at org.mapdb.StoreDirectAbstract.<init>(StoreDirectAbstract.kt:41)
	at org.mapdb.StoreWAL.<init>(StoreWAL.kt:31)
	at org.mapdb.StoreWAL$Companion.make(StoreWAL.kt:56)
	at org.mapdb.StoreWAL$Companion.make$default(StoreWAL.kt:55)
	at org.mapdb.DBMaker$Maker.make(DBMaker.kt:464)
	at org.telegram.abilitybots.api.db.MapDBContext.onlineInstance(MapDBContext.java:57)
	at org.telegram.abilitybots.api.bot.AbilityBot.<init>(AbilityBot.java:149)
	at Gaia.Nereide.Telegram.<init>(Telegram.java:41)
	at Gaia.Nereide.Telegram.<init>(Telegram.java:51)
	at Gaia.Nereide.Start.main(Start.java:13)`

Here is my code:

`import org.telegram.abilitybots.api.bot.AbilityBot;
import org.telegram.abilitybots.api.objects.Ability;

import static org.telegram.abilitybots.api.objects.Locality.ALL;
import static org.telegram.abilitybots.api.objects.Privacy.PUBLIC;

public class ExampleBot extends AbilityBot {
  public static final String BOT_TOKEN = "BOT_TOKEN";
  public static final String BOT_USERNAME = "BOT_USERNAME";

  public ExampleBot() {
    super(BOT_TOKEN, BOT_USERNAME);
  }

  @Override
  public int creatorId() {
    return 123456789;
  }

  public Ability sayHelloWorld() {
    return Ability
        .builder()
        .name("hello")
        .info("says hello world!")
        .locality(ALL)
        .privacy(PUBLIC)
        .action(ctx -> silent.send("Hello world!", ctx.chatId()))
        .build();
  }
}`

I can't find any solution for this problem. Where is the problem?

Thank you.

**Comment by addo37** [comment]
How exactly are you building your dependencies? Are you using jar files or compiling via Maven/Gradle?

**Comment by BlackRose01** [comment]
I compile via Maven.

**Comment by addo37** [comment]
Can you supply me the full source code of your sample project so that I can reproduce the issue?

**Comment by Fricofresh** [comment]
I think you don't have the AbilityBot dependancy.
Do you have the following code in your pom.xml?

<dependency>
        <groupId>org.telegram</groupId>
        <artifactId>telegrambots-abilities</artifactId>
        <version>3.5</version>
</dependency>

I haven't checked if this would work but it could help you.

**Comment by BlackRose01** [comment]
@Fricofresh This is the package I use from Maven. I also tried the compiled jar with all dependencies.

This is my code:

`
import com.google.common.annotations.VisibleForTesting;
import org.glassfish.hk2.api.Visibility;
import org.telegram.abilitybots.api.bot.AbilityBot;
import org.telegram.abilitybots.api.objects.Ability;
import org.telegram.abilitybots.api.sender.MessageSender;
import org.telegram.telegrambots.api.objects.Message;
import org.telegram.telegrambots.api.objects.Update;

import java.util.Map;
import java.util.function.Predicate;

import static org.telegram.abilitybots.api.objects.Flag.*;
import static org.telegram.abilitybots.api.objects.Locality.ALL;
import static org.telegram.abilitybots.api.objects.Locality.USER;
import static org.telegram.abilitybots.api.objects.Privacy.ADMIN;
import static org.telegram.abilitybots.api.objects.Privacy.PUBLIC;

public class ExampleBot extends AbilityBot {

  public static final String BOT_TOKEN = "BOT_TOKEN ";
  public static final String BOT_USERNAME = "BOT_USERNAME ";

  public ExampleBot() {
    super(BOT_TOKEN, BOT_USERNAME);
  }

  @Override
  public int creatorId() {
    return 1337; // Your ID here
  }

  public Ability saysHelloWorld() {
    return Ability
    		.builder()
        .name("hello") // Name and command (/hello)
        .info("Says hello world!") // Necessary if you want it to be reported via /commands
        .privacy(PUBLIC)  // Choose from Privacy Class (Public, Admin, Creator)
        .locality(ALL) // Choose from Locality enum Class (User, Group, PUBLIC)
        .input(0) // Arguments required for command (0 for ignore)
        .action(ctx -> {
          // Custom sender implementation
        	silent.send("Hello World!", ctx.chatId());
        })
        .build();
  }

  public Ability saysHelloWorldToFriend() {
    return Ability.builder()
        .name("sayhi")
        .info("Says hi")
        .privacy(PUBLIC)
        .locality(USER)
        .input(1)
        .action(ctx -> silent.send("Hi " + ctx.firstArg(), ctx.chatId()))
        .build();
  }


  public Ability scaredOfAdmins() {
    return Ability.builder()
        .name("scared")
        .info("Makes me scared of admins!")
        .privacy(ADMIN)
        .locality(ALL)
        .input(0)
        .action(ctx -> {
          // Custom sender implementation
        	silent.send("Eeeeek, I'm so sorry your highness!", ctx.chatId());
        })
        .post(ctx -> {
          // This "post" action is executed after the main action is done
          silent.send("I will never do it again!", ctx.chatId());
        })
        .build();
  }


  @Override
  public boolean checkGlobalFlags(Update update) {
    return true;
  }


  public Ability sayNiceToPhoto() {
    return Ability.builder()
        .name(DEFAULT) // DEFAULT ability is executed if user did not specify a command -> Bot needs to have access to messages (check FatherBot)
        .flag(PHOTO)
        .privacy(PUBLIC)
        .locality(ALL)
        .input(0)
        .action(ctx -> silent.send("Daaaaang, what a nice photo!", ctx.chatId()))
        .build();
  }
  
  public Ability useDatabaseToCountPerUser() {
    return Ability.builder()
        .name("count")
        .info("Increments a counter per user")
        .privacy(PUBLIC)
        .locality(ALL)
        .input(0)
        .action(ctx -> {
          // db.getMap takes in a string, this must be unique and the same everytime you want to call the exact same map
          // TODO: Using integer as a key in this db map is not recommended, it won't be serialized/deserialized properly if you ever decide to recover/backup db
          Map<String, Integer> countMap = db.getMap("COUNTERS");
          int userId = ctx.user().id();

          // Get and increment counter, put it back in the map
          Integer counter = countMap.compute(String.valueOf(userId), (id, count) -> count == null ? 1 : ++count);

          // Send formatted will enable markdown
          String message = String.format("%s, your count is now *%d*!", ctx.user().shortName(), counter);
          silent.sendMd(message, ctx.chatId());
        })
        .build();

    // In this ability, you can also experiment with /backup and /recover of the AbilityBot!
    // Take a backup of when the counter is at 1, do /count multiple times and attempt to recover
    // The counter will be reset since the db will recover to the backup that you specify
  }

  public Ability playWithMe() {
    String playMessage = "Play with me!";

    return Ability.builder()
        .name("play")
        .info("Do you want to play with me?")
        .privacy(PUBLIC)
        .locality(ALL)
        .input(0)
        .action(ctx -> silent.forceReply(playMessage, ctx.chatId()))
        // The signature of a reply is -> (Consumer<Update> action, Predicate<Update>... conditions)
        // So, we  first declare the action that takes an update (NOT A MESSAGECONTEXT) like the action above
        // The reason of that is that a reply can be so versatile depending on the message, context becomes an inefficient wrapping
        .reply(upd -> {
              // Prints to console
              System.out.println("I'm in a reply!");
              // Sends message
              silent.send("It's been nice playing with you!", upd.getMessage().getChatId());
            },
            // Now we start declaring conditions, MESSAGE is a member of the enum Flag class
            // That class contains out-of-the-box predicates for your replies!
            // MESSAGE means that execute the reply if it has a message
            MESSAGE,
            // REPLY means that the update must be a reply
            REPLY,
            // The reply must be to the bot
            isReplyToBot(),
            // The reply is to the playMessage
            isReplyToMessage(playMessage)
        )
        // You can add more replies by calling .reply(...)
        .build();
  }

  private Predicate<Update> isReplyToMessage(String message) {
    return upd -> {
      Message reply = upd.getMessage().getReplyToMessage();
      return reply.hasText() && reply.getText().equalsIgnoreCase(message);
    };
  }

  private Predicate<Update> isReplyToBot() {
    return upd -> upd.getMessage().getReplyToMessage().getFrom().getUserName().equalsIgnoreCase(getBotUsername());
  }

  @VisibleForTesting
  void setSender(MessageSender sender) {
    this.sender = sender;
  }
}
`

**Comment by BlackRose01** [comment]
I also tested from add37 the examplebots but I get the same error.

https://github.com/addo37/ExampleBots/tree/master/src/main/java/org/telegram/examplebots

Start:
https://github.com/addo37/ExampleBots/blob/master/src/main/java/org/telegram/examplebots/Application.java

HelloBot:
https://github.com/addo37/ExampleBots/blob/master/src/main/java/org/telegram/examplebots/HelloBot.java

**Comment by addo37** [comment]
Any updates for this issue @BlackRose01? Otherwise, I'll work on exploring the issue. It still believe it's a packaging/DM issue.

**Comment by BlackRose01** [comment]
Hello @addo37, I tried some code snippets and I figured out that the ApiContextInitializer also have to initialize. I thought that it must not be implement. So I think the problem is solved but I forgot to close this topic. Thank you for the reply.
