### ISSUE TITLE
execute shell command

### ISSUE THREAD

**Issue by marcopaggioro** [rubenlagus/TelegramBots#366]
Hi, I can not find the help page for this framework. How do I execute a shell command and capture the output? I would like to do vcgencmd measure_temp

**Comment by Clevero** [comment]
You can find very useful informationen about this library in the wiki
https://github.com/rubenlagus/TelegramBots/wiki

Executing a shell command is not handled by this library as this is just a library for the Telegram Bots API

**Comment by Chase22** [comment]
Executing Commands on the Server is not part of the Libary. As @Clevero already pointed out.
You can use the [ProcessBuilder Class](https://docs.oracle.com/javase/7/docs/api/java/lang/ProcessBuilder.html) for that

**Comment by Chase22** [comment]
@marcopaggioro Please close if the issue was resolved
