### ISSUE TITLE
parameter type in deletemessage.setChatId() method

### ISSUE THREAD

**Issue by ahmadsl** [rubenlagus/TelegramBots#368]
hi,
chatId is a Long type variable. in other method setChatId, parameter is implemented as Long variable, but in DeleteMessage class implemented as String variable.
thanks to fix it.

**Comment by kharkovsky** [comment]
You can "wrap" `Long chatId` with `String.valueOf(chatId)` and it will be executed properly. 
It сan come in handy as a temporary solution.

**Comment by xTheDoctah** [comment]
deleteMessage(new DeleteMessage ( chat_id,(int) (long) message_id));
chat_id and message_id are both long values. 
U can pick them in a message or call back query case;
Sorrounded by try and catch. Pretty much easy. 
Don't use setChatId and setMessageId , just pass the args to the class. without any methods. Btw if u wanna use the set method. use the set methods is pretty much longer than this -> deleteMessage(new DeleteMessage(chat_id,(int) (long) message_id));

**Comment by rubenlagus** [comment]
It is an String because it can also be an username. In any case, I added a new setter that accept Long to make it easier.
