### ISSUE TITLE
bot开发中回调地址设置得腾讯云服务器，一直显示连接不上

### ISSUE THREAD

**Issue by 401825317** [rubenlagus/TelegramBots#372]
是不是必须得用海外得服务器啊？

**Comment by Clevero** [comment]
Would you please be so kind and ask your question in english?
So that we can understand what your question is and are able to help you :)
Also it would help to keep track of issues and comments for future improvements.

**Comment by 401825317** [comment]
In the development of BOT, the callback address is set up by China's Tencent's cloud server. When I use ngrok intranet, I can receive callback information, but I can't connect it to my own server. The wrong information is as follows:
{"OK": true, "result": {"URL": "https://test.ecomchain.io/telegram", "has_custom_certificate": false, "pending_update_count": 6, "last_error_date": 1517399078, "last_error_message": "Connection" and "X").

**Comment by 401825317** [comment]
{"ok":true,"result":{"url":"https://test.ecomchain.io/telegram","has_custom_certificate":false,"pending_update_count":6,"last_error_date":1517399078,"last_error_message":"Connection refused","max_connections":40}}

**Comment by 401825317** [comment]
@Clevero

**Comment by fireyang** [comment]
估计是封了ip了，我的也是这样。。。

**Comment by rubenlagus** [comment]
@401825317 That error you showed is a configuration problem of your server, here you can find some ideas: https://stackoverflow.com/questions/2333400/what-can-be-the-reasons-of-connection-refused-errors

**Comment by shinohara-rin** [comment]
我认为是某防火墙的原因
I think the great firewall is blocking the connection

改用LongPolling+Proxy吧

**Comment by rubenlagus** [comment]
In that case, I guess we can close this issue. Nothing I can do with the great firewall, sorry.
