### ISSUE TITLE
How to get chat id without update method? 

### ISSUE THREAD

**Issue by GalaxyLion** [rubenlagus/TelegramBots#383]
Hello, how I can chat id withot update method? I want to send messages at a certain interval. But I can get chat only with update.getMessage().getChatId().

**Comment by Chase22** [comment]
You'll have to save the chat ID you want to send the message to into a file or database. Currently there's no way of determining which chats the bot is part of or to get the chat ID by name.

**Comment by Clevero** [comment]
@GalaxyLion is your question solved?
If yes, please close the issue.
