### ISSUE TITLE
3.6 version have not TelegramLongPollingBot class

### ISSUE THREAD

**Issue by IvanDeveloper84** [rubenlagus/TelegramBots#388]
![2018-02-16_02-04-40](https://user-images.githubusercontent.com/28867921/36275568-c7e058ea-12bd-11e8-9137-53790c4c970c.jpg)
3.5 ok

**Comment by rubenlagus** [comment]
![image](https://user-images.githubusercontent.com/2874352/36301391-edc832de-1304-11e8-94d1-e02594f7f19e.png)

The file is not in meta package, it it in "telegrambots" package

**Comment by IvanDeveloper84** [comment]
I don't understand how to find this class.
If i change version 3.5 - maven load 2 lib 
but for 3.6 - 1 lib
I made restart idea - did't work
![2018-02-16_18-48-11](https://user-images.githubusercontent.com/28867921/36306434-474d25ae-134a-11e8-9551-44ae7b4888a2.jpg)
![2018-02-16_18-47-28](https://user-images.githubusercontent.com/28867921/36306435-4771fe24-134a-11e8-8044-966cc7c58e09.jpg)
