### ISSUE TITLE
[Bot Ability] GROUP_ADMIN privacy doesn't work in supergroups.

### ISSUE THREAD

**Issue by EricS07** [rubenlagus/TelegramBots#390]
The privacy for **GROUP_ADMIN** works only in normal groups.
I found the problem inside
`    public static boolean isGroupUpdate(Update update) {
return Flag.MESSAGE.test(update)?update.getMessage().isGroupMessage():(Flag.CALLBACK_QUERY.test(update)?update.getCallbackQuery().getMessage().isGroupMessage():(Flag.CHANNEL_POST.test(update)?update.getChannelPost().isGroupMessage():(Flag.EDITED_CHANNEL_POST.test(update)?update.getEditedChannelPost().isGroupMessage():(Flag.EDITED_MESSAGE.test(update)?update.getEditedMessage().isGroupMessage():false))));
    }`
which is called by isGroupAdmin() of AbilityBot class. This function checks only if is a group update and not if is a supergroupones.

**Comment by EricS07** [comment]
I've fixed the bug by editing isGroupAdmin function in "AbilityBot" class to:
`    private boolean isGroupAdmin(Update update, int id) {
        GetChatAdministrators admins = (new GetChatAdministrators()).setChatId(AbilityUtils.getChatId(update));
        return AbilityUtils.isSuperGroupUpdate(update) && ((ArrayList)this.silent.execute(admins).orElse(new ArrayList())).stream().anyMatch((member) -> {
            return member.getUser().getId().intValue() == id;
        }) || AbilityUtils.isGroupUpdate(update) && ((ArrayList)this.silent.execute(admins).orElse(new ArrayList())).stream().anyMatch((member) -> {
            return member.getUser().getId().intValue() == id;
        });
    }`

Adding then the method "isSuperGroupUpdate" to AbilityUtils class. That's the code:
`    public static boolean isSuperGroupUpdate(Update update) {
        return Flag.MESSAGE.test(update)?update.getMessage().isSuperGroupMessage():(Flag.CALLBACK_QUERY.test(update)?update.getCallbackQuery().getMessage().isSuperGroupMessage():(Flag.CHANNEL_POST.test(update)?update.getChannelPost().isSuperGroupMessage():(Flag.EDITED_CHANNEL_POST.test(update)?update.getEditedChannelPost().isSuperGroupMessage():(Flag.EDITED_MESSAGE.test(update)?update.getEditedMessage().isSuperGroupMessage():false))));
    }`
Hope it helps.

**Comment by rubenlagus** [comment]
@addo37 Can you have a look?
