### ISSUE TITLE
How to edit a Inline Keyboard Message Multiple times? (EditMessageReplyMarkup)

### ISSUE THREAD

**Issue by ahooee** [rubenlagus/TelegramBots#396]
Is there any way to edit an inline keyboard message multiple times?

I tried to run the following code in a  loop statement

`if(update.hasCallbackQuery()){
	        	String call_data = update.getCallbackQuery().getData();
	            long message_id = update.getCallbackQuery().getMessage().getMessageId();
	            long chat_id = update.getCallbackQuery().getMessage().getChatId();
	            String inline_message_id = update.getCallbackQuery().getInlineMessageId();
	            if (call_data.equals(i+"up")) {
	                EditMessageReplyMarkup new_message = new EditMessageReplyMarkup()
	                        .setChatId(chat_id).setMessageId(toIntExact(message_id))
	                        .setInlineMessageId(inline_message_id);
	                InlineKeyboardButton dk1=new InlineKeyboardButton();
	                dk1.setText(i+"up");
;                       dk1.setCallbackData(k+"up");
	                InlineKeyboardMarkup markupInline = new InlineKeyboardMarkup();
	                List<List<InlineKeyboardButton>> rowsInline = new ArrayList<>();
	                List<InlineKeyboardButton> rowInline = new ArrayList<>();
        	         rowInline.add(dk1);
	                rowsInline.add(rowInline);
                        markupInline.setKeyboard(rowsInline);
	                new_message.setReplyMarkup(markupInline);
                        try {editMessageReplyMarkup(new_message);
                        } catch (TelegramApiException e) {
	                    e.printStackTrace();
	                }
	                `
	                `
But the code  run only once and i got this error:

`org.telegram.telegrambots.exceptions.TelegramApiRequestException: Error editing message reply markup: [400] Bad Request: message is not modified
	at org.telegram.telegrambots.api.methods.updatingmessages.EditMessageReplyMarkup.deserializeResponse(EditMessageReplyMarkup.java:111)
	 at org.telegram.telegrambots.bots.DefaultAbsSender.sendApiMethod(DefaultAbsSender.java:690)
	  at org.telegram.telegrambots.bots.AbsSender.editMessageReplyMarkup(AbsSender.java:206)
	   at javatelbot4.Myinkey.editinline1(Myinkey.java:83)
	    at javatelbot4.Inline1.onUpdateReceived(Inline1.java:30)
	      at java.util.ArrayList.forEach(ArrayList.java:1255)
	       at org.telegram.telegrambots.generics.LongPollingBot.onUpdatesReceived(LongPollingBot.java:27)
	        at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$HandlerThread.run(DefaultBotSession.java:311)`

**Comment by xTheDoctah** [comment]
Because he cannot find the message. Probably your code , set to every message sent or received another message id . So u have to make another var that u update every time with the id of the edited/sent message . I hope to be clear. Unfortunatly the english is not my first lang , so i hope u appreciate the effort.
E.G.:
`public void onUpdateReceived(Update update){
  if (update.hasMessage() && update.getMessage.hasText()){
   long message_id = update.getMessage().getMessageID();
     if(update.getMessage.getText().equals("/start"){
       // send message and keyboard stuff then u execute the message and store the var 
       long menu_id = update.getMessage.getMessageID();
      }
  }
}
`

**Comment by Clevero** [comment]
@ahooee 
You get the error message ````Bad Request: message is not modified```` if you try to modify a message but don't changed anything of the message.

**Comment by rubenlagus** [comment]
@Clevero is right, you should always make some modification if you don't want to get such an error. Closing since it is not something we can fix from here.
