### ISSUE TITLE
After 4 messages bot stop receiving/sending

### ISSUE THREAD

**Issue by ReedFlake** [rubenlagus/TelegramBots#4]
After 3~4 messages, bot stop responding (i'm created a debug for receiving-sending messages) and don't receive more messages.

**Comment by maratische** [comment]
Same problem

**Comment by Clevero** [comment]
do you have used polling (getUpdates) or webhook for receiving messages?

**Comment by maratische** [comment]
simple pooling
I think some problem with network and after app can not reconnect?
I have added many logging in UpdatesThread.java and restart service... waiting... :)

**Comment by Clevero** [comment]
I will try to reproduce it in the following days

**Comment by rubenlagus** [comment]
Not sure what can be happening, my bots have been running for a month at least without problem. Can you provide some error or more information ?

**Comment by maratische** [comment]
I found problem.
it was in line
response = httpclient.execute(httpPost);

Apache http client some time hang on long request

I created two bots. 1 buit from your master source code and 2 built from my code with fix.
5 days on small nettop (Atom processor, linux, java8).
1 - regular hang 
2 - stable work

https://github.com/maratische/TelegramBots/commit/b795c33d9074d4510e1e1098800c3e8916ff5416
