### ISSUE TITLE
Message has a flavor

### ISSUE THREAD

**Issue by xTheDoctah** [rubenlagus/TelegramBots#404]
I'm trying to understand how i can send a flavor with the message . But i dont really get it . Someone can help me ? Thanks in advance.

**Comment by Clevero** [comment]
What do you mean with flavor?
You mean like **bold** and _italic_?

**Comment by xTheDoctah** [comment]
Nope , look this video at 9.46 is a tutorial for a telegram python library [https://www.youtube.com/watch?v=OuVIe9vqkRE](here) as u can see there is a "pop-up" with a yeah written inside . I mean that when i talk about flavor :l .

**Comment by MouamleH** [comment]
When answering callbackQuery set the "show_alert" to true
https://core.telegram.org/bots/api#answercallbackquery

**Comment by xTheDoctah** [comment]
I'm talking about this Java Api . Not the telegram one .

**Comment by xTheDoctah** [comment]
Solved. Using                
`` AnswerCallbackQuery risposta  = new AnswerCallbackQuery()
                        .setShowAlert(true)
                        .setText("ciaoofsada")
                        .setCallbackQueryId(callback_queryID);`
