### ISSUE TITLE
deprecated Automatic enabling of cancellation of promises is deprecated.

### ISSUE THREAD

**Issue by Cyberpunk2027** [rubenlagus/TelegramBots#407]
In the future, you will have to enable it yourself.
See https://github.com/yagop/node-telegram-bot-api/issues/319. module.js:662:30

This code: `process.env["NTBA_FIX_319"] = 1;.` don't help me. Help me please!

**Comment by Clevero** [comment]
Has it anything todo with this library?
TelegramBots is written in java

**Comment by Cyberpunk2027** [comment]
@Clevero not only. Node.js, js too

**Comment by Cyberpunk2027** [comment]
@Clevero oh shit, i mixed up libraries... Thanks)

**Comment by Clevero** [comment]
xD

@Cyberpunk2027 Then please close this issue
