### ISSUE TITLE
Forward photo

### ISSUE THREAD

**Issue by Patatone** [rubenlagus/TelegramBots#408]
I want to make a simple bot that forward all photo. How can i forward a message? Thanks for the help :)

**Comment by Clevero** [comment]
https://core.telegram.org/bots/api#forwardmessage

This library is implementing all of the features of the offical Telegram Bot API. If it's in the offical documentation, it's available in this library
https://core.telegram.org/bots/api

**Comment by Clevero** [comment]
@Patatone is your question solved?
If yes, please close the issue.
