### ISSUE TITLE
Command API

### ISSUE THREAD

**Issue by lfdajr** [rubenlagus/TelegramBots#41]
Hello,

I'd like do suggest a command API to handle the commands issued in the platform in a decoupled way. It would work like this:

1. You register the commands your robot treat
2. For each command you create a class which handles that command accordingly
3. All the code will stay contained.

I have done this in my local copy, if you guys would like to see it, I could submit.

Regards.

**Comment by rubenlagus** [comment]
@lfdajr It would be great to have a look to it. Do you have it in a git for or something?

**Comment by Mit0x2** [comment]
See #76 where I suggested my version of the above mentioned 🙂

**Comment by rubenlagus** [comment]
I guess this one can be closed too, thanks @Mit0x2
