### ISSUE TITLE
where to find complete example?

### ISSUE THREAD

**Issue by peterremote1980** [rubenlagus/TelegramBots#419]
where to find complete example?

**Comment by Clevero** [comment]
Please see the example repo
https://github.com/rubenlagus/TelegramBotsExample
otherwise you are welcome to ask questions on how to to/implement something specific xD

**Comment by McPringle** [comment]
Based on the information from the wiki of this repo and additional sources I am in the process of creating a chatbot workshop. It is not finished yet but may still be useful for you:  https://github.com/McPringle/chatbot-workshop/blob/master/WORKSHOP.adoc

I guess it would take you about two hours to work through it. Any feedback is appreciated. Please use the issue section of my workshop for questions, suggestions etc.

**Comment by addo37** [comment]
> Based on the information from the wiki of this repo and additional sources I am in the process of creating a chatbot workshop. It is not finished yet but may still be useful for you: https://github.com/McPringle/chatbot-workshop/blob/master/WORKSHOP.adoc
If you're going to make a workshop with some of its material copy-pasted, then it would be proper to thank the original creators (Ruben, Clevero, Addo37, etc...). No offense intended.

**Comment by McPringle** [comment]
@addo37, sure, in the presentation there are already slides to honor the work of the authors of this library. The documentation on GitHub is work in progress. Links to this repo, the wiki and the authors will be mentioned there, too. Definitely!

**Comment by rubenlagus** [comment]
@McPringle You can also make a PR with this workshop in a new page of the wiki (https://github.com/rubenlagus/TelegramBots/tree/master/TelegramBots.wiki) and I can merge it directly to the wiki of the project (don't forget to use dev branch)

**Comment by addo37** [comment]
@peterremote1980, please close this issue if it has been resolved.
