### ISSUE TITLE
How to remotely execute ability from Java Web application?

### ISSUE THREAD

**Issue by ferrum1996** [rubenlagus/TelegramBots#421]
I have a Telegram bot that extends Ability Bot, and I want to send message (With ReplyKeyboard ) to a specific person (ChatId and UserId are known). How can I do it? I tried https request with the bot's token and ability's name, but i have received and error, no such method exists.

**Comment by addo37** [comment]
As mentioned in the group, Abilities are not exposed as ReST methods by default. If you want to do that, then you should do it explicitly, jax-rs/spring rest controller/jetty/any library with ReST capabilities.
