### ISSUE TITLE
Send Offline messages

### ISSUE THREAD

**Issue by Majestcx** [rubenlagus/TelegramBots#426]
Hi,
I'm using LongPoolingBot. Could I know how to send offline messages to my bot's users?

**Comment by Clevero** [comment]
What do you mean with "offline messages"?

If your bot sends a user a message, the message is sent regardless of the current state (onlline or offline) of the user.

**Comment by Majestcx** [comment]
Sorry, I mean if I save Chat IDs how I can send a broadcast to all users of bot even if they are offline?

**Comment by rubenlagus** [comment]
@Majestcx Quite probably, you will hit limits doing so: https://core.telegram.org/bots/faq#broadcasting-to-users
