### ISSUE TITLE
Uploading files

### ISSUE THREAD

**Issue by karimiehsan90** [rubenlagus/TelegramBots#428]
Hi
How can I upload file to telegram's server?
I know there are three ways to send files
One file_id
Two link that this doesn't work for my vps
Three upload
How can I do this?

**Comment by Clevero** [comment]
In the wiki is an example how to send a photo.

https://github.com/rubenlagus/TelegramBots/wiki/FAQ#how_to_send_photos

Should be similiar for other file types like Document and Audio

**Comment by Clevero** [comment]
@karimiehsan90 
Is your problem solved?
If yes, please close the issue
