### ISSUE TITLE
Incorrect filename after upload if it contains symbols(while the length of filename is too long)?

### ISSUE THREAD

**Issue by zzdjij** [rubenlagus/TelegramBots#440]
when I try the following code,
```
    SendDocument document = new SendDocument() // Create a SendMessage object with mandatory fields
        .setChatId(Field.CHAT_CHANNEL_ID)
        .setNewDocument(new File("C:/新建文本文档新建文本文档新建文本文档新建文本文档_[telegram]_good.txt"));

   bot.sendDocument(document);


    SendDocument document = new SendDocument() // Create a SendMessage object with mandatory fields
        .setChatId(Field.CHAT_CHANNEL_ID)
        .setNewDocument(new File("C:/新建文本_[telegram]_good.txt"));

    bot.sendDocument(document);
```

upload action works fine, but the filename was been changed...

![default](https://user-images.githubusercontent.com/38555434/39042007-6d7c3ab4-44bc-11e8-9494-4780e76c947c.png)

again, when I try rename file to "C:/新建文本文档新建文本文档新建文本文档新建文本文档建文本文档建文本文档建文本文档建文本文档_[telegram]_good.txt", it ends up with this:
![default](https://user-images.githubusercontent.com/38555434/39042024-781292c0-44bc-11e8-9d17-27d7ad6db234.png)

it almost lost most of the important information of the filename.

may be there is filename length limit? but I can't find any description about this... Is anywhere can figure out how filename convert while uploading file?
who can help me solve this out? thanks!

**Comment by rubenlagus** [comment]
@zzdjij What happen if you download the file again from the message you are showing in the screenshot? Does it still have the "..." in the downloaded file?

**Comment by zzdjij** [comment]
@rubenlagus nope, just same as the filename in the screenshot.

**Comment by rubenlagus** [comment]
@zzdjij The limit is in Telegram server side, it should be about 64 bytes as far as I know. Nothing I can do with the API to fix it.

**Comment by zzdjij** [comment]
yep, I do think so, though telegram api (not bot) can upload file without changing the filename.
thanks your reply!

**Comment by rubenlagus** [comment]
You are welcome, I'm closing the issue here ;)
