### ISSUE TITLE
Usages of API

### ISSUE THREAD

**Issue by parlad** [rubenlagus/TelegramBots#443]
From [https://core.telegram.org/](url)
>  This API id is limited on the server side and is not suitable for apps released to end-users — using it for anything but testing purposes will result in the API_ID_PUBLISHED_FLOOD error for your users

So it is unsuitable for production and giving to customer ?

**Comment by rubenlagus** [comment]
This API is intended for Bots platform: https://core.telegram.org/bots/api, those API ids you talk about are not related to it.
