### ISSUE TITLE
Error Removing Old Webhook

### ISSUE THREAD

**Issue by bernardyip** [rubenlagus/TelegramBots#447]
Hi, Having some problems with removing oldwebhook out of the blue. I am using TelegramLongPollingBot, my bot which has its own set of test cases passes but I am unable to register the bot to the TelegramBotsApi

This is the error message:

> org.telegram.telegrambots.exceptions.TelegramApiRequestException: Error removing old webhook
> 	at org.telegram.telegrambots.bots.TelegramLongPollingBot.clearWebhook(TelegramLongPollingBot.java:32) ~[telegrambots-3.6.1.jar:?]
> 	at org.telegram.telegrambots.TelegramBotsApi.registerBot(TelegramBotsApi.java:120) ~[telegrambots-meta-3.6.1.jar:?]
> 	at main.Main.main(Main.java:34) [bin/:?]
> Caused by: org.telegram.telegrambots.exceptions.TelegramApiRequestException: Unable to deserialize response
> 	at org.telegram.telegrambots.api.methods.updates.DeleteWebhook.deserializeResponse(DeleteWebhook.java:43) ~[telegrambots-meta-3.6.1.jar:?]
> 	at org.telegram.telegrambots.api.methods.updates.DeleteWebhook.deserializeResponse(DeleteWebhook.java:19) ~[telegrambots-meta-3.6.1.jar:?]
> 	at org.telegram.telegrambots.bots.DefaultAbsSender.sendApiMethod(DefaultAbsSender.java:689) ~[telegrambots-3.6.1.jar:?]
> 	at org.telegram.telegrambots.bots.AbsSender.execute(AbsSender.java:53) ~[telegrambots-meta-3.6.1.jar:?]
> 	at org.telegram.telegrambots.bots.TelegramLongPollingBot.clearWebhook(TelegramLongPollingBot.java:27) ~[telegrambots-3.6.1.jar:?]
> 	... 2 more
> Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
>  at [Source: <html>
> <head><title>502 Bad Gateway</title></head>
> <body bgcolor="white">
> <center><h1>502 Bad Gateway</h1></center>
> <hr><center>nginx/1.12.2</center>
> </body>
> </html>
> ; line: 1, column: 2]
> 	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702) ~[jackson-core-2.8.7.jar:2.8.7]
> 	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558) ~[jackson-core-2.8.7.jar:2.8.7]
> 	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:456) ~[jackson-core-2.8.7.jar:2.8.7]
> 	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1906) ~[jackson-core-2.8.7.jar:2.8.7]
> 	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:749) ~[jackson-core-2.8.7.jar:2.8.7]
> 	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3834) ~[jackson-databind-2.8.7.jar:2.8.7]
> 	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3783) ~[jackson-databind-2.8.7.jar:2.8.7]
> 	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2861) ~[jackson-databind-2.8.7.jar:2.8.7]
> 	at org.telegram.telegrambots.api.methods.updates.DeleteWebhook.deserializeResponse(DeleteWebhook.java:35) ~[telegrambots-meta-3.6.1.jar:?]
> 	at org.telegram.telegrambots.api.methods.updates.DeleteWebhook.deserializeResponse(DeleteWebhook.java:19) ~[telegrambots-meta-3.6.1.jar:?]
> 	at org.telegram.telegrambots.bots.DefaultAbsSender.sendApiMethod(DefaultAbsSender.java:689) ~[telegrambots-3.6.1.jar:?]
> 	at org.telegram.telegrambots.bots.AbsSender.execute(AbsSender.java:53) ~[telegrambots-meta-3.6.1.jar:?]
> 	at org.telegram.telegrambots.bots.TelegramLongPollingBot.clearWebhook(TelegramLongPollingBot.java:27) ~[telegrambots-3.6.1.jar:?]
> 	... 2 more

and the relevant code is as below:

> public static void main(String[] args) {
>         logger.info("Enable trust for SSL");
>         WebController.trustAll();
>         logger.info("Initializing ApiContextInitializer (required for Telegram bot API)");
>         ApiContextInitializer.init();
> 
>         logger.info("Starting up BusTimeBot instance");
>         BusTimeBot.getInstance();
> 
>         logger.info("Loading up Telegram Gateway and registering bot");
>         TelegramBotsApi telegramBotsApi = new TelegramBotsApi();
>         try {
>             telegramGateway = new TelegramGateway();
>             telegramBotsApi.registerBot(telegramGateway);
>             logger.info("BusTimeBot for telegram ready to rock and roll!");
>         } catch (Exception e) {
>             logger.fatal("There is a problem registering the Telegram Gateway!", e);
>         }
>     }

with my extended longpollingbot:

>     public TelegramGateway() {
>         try {
>             loadProperties();
>             lastQueried = new HashMap<Long, Date>();
>         } catch (Exception e) {
>             logger.fatal("Unable to start up Telegram Gateway!", e);
>         }
>     }
>     /**
>      * @return the name of the telegram bot
>      */
>     @Override
>     public String getBotUsername() {
>         return TELEGRAM_BOT_NAME;
>     }
> 
>     /**
>      * @return the telegram bot's token
>      */
>     @Override
>     public String getBotToken() {
>         return TELEGRAM_TOKEN;
>     }

The same code has been working up till today, please help!

**Comment by xpforest** [comment]
+1
I think that is problem with TG. Again :(

**Comment by bernardyip** [comment]
Ah alright! The servers seem to have been fixed just now. Thanks!
