### ISSUE TITLE
Spring boot starter does not work

### ISSUE THREAD

**Issue by AndreiShilov** [rubenlagus/TelegramBots#450]
Spring boot starter does not work as expected. Still, need to manually register bots.

Demo project could be found -> [here](https://github.com/AndreiShilov/telegram-bot-spring-boot-starter-test)

If I manually register bot in post construct method it works as expected

```
 @PostConstruct
    public void post(){
        TelegramBotsApi telegramBotsApi = new TelegramBotsApi();
        try {
            telegramBotsApi.registerBot(this);
        } catch (TelegramApiRequestException e) {
            e.printStackTrace();
        }
    }
```

**Comment by valinz** [comment]
@AndreiShilov I moved the EnableTelegramBots annotation to a separated configuration file and I created a pull request in your demo project -> [here](https://github.com/AndreiShilov/telegram-bot-spring-boot-starter-test/pull/1)
