### ISSUE TITLE
AbilityBot DB support for special characters.

### ISSUE THREAD

**Issue by Systemoutprintln7** [rubenlagus/TelegramBots#455]
Hello.
I wanted to ask feature for supporting special characters on DB when doing backup.
Characters like ᴷᵃˡᶤ or  (ᏉᎥᎮ) Allaͩnͣᵛᵉ🤕 or Ƙяιѕρєℓℓα.🌸 are not supported when doing backup. Is there a way to make them support it? For emojis i found some libraries, but what about special characters?

**Comment by addo37** [comment]
Hey Eric, can you please show the JSON output when those characters are saved?

**Comment by EricS07** [comment]
ØRFÊĪ [aQ5]   ->  ?RF?? [aQ5]
ᴮᵉˡᶤᵃˡ                 ->  ??????
Ƙяιѕρєℓℓα.🌸  -> ?????????.?
Hιкαʀυ { -🦄 }-> H?????
(ᏉᎥᎮ)•Allan🐉[TEAM GOFFO] -> (???)?Allan?[TEAM GOFFO]

If you need more, just tell me.

**Comment by addo37** [comment]
@EricS07 I've changed my name and added one of those characters. The JSON backup seemed ok. What are you using to view the JSON file?

**Comment by Systemoutprintln7** [comment]
It's a platform dependent. Armbian doesnt encode this characters correctly. Ubuntu 16.04/18.04 and Windows 10 does encode everything correctly.
