### ISSUE TITLE
CheckNumber

### ISSUE THREAD

**Issue by alexandrelealjr** [rubenlagus/TelegramBots#459]
how i can check if a number is registred on telegram.

**Comment by bvn13** [comment]
I guess you are not allowed to do this. I don't remember it was implemented into TelegramApi.

**Comment by rubenlagus** [comment]
@alexandrelealjr A bot is not supposed to contact anyone that haven't sent a message to the bot first. So there is no real point to do it. The only couple of workarounds that I know, will make your bot hit limits right away and becomes unusable. So I wouldn't even bother to try.
