### ISSUE TITLE
How do I make the bot send messages without the need for the user to write to the bot?

### ISSUE THREAD

**Issue by alvarodev1** [rubenlagus/TelegramBots#461]

**Comment by bvn13** [comment]
First of all, user have to say "/start" to your bot otherwice they cannot talk to each other.
Then you can save somewhere client id of your user. Then you can send message to this client id.

**Comment by alvarodev1** [comment]
Thank you very much for responding, I followed the examples of the api the bot works with the commands. But what I want to do is a notification button that sends a message at a certain time automatically. Is that possible ? . If I had time, could you tell me how to do it or give me an example?

**Comment by rubenlagus** [comment]
You'll need to code that yourself, you can use some kind of Timer in your code

**Comment by bvn13** [comment]
@alvarodev1 You could check an instance in my [code](https://github.com/bvn13/SpringBlog/blob/master/src/main/java/com/raysmond/blog/notificators/telegram/TelegramBotManager.java), I implemented sending sending messages from web button into telegram channel as well. 

Sending on timer can be implemented using timer or (i.e. Spring Scheduling mechanism) as @rubenlagus noted.

**Comment by alvarodev1** [comment]
Thanks for everything @bvn13 @rubenlagus . I have done it
