### ISSUE TITLE
How can I download a file?

### ISSUE THREAD

**Issue by AhabHyde** [rubenlagus/TelegramBots#462]
Hi
I've read the FAQ on how to download photos, and I can do it with no problem.
But when I try to download a document, the Document class doesn't have the getFilePath() method.

How can I do it?

Thanks

**Comment by rubenlagus** [comment]
You need to call getFile as explained in https://github.com/rubenlagus/TelegramBots/wiki/FAQ#how-to-download-photo, it will tell you the filePath to use
