### ISSUE TITLE
Spring Boot: No qualifying bean of type 'java.util.List<org.telegram.telegrambots.generics.WebhookBot>' available

### ISSUE THREAD

**Issue by sergiussheman** [rubenlagus/TelegramBots#465]
I'm trying to use TelegramBots in Spring Boot application. 

The sample project is [here](https://github.com/sergiussheman/lifeEmployeeBot)
I have added dependency for TelegramBots to my `pom.xml`
``` xml
		<dependency>
			<groupId>org.telegram</groupId>    
			<artifactId>telegrambots-spring-boot-starter</artifactId>
			<version>3.6.1</version>
		</dependency>
```
And i have configuration with `@EnableTelegramBots` annotation
``` java
@Configuration
@EnableTelegramBots
public class TelegramBotConfiguration {
}
```
But when i try to startup my application i get following error
``` xml
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.telegram.telegrambots.starter.TelegramBotStarterConfiguration': Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'java.util.List<org.telegram.telegrambots.generics.WebhookBot>' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
```
Am i missed something?

**Comment by Artgit** [comment]
I ran into the same issue. Could you please provide a workaround for Spring Boot 2 users?

**Comment by maslick** [comment]
it seams you got to have at least two @Components registered (one for TelegramWebhookBot, and one for TelegramLongPollingBot)... This is because they are using constructor injection....

**Comment by donkeystep** [comment]
@maslick , thanks, moving config to separate file and creating a mock WebhookBot in addition to my LongPollingBot worked for me.
![selection_008](https://user-images.githubusercontent.com/20819782/42736006-ec5d6c3e-8866-11e8-84ac-d857fdc1b3eb.png)
