### ISSUE TITLE
Few lines of text in button

### ISSUE THREAD

**Issue by Saeniel** [rubenlagus/TelegramBots#471]
![image](https://user-images.githubusercontent.com/22329568/40858958-b8e76260-65e8-11e8-8b67-46cdae7279d6.png)

There's no way to replace some text to second line as it was said in telefram chat.
Maybe it will be useful feature for others.

**Comment by rubenlagus** [comment]
This kind of button doesn't support multilines, so there is nothing I can do from the API.
