### ISSUE TITLE
Autowired variable is null in bot class

### ISSUE THREAD

**Issue by joshkim27** [rubenlagus/TelegramBots#473]
Hi,

I declared autowired variable in bot class like below.
But variable is null during runtime.

public class TestBot extends TelegramLongPollingBot {

    @Autowired
    private UserService userService;

    @Override
    public void onUpdateReceived(Update update) {
        ...
        userService.insert(user);     <------- userService is null
        ...
    }
}

What am I missing?

**Comment by red-avtovo** [comment]
Is your class annotated with `@Service` or `@Component`?
