### ISSUE TITLE
TelegramBots Java API add likes buttons to the posts

### ISSUE THREAD

**Issue by Artgit** [rubenlagus/TelegramBots#474]
I use [TelegramBots][1] Java API. I need to add like buttons to my posts in Telegram. Right now I'm unable to find information how it can be done with TelegramBots Java API. I think that `InlineKeyboardMarkup` or `@like` bot should be used for this purpose but I don't know how to use it from TelegramBots. Please show how to properly add like buttons to the posts.

  [1]: https://github.com/rubenlagus/TelegramBots

**Comment by hmartinh** [comment]
You can implement your own "like" widget, instead of using 3d party bots. You have to use InlineKeyboardMarkup, handle callback queries and store this clicks in any db.
