### ISSUE TITLE
Can AbilityBots answer to InlineQueryies?

### ISSUE THREAD

**Issue by Flyffies** [rubenlagus/TelegramBots#475]
I haven't found anything about this on the Wiki page and tried to get it to work...
But it doesn't seem to be working add there is no example for it.

So is this even possible right now?

**Comment by addo37** [comment]
Definitely, check https://github.com/rubenlagus/TelegramBots/wiki/Using-Replies

**Comment by Flyffies** [comment]
Could you provide an example of how the code would look like? 

Maybe even add an example to the wiki?

**Comment by Flyffies** [comment]
figuered it out
