### ISSUE TITLE
Ability Bot Getting Started

### ISSUE THREAD

**Issue by djuelg** [rubenlagus/TelegramBots#482]
Hey there!

I worked with this lib and especially AbilityBot a couple of weeks ago, but I had a rather hard time to find more documentation and examples outside this wiki. 

I have a blog with a couple of friends and last monday we published a post about the AbilityBot. We would be pleasured to be part of your documentation, so more people have an easier start :)

This is the post: [Getting Started with Telegrams AbilityBot](https://billigeplaetze.com/getting-started-with-the-telegram-abilitybot)

We are curious what you think of it!

**Comment by Flyffies** [comment]
Thank you, I experimented with them and only wisched for a guide like this! Great work

**Comment by djuelg** [comment]
Thanks! I'm glad to help

**Comment by addo37** [comment]
Fantastic guide, @djuelg. I will definitely issue a PR with the addition of your guide.

**Comment by addo37** [comment]
Thank you again, @djuelg and sorry for the delay ;)

**Comment by Clevero** [comment]
@djuelg I think this issue can be closed, since @addo37 's PR is merged?
If yes, please close the issue.
Thanks! :)
