### ISSUE TITLE
howto remove aktive ReplyKeyboardMarkup?

### ISSUE THREAD

**Issue by Hiajen** [rubenlagus/TelegramBots#483]
May I am just stupid but is there a way to use the ReplayKeyboardRemove Function?
https://core.telegram.org/bots/api#replykeyboardremove

And if so: who do I use it?
It just do not work for me right now.

Thanks for any help! :)

**Comment by rubenlagus** [comment]
It is not a function, it is an object. You need to include it in a message, the same way you included the ReplyKeyboardMarkup
