### ISSUE TITLE
Spring Boot problem

### ISSUE THREAD

**Issue by vrepetenko** [rubenlagus/TelegramBots#484]
Hi!

Trying to run simple bot using Spring Boot, and get error:
aused by: org.springframework.beans.factory.BeanCreationException: 
Error creating bean with name 'polzaTelegramBot': Invocation of init method failed; nested exception is com.google.inject.ConfigurationException: Guice configuration errors:

1) No implementation for org.telegram.telegrambots.generics.BotSession was bound.
  while locating org.telegram.telegrambots.generics.BotSession

1 error
Caused by: com.google.inject.ConfigurationException: 
Guice configuration errors:

1) No implementation for org.telegram.telegrambots.generics.BotSession was bound.
  while locating org.telegram.telegrambots.generics.BotSession

1 error

```
@SpringBootApplication
@EnableTelegramBots
public class Application {

	public static void main(String[] args) {
		ApiContextInitializer.init();
		SpringApplication.run(Application.class, args);
	}
}
```

```
@Component
public class SimpleTelegramBot extends TelegramLongPollingBot {
	
	private static final Logger logger = LoggerFactory.getLogger(SimpleTelegramBot.class);

	@PostConstruct
	public void registerBot(){
	     TelegramBotsApi telegramBotsApi = new TelegramBotsApi();
	     try {
	       telegramBotsApi.registerBot(this);
	     } catch (TelegramApiException e) {
	       logger.error(e.toString());
	     }
	}
	     
	@Override
	public void onUpdateReceived(Update update) {
		Message message = update.getMessage();
......
       }
}
```

**Comment by vrepetenko** [comment]
It seems network related problem...

**Comment by rubenlagus** [comment]
@vrepetenko if it is a network problem, can you close the issue?

**Comment by orantauser** [comment]
I have same problem.
If I run or debug b application - all works great, but when i'm trying to package my app with maven plugin - i'm getting same error.

> Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.773 s <<< FAILURE! - in bitrix24telegrambot.Bitrix24telegrambotApplicationTests
> contextLoads(bitrix24telegrambot.Bitrix24telegrambotApplicationTests)  Time elapsed: 0.003 s  <<< ERROR!
> java.lang.IllegalStateException: Failed to load ApplicationContext
> Caused by: org.springframework.beans.factory.BeanCreationException: 
> Error creating bean with name 'telegramBotInitializer' defined in class path resource [org/telegram/telegrambots/starter/TelegramBotStarterConfiguration.class]: Invocation of init method failed; nested exception is com.google.inject.ConfigurationException: Guice configuration errors:
> 
> 1) No implementation for org.telegram.telegrambots.meta.generics.BotSession was bound.
>   while locating org.telegram.telegrambots.meta.generics.BotSession
> 
> 1 error
> Caused by: com.google.inject.ConfigurationException: 
> Guice configuration errors:
> 
> 1) No implementation for org.telegram.telegrambots.meta.generics.BotSession was bound.
>   while locating org.telegram.telegrambots.meta.generics.BotSession

Maybe I also has network problem, i don't know.
My code:
```
@Component
public class TelegramBot extends TelegramLongPollingBot {

    // Database connection
    @Value("${spring.datasource.url}")
    private String POSTGRES_URL;
    @Value("${spring.datasource.username}")
    private String USER;
    @Value("${spring.datasource.password}")
    private String PASS;

    @Override
    public void onUpdateReceived(Update update) {
    .... code ....
    }
```

```
@SpringBootApplication
public class Bitrix24telegrambotApplication {

	public static void main(String[] args) {

		ApiContextInitializer.init();
		SpringApplication.run(Bitrix24telegrambotApplication.class, args);
	}
}
```
If i remove anotation @Component - application packing, but not works.
How you solved this issue ?

**Comment by coffman21** [comment]
@vrepetenko How did you get rid of this issue? It doesn't seems like network issue: I am able to establish connection with SOCKS5 server, but still getting issue with unbounded BotSession.
