### ISSUE TITLE
 Java Compiler.1.7 or 1.8

### ISSUE THREAD

**Issue by moosaei** [rubenlagus/TelegramBots#49]
when i set java Compiler to 1.7
this error shows

Cannot refer to the non-final local variable callback defined in an enclosing scope	AbsSender.java	/telegrambots/src/main/java/org/telegram/telegrambots/bots	line 802	

but i must set java build path to 1.7

**Comment by rubenlagus** [comment]
The code is built using java 1.8, can't be sure what's going on.. I'll check

**Comment by rubenlagus** [comment]
Ok, I can confirm now that with latest changes (current dev branch), it won't work with java 7, sorry.
