### ISSUE TITLE
Access group history

### ISSUE THREAD

**Issue by stefan-reich** [rubenlagus/TelegramBots#495]
Hi,

[my bot](http://tinybrain.de/1017505) is working fine... but what I still need is a way to get the old messages. Can it be done? [Group link.](http://t.me/Hello_Computer)

Thanks,
Stefan
BotCompany.de

**Comment by Clevero** [comment]
That's not possible. The official Telegram Bot API doesn't offer that.

You need to save them when you get them to access them in the future

**Comment by Clevero** [comment]
@stefan-reich du you have any further questions?
If no, please close the issue

**Comment by bestDvlpr** [comment]
Hi There!

Thank you for great platform, it is working very well.

I thought my issue is related to this topic: is there any way to get channel or group history using messages.getHistory method?
Thank you in advance

**Comment by rubenlagus** [comment]
@bestDvlpr the answer is the same, that method doesn't even exists in Telegram Bots API

**Comment by alexzhyshko** [comment]
Hi all. Seems there have been quite some time since past updates and checking the telegram api documentation, there has to be possibility to read chat history now: https://core.telegram.org/method/messages.getHistory
May I ask, if I see it correct / if it is possible with this library?
