### ISSUE TITLE
Can't get setReplayToMessageId() method from SendDocument class to work

### ISSUE THREAD

**Issue by putorojo** [rubenlagus/TelegramBots#50]
When I use that method nothing happens and the message it's never sent.

I had no problems with SendAudio, SendMessage or SendSticker, It just happen with SendDocument

**Comment by rubenlagus** [comment]
Hi @putorojo, 

can you post the part of the code where you are creating and setting that?

**Comment by rubenlagus** [comment]
No answer, guess it was fixed.
