### ISSUE TITLE
InlineQueryResultCachedSticker is converting to InlineQueryResultCachedGif

### ISSUE THREAD

**Issue by camilosampedro** [rubenlagus/TelegramBots#51]
I suspect it can be fixed by changing the toString method in InlineQueryResultCachedSticker
![capturadeepin20160424155514](https://cloud.githubusercontent.com/assets/8657866/14770343/f344510a-0a34-11e6-9278-911b9c1dbf93.png)

**Comment by rubenlagus** [comment]
Fixed with merge #52
