### ISSUE TITLE
why i can’t sql

### ISSUE THREAD

**Issue by boy-good** [rubenlagus/TelegramBots#513]
![image](https://user-images.githubusercontent.com/39320533/44383152-52326f00-a54a-11e8-9ee0-179b4bfa70f7.png)

**Comment by carlopantaleo** [comment]
Hi, could you post a little bit more code (at least the constructor), please? Anyways this is issue seems to have to do with Spring and not with this library...

**Comment by boy-good** [comment]
sorry, i solved this problem.
