### ISSUE TITLE
how to use inline model?

### ISSUE THREAD

**Issue by boy-good** [rubenlagus/TelegramBots#514]
how to set inline model,like this button..

![image](https://user-images.githubusercontent.com/39320533/44385724-d557c300-a552-11e8-847c-b37bc5a67ca0.png)

**Comment by Clevero** [comment]
Those aren't Inline Buttons.

I think you mean custom keyboards. How to use them can be read in the FAQ
https://github.com/rubenlagus/TelegramBots/wiki/FAQ#how_to_use_custom_keyboards

**Comment by mymike00** [comment]
but how can I use those with an AbilityBot ?
