### ISSUE TITLE
Action clik on InlineButton does not end

### ISSUE THREAD

**Issue by vincenzopalazzo** [rubenlagus/TelegramBots#520]
Hello guys,
Sorry if I disturb you I have a problem with the inlineKeyboard, when the click on the button is made and as if the button was waiting for something.

type in this example
![bug](https://user-images.githubusercontent.com/17150045/45143542-df68fb00-b1bb-11e8-9d52-686b1f6bb647.png)

Can I ask you if it's a problem or just my lack of knowledge of how InlineKeyboard works?

Sorry for the stupid question but I'm trying to learn.

**Comment by gekoramy** [comment]
When the user taps on an [InlineKeyboardButton](https://core.telegram.org/bots/api#inlinekeyboardbutton), he sends a [CallbackQuery](https://core.telegram.org/bots/api#callbackquery)
You have to reply to it with an [AnswerCallbackQuery](https://core.telegram.org/bots/api#answercallbackquery)

**Comment by vincenzopalazzo** [comment]
@gekoramy oh I was a moron, thank you very much

**Comment by gekoramy** [comment]
The CallbackQuery has some fields.
One of them is the **optional*** [Message](https://core.telegram.org/bots/api#message) with the callback button that originated the query.
The Message has other fields, such as:
- the _chat_id_ useful if you want to send a [SendMessage](https://core.telegram.org/bots/api#sendmessage) for example
- the _message_id_ useful if you want to send an [EditMessageTest](https://core.telegram.org/bots/api#editmessagetext) for example
- ...


> \* If you want to know why the field is optional I suggest you to read the [CallbackQuery](https://core.telegram.org/bots/api#callbackquery) introduction

**Comment by vincenzopalazzo** [comment]
@gekoramy ok so I have to do something like that

'execute(sendMessage);
 execute(answerCallbackQuery);'

**Comment by gekoramy** [comment]
Exactly

In general, in order to “tell to Telegram” that your bot has managed to handle the CallbackQuery, you have to reply with an AnswerCallbackQuery

**Comment by vincenzopalazzo** [comment]
@gekoramy Fantastic, very kind thank you

**Comment by gekoramy** [comment]
My pleasure
