### ISSUE TITLE
Send phonenumber.  Get response phonenumber??

### ISSUE THREAD

**Issue by laurohen** [rubenlagus/TelegramBots#523]
How do I get the phone number that the user shared?
I can generate keyboard and sending occurs but I can not get a response.

**Comment by ASLANTORRET** [comment]
Hi, laurohen. You need 
`if(update.hasMessage()` && update.getMessage().hasContact()){` statement in your `updateReceived 
` method to handle a phone number. And `update.getMessage().getContact().getPhoneNumber()` to get the phone number.

**Comment by laurohen** [comment]
update.getMessage().hasContact()  --------> hasContact()  error that does not exist

**Comment by laurohen** [comment]
Updated lib to 4.0.1 load (hasContact() )  ----ok 
Sucess!!!!!!
