### ISSUE TITLE
How change maxThreads (DefaultBotOptions)

### ISSUE THREAD

**Issue by 81x08** [rubenlagus/TelegramBots#527]
I create WebhookBot with DefaulBotOptions.
> DefaultBotOptions defaultBotOptions = new DefaultBotOptions();
defaultBotOptions.setMaxThreads(10);
telegramBotsApi = createSelfSignedTelegramBotsApi();
telegramBotsApi.registerBot(new WebhookHandlers(defaultBotOptions));

and call super:

>public WebhookHandlers(DefaultBotOptions defaultBotOptions) {
super(defaultBotOptions);
}

But when I send messages each one is processed (5 seconds - Thread.sleep), see this in the chat:

>grizzly-http-server-1
grizzly-http-server-0
grizzly-http-server-1
grizzly-http-server-0
grizzly-http-server-1

Why 0, 1? I expected to see: 0, 1, 2, 3, 4

**Comment by Chase22** [comment]
The maxThreads option is only used for async execution of methods using executeAync() method. It does not influence how many threads are used for handling messages from the webhook
