### ISSUE TITLE
Can't send a message in main

### ISSUE THREAD

**Issue by AlexBexDE** [rubenlagus/TelegramBots#546]
Hello,
I want to send a Message in the `main(String[] args)`
But I can't use `execute(message);` and I don't have a `TelegramBotHandler`.
I tried to make a method in the bot-class but I can't use it, in the main.

**Comment by Chase22** [comment]
The execute method is not static. You need a instance for the bot.

In your main method you are probably registering the bot using TelegramBotsApi.registerBot(). Use the instance you are passing to that method and call execute() on it
