### ISSUE TITLE
Group Chat Support?

### ISSUE THREAD

**Issue by hamhub7** [rubenlagus/TelegramBots#553]
I am having some trouble with getting messages to be picked up in a group chat. I have a simple command that picks up if the first 3 letters of your message is "im " as a bot prefix. this works fine in dm messages, but when i go into group chats, only the / commands that i have implemented work. how do i fix this to pick up all messages on the onUpdateRecieved method instead of only /commands and dms?

**Comment by aNNiMON** [comment]
Disable Group Privacy for your bot in Botfather.
