### ISSUE TITLE
Sending Group photo

### ISSUE THREAD

**Issue by san3ani** [rubenlagus/TelegramBots#558]
Hello
I am trying to get the group photo and then send it to a channel.
I used 
GetChat to get the group info. Then I tried using SendPhoto to send the photo after setting the setPhoto to the bigFiledId (I also tried the smallFieldId)
However, I keep getting the following exception 
org.telegram.telegrambots.exceptions.TelegramApiRequestException: Error sending photo: [400] Bad Request: type of file mismatch

Any ideas?

**Comment by san3ani** [comment]
The java API has nothing to do with this error. It seems the bigFiledId  and smallFieldId do not correspond to the photo id that is used in the SendPhoto method.

**Comment by aNNiMON** [comment]
According to [Telegram Bot API docs](https://core.telegram.org/bots/api#chatphoto) you can't use ChatPhoto file ids for anything except photo download

**Comment by san3ani** [comment]
> According to [Telegram Bot API docs](https://core.telegram.org/bots/api#chatphoto) you can't use ChatPhoto file ids for anything except photo download

Thanks a lot. You are 100% correct.
I will try to download the photo first and then upload it and send it. I don't know why telegram didnt make the group photo similar to the user profile photo.
