### ISSUE TITLE
Error in method execute(SendAnimation sendAnimation) 

### ISSUE THREAD

**Issue by vladimirovichsa** [rubenlagus/TelegramBots#567]
In **DefaultAbsSender.java** present error in `String url = getBaseUrl () + SendVoice.PATH;`. 
Is it in the execute method(Sandanimation sendAnimation) must be a call to SendVoice?
When I send a GIF, I get this error **org.telegram.telegrambots.meta.exceptions.TelegramApiRequestException: Error sending animation: [400] Bad Request: there is no voice in the request
	at org.telegram.telegrambots.meta.api.methods.send.SendAnimation.deserializeResponse (SendAnimation.java: 205).**

**Comment by aNNiMON** [comment]
@vladimirovichsa it is already fixed in dev branch with #524 
IYou can use jitpack https://jitpack.io/#rubenlagus/TelegramBots/dev-SNAPSHOT

**Comment by LeviSchuck** [comment]
This should be closed, it is now included with the latest version on maven.

**Comment by Chase22** [comment]
@vladimirovichsa can be closed
