### ISSUE TITLE
 onUpdateReceived (Update update) multithreading

### ISSUE THREAD

**Issue by LaYJeL** [rubenlagus/TelegramBots#570]
Guys, who can help me with async getting updates.
https://stackoverflow.com/questions/54215059/telegram-bot-new-update-in-new-thread-with-telegrambots-spring-boot-starter
Here I ask how to solve the problem, but I did not get an answer.
Maybe method "executeAsync" can help me, but i can't find any examples how to use it.
Can someone help me ???

**Comment by Chase22** [comment]
The onUpdateRecieved Method is already executed asynchronously in the handler thread. Which there's only one.
Easiest way for this to work is use the onUpdateRecieved() method to build and start a worker thread that does the handling. That way you go through that method very quickly and can handle the next update, while the actual processing is taking place asynchronously

**Comment by LaYJeL** [comment]
Thank you. 
That is what i looking for.
Please, can you give me url with example???
Or where i can read more about it ???

**Comment by LaYJeL** [comment]
I found  the solution.
```
 @Override
    public void onUpdateReceived(Update update) {

        new Thread(new Runnable() {
            @Override
            public void run() {
                if (update.hasMessage()) {
                // code goes here.
                }
   }.start
}
```
This code works fine with many users at the same time.
But i don't know correct this solution or not...

**Comment by Chase22** [comment]
You could also use Java Futures for it. Which is probably the more current way to do it

**Comment by LaYJeL** [comment]
Ok, thanks.
