### ISSUE TITLE
How to get the join message?

### ISSUE THREAD

**Issue by Spixmaster** [rubenlagus/TelegramBots#582]
Do you know how to get the join message? Is it even possible? I already know new_chat_members but I need the person who added the users or the whole join message as a string.

**Comment by ivan909020** [comment]
if (message.getLeftChatMember() == null && message.getText() == null && message.getNewChatMembers().size() > 0) {
   String name = message.getNewChatMembers().get(message.getNewChatMembers().size() - 1)
`.getFirstName();
}

**Comment by Spixmaster** [comment]
I have the solution: with `message.from()` you get the person who added the new members and with `message.newChatMembers()` you get the added users.

**Comment by Spixmaster** [comment]
I have the solution: with `message.from()` you get the person who added the new members and with `message.newChatMembers()` you get the added users.
