### ISSUE TITLE
Conversation Between User And Bot

### ISSUE THREAD

**Issue by vbaidak** [rubenlagus/TelegramBots#585]
Hi!

My question could seem somewhat stupid, but I went through the Wiki and Issues and couldn't find the answer.
Basically, what I'm trying to achieve is a simple conversation between User and Bot, where Bot answers the User's previous question. I don't really understand how the API allows to identify that the current User's message answers the previous question and not the other one.

To be more concrete here is my case:

```code
fun search(): Ability {
    val markup = InlineKeyboardMarkup()
    val edrpouButton = InlineKeyboardButton("EDRPOU").setCallbackData("search_by_edrpou_requested")
    val nameButton = InlineKeyboardButton("Name").setCallbackData("search_by_name_requested")
    markup.keyboard = listOf(listOf(edrpouButton, nameButton))

    return Ability.builder()
        .name("search")
        .info("Search")
        .locality(Locality.ALL)
        .privacy(Privacy.PUBLIC)
        .action {
            val message = SendMessage(it.chatId(), "Select Search Type")
                .setReplyMarkup(markup)
                execute(message)
        }
        .reply(Consumer<Update?> { update ->
            val chatId = AbilityUtils.getChatId(update)
            when (update?.callbackQuery?.data) {
                "search_by_edrpou_requested" -> execute(EditMessageText().setChatId(chatId)
                                    .setMessageId(update.callbackQuery?.message?.messageId)
                                    .setText("Enter EDRPOU")
                )
                "search_by_name_requested" -> execute(SendMessage(chatId, "Enter Name"))
             }
        }, Flag.CALLBACK_QUERY)
        .build()
}
```

1. User types **/search** command
2. Two buttons appear ("EDRPOU" and "Name")
3. User presses "EDRPOU" button
4. "Enter EDRPOU" text is shown
5. User enters text

And here it is, at step 5, how can I guess that the entered text is actually an answer for "Enter EDPROU" and not for "Enter Name" or any other case? I though there might be some option for setting the previous message - the same like this is done with callback query.

Also I know this could be achieved with **DBContext**, but is it really the case to use it?

Thank you!

**Comment by addo37** [comment]
Hey @vbaidak, thanks for using the AblityBot library.

For your specific inquiry, the reply function takes in a `Consumer<Update>` and a vararg of `Predicate<Update>`. The `Flag` enum implements the Predicate interface.

For your use case, you can append this predicate and it would trigger the proper function:
```java
.reply(
<Your Consumer Here>,
Flag.CALLBACK_QUERY,
upd -> upd.getCallbackQuery().getData().equals("Enter EDPROU"))
```

Obviously, if you want to reuse that predicate, I suggest you refactor to this:
```java
public Predicate<Update> isReplyToQuery(String data) {
  return upd -> upd.getCallbackQuery().getData().equals(data);
}
```

No need to check whether the update is a callback query once your declare the CALLBACK_QUERY flag *before* the query-checking predicate.

After refactoring, this would now look like:
```java
.reply(
<Your Consumer Here>,
Flag.CALLBACK_QUERY,
isReplyToQuery("Enter EDPROU"))
```

Let me know if you have any further questions. :)

**Comment by vbaidak** [comment]
@addo37 , thanks for answering. Not it is a bit more clear to me
