### ISSUE TITLE
How to send a self-destruction message?

### ISSUE THREAD

**Issue by Spixmaster** [rubenlagus/TelegramBots#588]
How is it possible that a bot sends a message which will only be visible for ~30 seconds?

**Comment by Chase22** [comment]
This is currently not supported by the telegram api. 

What you can do is send the message, set a timer using the ScheduledExecutorService and delete the message after the timer.

**Comment by Spixmaster** [comment]
@Chase22 but the bot needs to be responsible during that.
Could it be possible to get the message id of the sent message in order to delete it?
i already tried that but it did not work.
i work with the cpp api but listener onAnyMessage does not recognize sent messages of the bot

**Comment by Chase22** [comment]
The execute (SendMessage) method returns the send message as an object. You can read the id from there

**Comment by Spixmaster** [comment]
@Chase22 Thanks. I thought it was void...
