### ISSUE TITLE
How to send Unicode?

### ISSUE THREAD

**Issue by Spixmaster** [rubenlagus/TelegramBots#589]
How can I send unicode with the bot?

**Comment by Chase22** [comment]
You send a message. 

All messages are Unicode encoded

**Comment by Spixmaster** [comment]
```
wchar_t a[] = L"🎊";
bot.getApi().sendMessage(message->chat->id, '@' + message->from->username + " " + a + " Before doing anything in this group activate the bot (@" + bot.getApi().getMe()->username + ")!");
```
I have absolutely no idea. This is what is intended. How would this work?
I use a C++ API.

**Comment by Spixmaster** [comment]
When wanting to print out "🎊" you need to write "\xf0\x9f\x8e\x8a" in your code. this site helps to convert: https://www.branah.com/unicode-converter.
