### ISSUE TITLE
No getter for data field in CallbackQuery

### ISSUE THREAD

**Issue by tolegen-t** [rubenlagus/TelegramBots#59]
There is no public getter of "data" field in CallbackQuery

**Comment by antonu17** [comment]
@tolegen-t I think you are using outdated source.
it is there: [CallbackQuery.java:83](https://github.com/rubenlagus/TelegramBots/blob/master/src/main/java/org/telegram/telegrambots/api/objects/CallbackQuery.java#L83). It was added 10 days ago in https://github.com/rubenlagus/TelegramBots/commit/a601e983ecb485f20ef7a28037926d67cae20313

**Comment by rubenlagus** [comment]
As @antonu17 said, it was added.
