### ISSUE TITLE
deleteMessage() causes problem 

### ISSUE THREAD

**Issue by Spixmaster** [rubenlagus/TelegramBots#590]
```
if (args.at(0) == "Dx" + std::to_string(constants::ENGAGEMENT_AMOUNT) || args.at(0) == "dx" + std::to_string(constants::ENGAGEMENT_AMOUNT))
{
     //###irrelavant code for now
}
else
{
	if (!tools::isAdmin(bot, message->from, message))
	{
		if (tools::isAdmin(bot, bot.getApi().getMe(), message))
		{
			std::cout << "Deleted message in group:\n" << message->from->username << ":\n" << 
                        message->text << '\n' << std::endl;
			bot.getApi().deleteMessage(message->chat->id, message->messageId);
		}
		else
		{
		    TgBot::Message::Ptr msg = bot.getApi().sendMessage(message->chat->id, "\xe2\x9d\x8cThe 
                     bot does not have the permission to delete messages. Make him admin to solve the 
                     problem!");
		     //to delete message after a while
		     cleanChat::add(msg->messageId);
		}
}
```

This is the relevant code.
The intention is that it is only allowed to write messages in a group which start with "Dx10".

Following problem occurs. I happens from time to time that the application crashes. The programm can be started again if the code above is commented out.
I highly assume that the program crashes due to the function deleteMessage() which tries to delete a non-existent message.
The only reason for this is that a user deletes a message before the program does it.
Deleting non-existent messages lets the app crash.

**My question:
Is there a possibility to check whether the message with the corresponding messageId is still existent?**

**Comment by Clevero** [comment]
This library is written in Java, not C++
Please ask your question in the group/forum/issue page of your lib you are using

**Comment by Spixmaster** [comment]
@Clevero As the http get requests of the Telegram API deliver the same json the programming language does not matter really.
You can neglect the code.
Just say if you know a way the state whether a message is still existent,

**Comment by Chase22** [comment]
@Spixmaster You can't directly check whether a message still exists. Telegram does not support interacting with the message history.

You can only try to delete the message and see if it returns an error.

**Comment by Spixmaster** [comment]
@Chase22 with the c++ api the app crashes. Do you know if it is possible that it doesn't?

Nevertheless, you often so often my questions. Thank you either way!

**Comment by Clevero** [comment]
Can't you just catch the exception? Like with try/catch block

**Comment by Chase22** [comment]
@Spixmaster i do not know c++ or the libary your are using. It's probably better to head to that libaries GitHub and ask there

**Comment by Spixmaster** [comment]
I got it. just surround deleteMessage() with a try block and catch the exception. 👍
