### ISSUE TITLE
Standard ability-bot commands.

### ISSUE THREAD

**Issue by ScriptGenius** [rubenlagus/TelegramBots#592]
Please allow developers to disable standard ability-bot commands, such as /claim, /promote and etc.
Maybe something like this:
   ` @Override
    public bool enableStandardCommands(){
       return false;
    }`

**Comment by addo37** [comment]
FYI, this has been implemented in the latest 4.4.0.2 version via [ability toggles](https://github.com/rubenlagus/TelegramBots/wiki/Ability-Toggle)!
