### ISSUE TITLE
How to use GetChatMember?

### ISSUE THREAD

**Issue by rmasoumvand** [rubenlagus/TelegramBots#596]
Hi,
Im using this library to create my telegram bot,
i need to use GetChatMemeber to check my user is member of a group, i have read this class code and found no way to how to use it.
could please some write a simple exmaple of how to use this class?

thanks

**Comment by Clevero** [comment]
```java
GetChatMember getMember = new GetChatMember();
getMember.setChatId(the_id_of_the_chat); //like the id of the group
getMember.setUserId(user_id); //the id of the specific user

//since the API method GetChatMember is returning a ChatMember object on succes, 
// you can try to retrieve it
ChatMember theChatMember = execute(getMember);
```

https://core.telegram.org/bots/api#getchatmember

**Comment by rubenlagus** [comment]
Answered

**Comment by kurenchuksergey** [comment]
why userId is Integer?
