### ISSUE TITLE
Bot created in runtime

### ISSUE THREAD

**Issue by xTheDoctah** [rubenlagus/TelegramBots#603]
Hi, 
there is a way to "register" a bot created in runtime (via spring BeanRegistryDefinition) ? 

Thank you in advance.

EDIT: what i'm trying to achive is the possibility to add and register/unregister bot in runtime

**Comment by Chase22** [comment]
Since registering a bot is a call to a method, you can only do it at runtime. 
Just call telegrambotsapi.register() when you need

**Comment by xTheDoctah** [comment]
@Chase22 Ty i figured out now. I just autowired the object TelegramBotsApi and used the register method.
