### ISSUE TITLE
Get user message in other method

### ISSUE THREAD

**Issue by NiksonBinsk** [rubenlagus/TelegramBots#611]
I'm trying to make command, that requires arguments. idk how to get user message without update

**Comment by Chase22** [comment]
Are you using CommandBot and the BotCommand class?

**Comment by NiksonBinsk** [comment]
@Chase22 no.

**Comment by Chase22** [comment]
@NiksonBinsk i understood the message wrong.
You can not get any messages from a chat. When a message gets send, your bot recieves an update via the onUpdateRecieved method
