### ISSUE TITLE
Find links in message

### ISSUE THREAD

**Issue by sintaklaas** [rubenlagus/TelegramBots#613]
Currently when i use:

`update.getMessage().getText()`

Its the raw text of message that has been sent.
But the message can cotnain links, how do i extract them from the text?

**Comment by Philipinho** [comment]
It can be achieved using REGEX.

**Comment by sintaklaas** [comment]
I cannot use REGEX cause when I send the bot this:

This is a link (http://www.google.com/)!

It doesnt have the http-link in it...
It just sees:

This is a link!

(with the clickable "link")

**Comment by gekoramy** [comment]
https://core.telegram.org/bots/api#messageentity

**Comment by Chase22** [comment]
@sintaklaas Please close this if the issue is resolved
