### ISSUE TITLE
IOS sends same Message multiple times

### ISSUE THREAD

**Issue by entnx-01** [rubenlagus/TelegramBots#619]
I wrote a simple application in java for polling the updates of my telegram Bot. 

If a user sends a message from IOS an close the application without leaving the chat first, the bot received the same massage multiple times. 

The updateId increments and I don´t know, how to stop this. The bot answers the message multiple times, too.

Does anyone know this issue?

**Comment by MouamleH** [comment]
If you say that the updateId increments  then it's a "telegram IOS" issue not a bot api issue.

**Comment by rubenlagus** [comment]
Nothing we can fix from here, sorry.
