### ISSUE TITLE
set CallbackQuery like executed

### ISSUE THREAD

**Issue by Patatone** [rubenlagus/TelegramBots#630]
Is there a way to set a CallbackQuery like executed?
I want to remove the circled clock when i push the button.
![image](https://user-images.githubusercontent.com/34103646/59755086-9df79700-9287-11e9-8dab-a33e58dfbbb9.png)
Thanks for reply.

I know there is the doc but i don't find it.

**Comment by gekoramy** [comment]
https://core.telegram.org/bots/api#answercallbackquery

**Comment by Patatone** [comment]
Thanks :)
