### ISSUE TITLE
How to send messages to the channel?

### ISSUE THREAD

**Issue by Alesh17** [rubenlagus/TelegramBots#634]
I tried to use `sendMessage.setChatId` with channel id (-1234567), but it is not work.
With bot's chatId it works fine.

**Comment by Chase22** [comment]
What exactly didn't work?
Did you get an exception?

**Comment by Alesh17** [comment]
My bad, sorry. I'm used this thing:
`SendMessage sendMessage = new SendMessage();`
`ReplyKeyboardMarkup replyKeyboardMarkup = new ReplyKeyboardMarkup();`
`sendMessage.setReplyMarkup(replyKeyboardMarkup);`
And my message was not sent to the channel, because buttons were attached to it...
