### ISSUE TITLE
How to know has result of execute(message) error or not?

### ISSUE THREAD

**Issue by DenisWpk** [rubenlagus/TelegramBots#635]
Hi! 

I want to check result of 
` try {
            execute(message);
        } catch (TelegramApiException e) {
            e.printStackTrace();
        }`

Something like that `Result r  = execute(message); if (r.isOk) {}`
execute(message) rerurns Message type and I didn't find what I need. 

Thank you.

**Comment by Chase22** [comment]
when execute does not execute the given method successfully a TelegramApiException will be thrown. That's the way you know that something didn't work.
