### ISSUE TITLE
Duplicate logging

### ISSUE THREAD

**Issue by ImagePrototype** [rubenlagus/TelegramBots#638]
`dependencies {
    compile "org.telegram:telegrambots:4.3.1"
    compile "org.telegram:telegrambotsextensions:4.3.1"
    testCompile 'com.h2database:h2:1.3.148'
}`

`21:27:34: Executing task 'Main.main()'...

> Task :compileJava UP-TO-DATE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE

> Task :Main.main()
июл 24, 2019 9:27:36 PM org.telegram.telegrambots.meta.logging.BotLogger warning
WARNING: [MessageScheduler] - File 'chats.txt' not found, creating new...
июл 24, 2019 9:27:36 PM org.telegram.telegrambots.meta.logging.BotLogger warning
WARNING: [MessageScheduler] - File 'chats.txt' not found, creating new...
июл 24, 2019 9:27:36 PM org.telegram.telegrambots.meta.logging.BotLogger info
INFO: [MessageScheduler] - File 'chats.txt' successfully created!
июл 24, 2019 9:27:36 PM org.telegram.telegrambots.meta.logging.BotLogger info
INFO: [MessageScheduler] - File 'chats.txt' successfully created!`

I can't understand what the problem is? Can I get some help?

**Comment by rubenlagus** [comment]
Update to the last version and this should go away since the BotLogger was removed completely, now it is just using basic log4j2 logging.

**Comment by ImagePrototype** [comment]
> Update to the last version and this should go away since the BotLogger was removed completely, now it is just using basic log4j2 logging.

![image](https://user-images.githubusercontent.com/19995957/62629758-75f6ec80-b936-11e9-9b75-ad74101ea678.png)
