### ISSUE TITLE
DBContext recover with Var fails

### ISSUE THREAD

**Issue by Baspla** [rubenlagus/TelegramBots#642]
Using db.getVar("...") and trying to create a backup, this saves it as ["org.mapdb.Atomic$Var",{"recid":42}] and since there is not really any data to recver anything the recovery fails.

_Part of the exception stack:_
InvalidDefinitionException: Cannot construct instance of `org.mapdb.Atomic$Var` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)

**Comment by Baspla** [comment]
When saving a Custom Class in a Set i ran across the same problem for my class and fixed it by adding Jackson annotations to the constructor. Not sure how much this is applicable here.
Annotations i used:
@JsonCreator
@JsonProperty

**Comment by addo37** [comment]
Hey @Baspla! Thank you so much for opening this issue.

A [pull request](https://github.com/rubenlagus/TelegramBots/pull/664) is on its way to merge. :)

**Comment by alexdavliatov** [comment]
@addo37 Could this Issues be closed?

**Comment by addo37** [comment]
Well, only the issue creator and @rubenlagus can. It's been a while and this has definitely been addressed.
