### ISSUE TITLE
 Send a PUSH-notifications to more than one user

### ISSUE THREAD

**Issue by LBiffi** [rubenlagus/TelegramBots#654]
Hello!
I am trying to learn how to program a bot and was wondering if it is possible to make a
PUSH-notifications without commenting @ with the name of all users.
Initially it would be to call all members of a group, like slack or discord "@here" and "@all". But I would also like to call specific group of users (inside a telegram group). Imagine that, the users must must choose a value from a list, such as male and female. This registration will be done by a bot method, that will hold their id). Is it possible to do that too by sending a PUSH-notifications to only those who registered in (example), female in the list?

**Comment by rubenlagus** [comment]
When it is added to the API, we can see if it can be added to the library: https://core.telegram.org/bots/api
