### ISSUE TITLE
The artifact `org.telegram:Bots:4.4.0` is missing in maven repo

### ISSUE THREAD

**Issue by peterquiel** [rubenlagus/TelegramBots#655]
Motivated by https://stackoverflow.com/questions/57669668/could-not-resolve-org-telegramtelegrambots4-4-0/57670630#57670630

If you check out https://mvnrepository.com/artifact/org.telegram/Bots you will notice that `4.4.0` is missing.

**Comment by rubenlagus** [comment]
Use version 4.4.0.1, it should be fixed there
