### ISSUE TITLE
sendMessage.setParseMode("Markdown") makes *text* bold instead of cursive

### ISSUE THREAD

**Issue by stormstricker** [rubenlagus/TelegramBots#657]
And `**text**` gets displayed as usual text.

**Comment by gekoramy** [comment]
https://core.telegram.org/bots/api#markdown-style

**Comment by stormstricker** [comment]
> https://core.telegram.org/bots/api#markdown-style

Hm, that interesting, looks like the markdown for bots and users is different? Because if I send *test* as a user, it won't make it neither bold nor italic, but if I send **test** as a user, it would make it bold. Then, if I send __test__ as a user, it would make it italic. But if I send __test__ as a bot, it would make it normal text. If I send **test** as a bot, it would be normal text, while *test* as a bot would be bold.

**Comment by gekoramy** [comment]
I think that the markdown "for users" depends on the client app implementation

Anyway, if the issue is solved, please mark it as such
Thank you
