### ISSUE TITLE
Sending ```dog and cat``` would only deliver ``` and cat```, truncating the first word after threeticks

### ISSUE THREAD

**Issue by stormstricker** [rubenlagus/TelegramBots#658]

**Comment by stormstricker** [comment]
I understand it's so to remove the language names such as ```java System.out.println("Hello");```, however often people send non-code in codeblocks, so it would be useful to have an ability not to truncate such input.

**Comment by gekoramy** [comment]
https://core.telegram.org/bots/api#markdown-style

> \```block_language
> pre-formatted fixed-width code block
> \```

The 1st word determine the language code

Try to send your text like that ` ```\ndogs and cat``` `
