### ISSUE TITLE
Sending cursive strings with underscores inside

### ISSUE THREAD

**Issue by stormstricker** [rubenlagus/TelegramBots#662]
A message like this: ```_hello\_you_``` can't get sent, an error `org.telegram.telegrambots.meta.exceptions.TelegramApiRequestException: Error sending message: [400] Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 11`.

**Comment by rubenlagus** [comment]
The API doesn't support escaped characters inside an entity, nothing I can do from here, sorry.
