### ISSUE TITLE
Scheduled messages

### ISSUE THREAD

**Issue by Alesh17** [rubenlagus/TelegramBots#663]
Hello, the Telegram update was recently released, which added methods for working with scheduled messages. Will you update the library?

**Comment by Chase22** [comment]
It will be added when telegram updates the underlying not API

**Comment by Alesh17** [comment]
What do you mean by  
> updates the underlying not API

Telegram API method list has already [scheduled messages methods](https://core.telegram.org/methods#working-with-scheduled-messages)

**Comment by addo37** [comment]
@Alesh17 

What Chase means is that, the update for scheduled messages applies for the user API (standard, it's what the clients use to communicate with Telegram servers). However, this feature hasn't been released yet to [Bot API](https://core.telegram.org/bots/api).

**Comment by Alesh17** [comment]
I apologize. I did not know that there is a separation of the API. Thank!
