### ISSUE TITLE
Dependency won't resolve

### ISSUE THREAD

**Issue by stonetwig** [rubenlagus/TelegramBots#669]
Hello,

I am using a fresh gradle project in order to build a telegram bot so I thought to give this library a try. However, when I add the gradle compile instruction as per the wiki I get this on `gradle build`:

```
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve org.telegram:telegrambots:4.4.0.
     Required by:
         project :
      > Could not resolve org.telegram:telegrambots:4.4.0.
         > Could not parse POM https://repo.maven.apache.org/maven2/org/telegram/telegrambots/4.4.0/telegrambots-4.4.0.pom
            > Could not find org.telegram:Bots:4.4.0.
              Searched in the following locations:
                - https://repo.maven.apache.org/maven2/org/telegram/Bots/4.4.0/Bots-4.4.0.pom
                - https://repo.maven.apache.org/maven2/org/telegram/Bots/4.4.0/Bots-4.4.0.jar

```
I have both tried the JitPack version and the normal Maven one, both gives the same error.
I can reach the POM file in my web browser so there isn't really anything wrong with my internet connection.

Maybe you could help me?

All I did was add the compile instruction to my dependencies object in my gradle config:

```
dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.12'
    compile "org.telegram:telegrambots:4.4.0"
}
```

It was some time ago that I did any java development, thanks in advance!

**Comment by addo37** [comment]
Have you tried [4.4.0.1](https://mvnrepository.com/artifact/org.telegram/telegrambots/4.4.0.1)?

**Comment by stonetwig** [comment]
No, but I will do that later today :)
Thanks for the advice!

**Comment by stonetwig** [comment]
Hello,

Yes this worked great. Thank you!
