### ISSUE TITLE
A lot "Error editing message text: [400] Bad Request"

### ISSUE THREAD

**Issue by eos1d3** [rubenlagus/TelegramBots#674]
I have a message with inlinekeyboard markup, and I keep editing it.

From time to time, I alway receive this warning. But in the inlinekeyboard makrup, I have a random number to ensure no duplicate edit message is sent. But I still receive up to 7 warnings at a time randomly. But for most of time, I may get only one warning.

From what I know, OKHttp client has auto retry enabled by default. [link](https://square.github.io/okhttp/3.x/okhttp/okhttp3/OkHttpClient.Builder.html#retryOnConnectionFailure-boolean-)

I have no way to stop this error. Please check if it is from OKHttp. Thanks!

`org.telegram.telegrambots.meta.exceptions.TelegramApiRequestException: Error editing message text: [400] Bad Request: message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message`

**Comment by rubenlagus** [comment]
This happens when you try to edit a message to the same message again (aka no changes are applied). You should be fine ignoring this error

**Comment by eos1d3** [comment]
This is not the case. For every edit message, I do have a random number in the markup so that each edit message is different.

**Comment by mattmalec** [comment]
Yes, it absolutely is the case. You’re either updating the wrong message or not executing the correct EditMessageText.

**Comment by GoStaRoff** [comment]
Perhaps you are editing the message in the same text as it is. It helped me solve my problem :)

**Comment by evakdev** [comment]
I was editing the buttons' texts, and for some specific edits it worked and for some others it didnt. So I ended up just recreating a button object with the new text and replacing the old one. that solved the problem.

**Comment by ffaauusstt** [comment]
This problem already exists. And I think the reason is bad internet - when user clicks button, doesn't see any result, and clicks again and again. Later internet appears and you see all those beauties in a console )

**Comment by ahrorjonIsroilov** [comment]
> This happens when you try to edit a message to the same message again (aka no changes are applied). You should be fine ignoring this error

Hi. I have also have this problem. But you say that it should be fine to ignore this error. How can I handle telegram errors like this. Becasue in my program every error and exception islogged and I don't want to log unnecessary errors like this.
