### ISSUE TITLE
Not seeing update events from other bot

### ISSUE THREAD

**Issue by andyrozman** [rubenlagus/TelegramBots#681]
So I created bot, which would listen in channel and try to find specific messages (this messages are created by different bot that I have no power over). I can see all messages in channel, except the ones from other bot.

I though that if bot sends message to the channel, that my bot would be able to see it, but it seems that that is not the case... How can I make my bot see other bots messages? 

In Bot TG channel they said that while my bot can't communicate with other bots, it should be possible to see messages that other bot sends to channel... Am I missing something?

**Comment by Chase22** [comment]
[https://core.telegram.org/bots/faq#why-doesn-39t-my-bot-see-messages-from-other-bots](https://core.telegram.org/bots/faq#why-doesn-39t-my-bot-see-messages-from-other-bots)

That should answer it
