### ISSUE TITLE
I want to use a telegram bot with the same token on two servers.

### ISSUE THREAD

**Issue by cupssky** [rubenlagus/TelegramBots#693]
Can you show me how?

**Comment by Chase22** [comment]
This is not possible.
With long polling telegram doesn't allow to have 2 bots run simultaneously and using webhook you can only set one target address

**Comment by cupssky** [comment]
Is it impossible to run on two servers with the same bot at the same time?

**Comment by Chase22** [comment]
With the same token yes

**Comment by cupssky** [comment]
@Chase22 
Is there no other way?

**Comment by Chase22** [comment]
What do you want to do exactly?

**Comment by cupssky** [comment]
I'm sorry. Thank you for finding an alternative.
