### ISSUE TITLE
Cannot import lib

### ISSUE THREAD

**Issue by KaratekHD** [rubenlagus/TelegramBots#696]
Hello,

Is it possible that the Getting started guide is out of date?
I'm asking because it appears that the _TelegramBotsApi_ class doesn't exist. 
![Screenshot_20191125_165058](https://user-images.githubusercontent.com/38097062/69555649-c9ec1680-0fa3-11ea-9ba1-1721c214f9c1.png)

![Screenshot_20191125_165204](https://user-images.githubusercontent.com/38097062/69555733-f011b680-0fa3-11ea-8206-f4c772f1dbb6.png)

Thank you very much for your help!

~Karatek_HD

**Comment by rubenlagus** [comment]
It looks like you are not importing the library correctly, the class is completely included:

https://github.com/rubenlagus/TelegramBots/blob/master/telegrambots-meta/src/main/java/org/telegram/telegrambots/meta/TelegramBotsApi.java


You can see examples to  import it here: https://github.com/rubenlagus/TelegramBots#usage

**Comment by KaratekHD** [comment]
Figured it out. I imported the lib using Maven and now everything works just fine.
