### ISSUE TITLE
Customize BaseAbilityBot

### ISSUE THREAD

**Issue by wonderf** [rubenlagus/TelegramBots#698]
BaseAbilityBot have chain of functions for Update. Look like
`Stream.of(update)
                .filter(this::checkGlobalFlags)
                .filter(this::checkBlacklist)
                .map(this::addUser)
                .filter(this::filterReply)
                .map(this::getAbility)
                .filter(this::validateAbility)
                .filter(this::checkPrivacy)
                .filter(this::checkLocality)
                .filter(this::checkInput)
                .filter(this::checkMessageFlags)
                .map(this::getContext)
                .map(this::consumeUpdate)
                .forEach(this::postConsumption);`
I want change format of commands. Enought override getAbility but all methods private or smth like that.

**Comment by addo37** [comment]
What do you mean format of commands? If you mean the `/commands`, we had similar issue [here](https://github.com/rubenlagus/TelegramBots/issues/436).

**Comment by wonderf** [comment]
getAbility work with commands only start with '/' . For example I want use command '🎹 Music'.

**Comment by addo37** [comment]
Oh, you may use [replies](https://github.com/rubenlagus/TelegramBots/wiki/Using-Replies) for that!

**Comment by wonderf** [comment]
Actually replies for conversation. I want use this command for custom keyboard.

**Comment by addo37** [comment]
Yes, you can do that too. Please read the wiki carefully...
