### ISSUE TITLE
Tagger_Bot limitation to mentioned 4 users

### ISSUE THREAD

**Issue by mentolrespiral** [rubenlagus/TelegramBots#706]
Tagger_Bot is a very useful bot in large groups with users with different interests. By allowing to subscribe to several tags, they can be mentioned specifically of each one of them without having to notify the rest of the group members. However Tagger_Bot inherits a telegram limitation: Telegram doesn't notify the people mentioned after the first 4-5 if they are mentioned in the same message. In order to work well, they must be called into multiple messages as in everyone-bot (https://github.com/everyone-bot/everyone-bot). Could the Tagger_Bot configuration be changed to mention only four users per message and thus allow everyone to be notified? Thanks for the help

**Comment by Chase22** [comment]
@mentolrespiral This repository is not for support of individual bot. It's the basic library and a few frameworks used by people to create bots.

If you have an issue with a certain bot, please contact the creator of that bot

**Comment by mentolrespiral** [comment]
Oh sorry! I thought it was an Addo37 repository. Thank you

**Comment by addo37** [comment]
Hey mentol. I hear ye! Please talk to me on Telegram and close this issue here. @addo37 would be my handle. :)
