### ISSUE TITLE
Some exceptions are only logged into a file, but not into the logger

### ISSUE THREAD

**Issue by nidi3** [rubenlagus/TelegramBots#71]
see lines https://github.com/rubenlagus/TelegramBots/blob/bb110e1127b4857adfacdf34070fc3735371813f/src/main/java/org/telegram/telegrambots/BotLogger.java#L135-L161
is this on purpose or just a copy/paste error?

**Comment by rubenlagus** [comment]
Sorry, copy/paste is always a bad idea.... will fix, thanks
