### ISSUE TITLE
getCanRestrictUsers() don't work

### ISSUE THREAD

**Issue by XeneOG** [rubenlagus/TelegramBots#710]
The method returns null even if the bot has permissions or not, this is because the library uses can_restrict_users and not can_restrict_members.

**Comment by aNNiMON** [comment]
It's already fixed in #699 
But we need to wait until it accepted.

**Comment by XeneOG** [comment]
> It's already fixed in #699
> But we need to wait until it accepted.

Hell I didn't notice that. We will wait :>
