### ISSUE TITLE
Create 'command conversation' / wait for user reply.

### ISSUE THREAD

**Issue by PauMAVA** [rubenlagus/TelegramBots#729]
Hey!

I am using this API to develop a Telegram bot, and I've been stuck for some hours on this issue.

First of all I want to apologize if this info is on the wiki, but after searching for it I haven't been able to find it.

I want to make the bot ask the user for some info. Example:

**User:** /setname
**Bot:** Tell me your name!
**User:** Joe
**Bot:** Your name has been changed to Joe successfully!

I do NOT want to issue a command like: /setname joe.

I've already tried this approach:

```
private String getParameter() throws TelegramApiException {
        Integer updateId = 0;
        boolean notInput = true;
        String parameter = "";
        while(notInput) {
            ArrayList<Update> getUpdates = telegramBot.execute(new GetUpdates().setLimit(1).setOffset(updateId).setTimeout(0));
            if (getUpdates.size() > 0) {
                parameter = getUpdates.get(0).getMessage().getText();
                notInput = false;
            }
            updateId++;
        }
        return parameter;
    }
```
The problem on this code snippet, is that any update caused by any user will be processed by this method. So if I have to simultaneous chats something like this could happen:

**_Chat1_**
**User1:** /setname
**Bot:** Tell me your name!

**_Chat2_**
**User 2:** Mark

**_Chat1_**
**Bot:** Your name has been changed to Mark successfully!

Is there any way to set the GetUpdates object to only listen from a certain chatId?

Is there a better workaround to this ?

Any help is appreciated.

**Comment by PauMAVA** [comment]
Any idea on how to do this? @rubenlagus

**Comment by Chase22** [comment]
@PauMAVA Do not use GetUpdates yourself. Update fetching will be handled by the libary. 
What you can do is set a flag and check if the flag is set in onUpdateReceived. If the flag is set, use the message as a name, if not. Proceed as normal

**Comment by PauMAVA** [comment]
Thank you for your response. That solved my doubt. Thanks.
