### ISSUE TITLE
Handling command with regex

### ISSUE THREAD

**Issue by grigoriy-belov** [rubenlagus/TelegramBots#736]
Hello
Is there anyway to handle a bot command with regex? I mean something like /download123 or /download([0-9]+).

I need a work around for this.

Thanks.
![7J8qQ](https://user-images.githubusercontent.com/55102203/76296819-7c2fbb80-62bf-11ea-8ea6-b68b93f92328.jpg)

**Comment by rubenlagus** [comment]
Commands will be received in your Update->Message->Text field. Just stract them and apply whatever reges you'd like to. No limitations within the API for that.

**Comment by Zibog** [comment]
Is this behavior possible to implement using abilities? The `DEFAULT` ability handles only text, not commands. I would like to e.g. echo some text on any command except explicitly declared ones
