### ISSUE TITLE
Change logging logic to common logging api

### ISSUE THREAD

**Issue by 2686747** [rubenlagus/TelegramBots#74]
> Library just should use any of commong logging api (jul, jcl, log4j, slf4j-api), and final application should be free to decide which logger to use in real.

**Comment by antonu17** [comment]
@2686747 why did you removed @rubenlagus logging methods from code in your fork? It was already common logging api - java.util.logging. If you want to use SLF4j  in you final application, you could add jul-to-slf4j bridge to your application, and it will route all incoming jul records to the SLF4j API. No need to modify the library.

**Comment by 2686747** [comment]
@antonu17 library has own custom BotLogger and creates empty unexpected files. It is not good behavior. And i changed logic in my own fork without any PR, we can resume discussion in 87b4b44 if you want.

**Comment by antonu17** [comment]
@2686747 Creation files in BotLogger was only bad. Everything else is very well. @rubenlagus said the will disable files creation on next release. I'm sorry, i not criticize your change, just share experiense...

**Comment by 2686747** [comment]
@antonu17 No, no, sharing is a good idea. Ticket is more like a memo here, it can help to understand better some features of project, we can discuss this question together and all can see history of result solution.

**Comment by rubenlagus** [comment]
Everything should be fixed in latest dev version. Now the api logger accept any jul handler and the file is not created because I just added it as a different Handler so it can be used or not... up to the final dev.

**Comment by rubenlagus** [comment]
Closed via e54396a0cab085dddd45dd7250349c6497419ecc
