### ISSUE TITLE
Disable listening for incoming updates in long polling bot?

### ISSUE THREAD

**Issue by Serhiy-iLchenko** [rubenlagus/TelegramBots#747]
Hello, I am planning to use a telegram bot to send error reports to me when some exception happened in my java app. 
Therefore, I don't need the bot to listen on incoming messages (updates), this would create unnecessary resource consumption.

Can I somehow disable incoming messages listening?

**Comment by Chase22** [comment]
You should be able to not register a bot with the library and still use the excute method to send messages
