### ISSUE TITLE
Ability example: reply never triggered

### ISSUE THREAD

**Issue by andtorg** [rubenlagus/TelegramBots#764]
Hi,
I'm just getting my feet wet with the library. I cannot reproduce the reply of an Ability bot following the very same example in the wiki. If I reply to the bot message ("Play with me!"), nothing happens: it seems that the update is never caught.
Perhaps I am missing something.

**Comment by addo37** [comment]
Where are you talking to the bot? If it's a group, the bot needs to have public permissions to read all messages (talk to BotFather).

I could help you further if you post the full code snippet that you're running.

**Comment by andtorg** [comment]
Many thanks for your reply. 
I am trying both in a group and in the bot chat.
/setprivacy is disabled, so the bot should access to all messages. Here is [the class](https://gist.github.com/andtorg/922d01adb6e53518d1c4011f62654da3).
You'll notice that the two abilities are taken from the wiki almost without any change.
A word of disclaimer: it's just a couple of days that I'm playing both with telegram api and with this library, after a very quick look of other languages wrapping, so there's a chance i'm missing some key points. Anyway, that's what happens:
`/play`
the bot says "Play with me!";  a prompt for a reply appears inviting me to send a message
I send a message in reply.
At this point I expect the bot returns a msg saying "It's been nice playing with you!".
This latest snippet never gets executed.

**Comment by addo37** [comment]
Hey, I tried running your example. It worked fine; just make sure that you bot username matches what you define in `public static String BOT_USERNAME = "homer"`.

**Comment by andtorg** [comment]
My bad, I completely misunderstood that field meaning. Again, thx a lot.
Cheers
