### ISSUE TITLE
Ability command does not triggering in certain cases

### ISSUE THREAD

**Issue by Melodeiro** [rubenlagus/TelegramBots#768]
When i type command with some text on next line, it does not working:
```
/test
text1
text2
```
But if i type something on the first line it is working:
```
/test something
text1
text2
```
Im using 4.9 version, with AbilityBuilder and `name(test)` method.

**Comment by addo37** [comment]
The command mechanism splits the input by ' ' then takes the initial token as the ability name. This won't work with multi-line.

I think this could be enhanced. In the meantime, you can always use a Reply to support this use case. https://github.com/rubenlagus/TelegramBots/wiki/Using-Replies

**Comment by addo37** [comment]
@Melodeiro Can you verify if this is still not addressed? If it is, can you close the issue? Thanks!

Here's the reference to the new methods introduced to customize the way we process text.

https://github.com/rubenlagus/TelegramBots/wiki/Advanced

**Comment by Melodeiro** [comment]
Added custom regex for spaces and newlines, and it is working as i wanted, thank you
