### ISSUE TITLE
Getting a SL4J error on a blank project using this library

### ISSUE THREAD

**Issue by ityulkanov** [rubenlagus/TelegramBots#769]
I've tried to create a blank project with only your library, but it is breaking with an error: 

SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.

Creating with springboot working just fine - it is starting without any errors. 
Is there a specific extra import I should add to build.gradle file to make it work?  

My gradle file looks like this: 

```
plugins {
    id 'java'
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.12'
    compile group: 'org.telegram', name: 'telegrambots', version: '4.9'
}

```

**Comment by rubenlagus** [comment]
@ityulkanov please check http://www.slf4j.org/codes.html#noProviders, not an API issue

**Comment by omkar-tenkale** [comment]
Fixed it by adding slf4j dependency


    implementation("org.telegram:telegrambots:6.3.0")
    implementation("org.slf4j:slf4j-simple:2.0.5")
