### ISSUE TITLE
Incorrect TelegramLongPollingCommandBot class constructor implementation causing NPE in CommandRegistry.removeUsernameFromCommandIfNeeded(String command) method

### ISSUE THREAD

**Issue by vikulin** [rubenlagus/TelegramBots#770]
Incorrect TelegramLongPollingCommandBot class constructor implementation causing NPE in CommandRegistry.removeUsernameFromCommandIfNeeded(String command) method.
See the code line:

https://github.com/rubenlagus/TelegramBots/blob/1a2e7c9773dbb7d251d30f1f8e3d6538dcd92600/telegrambots-extensions/src/main/java/org/telegram/telegrambots/extensions/bots/commandbot/TelegramLongPollingCommandBot.java#L56

In time the TelegramLongPollingCommandBot contructor creates the instance method this.getBotUsername() returns null because all fields of implementing class have not been initialized yet. Fields initialization runs **after** super.TelegramLongPollingCommandBot  invocation

Suggested fix: add String botUsername parameter in TelegramLongPollingCommandBot constructor passing to CommandRegistry instance.

**Comment by rubenlagus** [comment]
@vikulin Feel free to do a pull request with the fix, as long as it is backward compatible, I'm ok with suggested fix

**Comment by vikulin** [comment]
@rubenlagus , yesm I have created the pull request. See https://github.com/jenkinsci/telegram-notifications-plugin/pull/58

**Comment by vikulin** [comment]
Also it should be corrected accordingly to my suggestion.

**Comment by rubenlagus** [comment]
@vikulin That's a different project... not this one

**Comment by vikulin** [comment]
@rubenlagus , what is the project?

**Comment by rubenlagus** [comment]
@vikulin Probably the one where you created the issue and are writing now? :)

https://github.com/rubenlagus/TelegramBots

**Comment by vikulin** [comment]
@rubenlagus ah, yes. There is still only silence...

**Comment by rubenlagus** [comment]
Should be fixed now
