### ISSUE TITLE
Privacy is not accesible in replies

### ISSUE THREAD

**Issue by romangraef** [rubenlagus/TelegramBots#771]
Right now, Replies have now way of making them Privacy based, like abilities. It is not even possible to get the privacy level yourself, as [getPrivacy is internal in the BaseAbilityBot](https://github.com/rubenlagus/TelegramBots/blob/1a2e7c9773dbb7d251d30f1f8e3d6538dcd92600/telegrambots-abilities/src/main/java/org/telegram/abilitybots/api/bot/BaseAbilityBot.java#L462) superclass. I would suggest to either to open the getPrivacy method (maybe with a few overloads), or to provide Flags which check for certain Privacy modes.

**Comment by addo37** [comment]
@romangraef This has been addressed in the latest fixes. Let me know if you have any other related requests. If not, can you please close the issue? Thanks!

**Comment by romangraef** [comment]
Thanks
