### ISSUE TITLE
Channel Posts have no `from` attribute, making AbilityUtils.getUser nullable and blacklist checks fail

### ISSUE THREAD

**Issue by romangraef** [rubenlagus/TelegramBots#772]
According to [Telegrams API docs](https://core.telegram.org/bots/api#message) and my own experience, channel posts have no from attribute. 

This code:
https://github.com/rubenlagus/TelegramBots/blob/1a2e7c9773dbb7d251d30f1f8e3d6538dcd92600/telegrambots-abilities/src/main/java/org/telegram/abilitybots/api/util/AbilityUtils.java#L66-L67
therefore returns null for channel posts. I think this on its own could lead to confusion, but sadly this nullablity isn't checked by `checkBlacklist`:
https://github.com/rubenlagus/TelegramBots/blob/1a2e7c9773dbb7d251d30f1f8e3d6538dcd92600/telegrambots-abilities/src/main/java/org/telegram/abilitybots/api/bot/BaseAbilityBot.java#L403-L404
resulting in a `NullPointerException` for channel posts, making abilities and replies for channels unusable.

**Comment by romangraef** [comment]
Sorry if this is phrased in a confusing way, im open to questions.

**Comment by addo37** [comment]
@romangraef Can you verify if this is still an problem? If not, can you close the issue? Thanks!

**Comment by romangraef** [comment]
Thanks
