### ISSUE TITLE
NPE On getId()

### ISSUE THREAD

**Issue by DevFabioTNT** [rubenlagus/TelegramBots#781]
Hi,
With this code:
https://pastebin.com/54HcRSWL

When i send a message to the bot, i recive this error:
https://pastebin.com/xaXukzDq
`

Without the User ID my bot won't work.

**Comment by Chase22** [comment]
Take a close look at this line. I might tell you what's wrong
`Integer userId = u.getMessage().getLeftChatMember().getId()`

**Comment by rubenlagus** [comment]
@DevFabioTNT You need to fix the line @Chase22 mentioned, not an API issue
