### ISSUE TITLE
Can't call methods

### ISSUE THREAD

**Issue by Yoshiro09** [rubenlagus/TelegramBots#786]
Hi!
Why can't I call methods when there is a callback query?
Sorry, but I've never used Java to make a Telegram bot, and I'm really bad at it ^^'

**Comment by Chase22** [comment]
What are you trying to do and what is not working?

**Comment by rubenlagus** [comment]
@Yoshiro09 you can join https://t.me/JavaBotsApi to get help if you have any doubts building your code.
