### ISSUE TITLE
How to use TimedSendLongPollingBot

### ISSUE THREAD

**Issue by eos1d3** [rubenlagus/TelegramBots#790]
I tried and found `TimedSendLongPollingBot` is not in maven library so that import is not possible.

Is this include in current version? If so how to see it?

Thanks!

**Comment by Chase22** [comment]
It's part of the [telegrambot-extensions](https://github.com/rubenlagus/TelegramBots/tree/master/telegrambots-extensions). They have their own maven artifact

**Comment by eos1d3** [comment]
@Chase22 Thank for your reply.

But there is some issues. First, `sendMessageCallback` is never used to register the callback, how can it be call when time is ready?

Second, `sendMessageCallback` is not visible in other package, does this class really work?
