### ISSUE TITLE
Replace custom callbacks with CompletableFuture

### ISSUE THREAD

**Issue by Chase22** [rubenlagus/TelegramBots#793]
Since the Introduction of the [CompleteableFuture](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html) in Java 8 it has become the standard for simple asynchronous operations and callbacks. 

Using a CompletableFuture as a return for async methods would make it easier to handle in code and easier to integrate into other applications using Futures. It'd also reduce the amount of custom code.

This will be a breaking change so a parallel API will probably be necessary. I'm not yet 100% sure how to properly implement the new methods while the old ones are still present

Related Classes:
- [DownloadFileCallback](https://github.com/rubenlagus/TelegramBots/blob/master/telegrambots-meta/src/main/java/org/telegram/telegrambots/meta/updateshandlers/DownloadFileCallback.java)
- [SentCallback](https://github.com/rubenlagus/TelegramBots/blob/master/telegrambots-meta/src/main/java/org/telegram/telegrambots/meta/updateshandlers/SentCallback.java)

**Comment by rubenlagus** [comment]
@Chase22 Feel free to duplicate existing method that return a completablefuture. That would be a good way to avoid a breaking change. We can also mark the old async ones as deprecated and remove them in next major versioni

**Comment by rubenlagus** [comment]
@Chase22 That should have been addressed from version 5.0.0
