### ISSUE TITLE
What happened to TimedSendLongPollingBot since version 4.4.1?

### ISSUE THREAD

**Issue by eos1d3** [rubenlagus/TelegramBots#795]
Since 4.4.1, `MessageSenderTask` class is removed, so `sendMessageCallback` is never called. 

And `public` in `sendMessageCallback` is also removed so it is not visible for other packages:

`abstract void sendMessageCallback(Long chatId, Object messageRequest);`

The last useable version is 4.3.1 which has complete codes. Since 4.4.1, the `TimedSendLongPollingBot` class is broken and missing a lot of codes.

**Comment by rubenlagus** [comment]
@eos1d3 Happy to get a pull request fixing it.
