### ISSUE TITLE
TelegramLongPollingCommandBot can't get correct botUserName

### ISSUE THREAD

**Issue by Maksat1991** [rubenlagus/TelegramBots#796]
[TelegramLongPollingCommandBot](https://github.com/rubenlagus/TelegramBots/blob/master/telegrambots-extensions/src/main/java/org/telegram/telegrambots/extensions/bots/commandbot/TelegramLongPollingCommandBot.java)

In constructor `public TelegramLongPollingCommandBot(DefaultBotOptions options, boolean allowCommandsWithUsername)`
method `getBotUsername()` returns null if the name is pulled through the class field, from a config-file for example

**Comment by rubenlagus** [comment]
Fixed #820
