### ISSUE TITLE
Failed to load class StaticLoggerBinder

### ISSUE THREAD

**Issue by Seferi** [rubenlagus/TelegramBots#806]
Hi, I followed the Clevero's tutorial to create a bot. But when I run the .jar, I'm getting this:

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/home/user/Documents/Java-try/KuzBot/out/artifacts/KuzBot_jar/KuzBot.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

And bot doesn't echo what I send..

Help is appreciated

**Comment by Seferi** [comment]
I added the slf4j to the project, first three errors are gone but I still get the Illegal reflective access warnings.

**Comment by marcopaggioro** [comment]
Same problems here:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details
```

**Comment by Seferi** [comment]
> Same problems here:
> 
> ```
> SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
> SLF4J: Defaulting to no-operation (NOP) logger implementation
> SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details
> ```

Hi mate, you have to add slf4j library to your project, I downloaded the jar and added that way. You might get a warning about a google package. You have to launch the jar with this option like this: java  --add-opens java.base/java.lang=ALL-UNNAMED -jar yourjarfile.jar
Also add the option to your VM options if you are working with an IDE
