### ISSUE TITLE
builder for inline (reply) keyboard

### ISSUE THREAD

**Issue by centralhardware** [rubenlagus/TelegramBots#809]
it is very useful to have ready-made builders for InlineKeyboard ReplyKeyboard in the core of the library.

i use in my projects 
https://gist.github.com/centralhardware/959b2c2fcddd1d6a3e9fba09c8511b21 for Inline and 
https://gist.github.com/centralhardware/3557cedcc672d054043a8e1874c5adf5 for reply 

i can create PR with this class (of course with javadoc)
but I do not know where exactly is the best place to put these classes

**Comment by rubenlagus** [comment]
Extensions module sounds like a good place to me.

But the builder class InlineKeyboardBuilder should be returning a InlineKeyboard when build method is called to keep consistency with the name.

**Comment by rubenlagus** [comment]
@centralhardware Lsat version should already have builders created. Feel free to use them
