### ISSUE TITLE
How to send message from java or telegram scheduler?

### ISSUE THREAD

**Issue by MainStar** [rubenlagus/TelegramBots#816]
Hi, could you help please, how to create a scheduler which will send message to all chats (users) with java?

**Comment by AndriiRomanenko** [comment]
Hi!
To create a scheduler you could create your application, basis on Spring Framework

TelegramBot has spring starter dependency

```xml
<dependency>
            <groupId>org.telegram</groupId>
            <artifactId>telegrambots-spring-boot-starter</artifactId>
            <version>4.9.1</version>
        </dependency>
```

Using Spring Framework you can create a scheduler, using this part of the code:

```java
@Configuration
@EnableScheduling
public class Scheduler {

   @Scheduled(fixedDelay = 5000L)
  public void foo() {
   // your scheduler job code here
  }
}
```

Method **foo()** will do some job with delay of 5 seconds. You could configure on cron expression

Next what you need is a list of user's chat id. You could hold it in a file or in a database.

Class **TelegramLongPollingBot** has method **execute**, that take SendMessage object for sending messages to the users. 
All you need are the chat id of the user and text message, that you want to send. It can looks like this

```java
public void sendMessage(Long chatId, String textMessage) {
        SendMessage message = new SendMessage()
                .setChatId(chatId)
                .setText(textMessage);
        try {
            execute(message);
        } catch (TelegramApiException e) {
            e.printStackTrace();
        }
    }
```

**Comment by MainStar** [comment]
Hi!
If I will use telegram-spring-boot-starter the project will work with dependency injcetion?

**Comment by AndriiRomanenko** [comment]
Create project via spring initializer (on official spring website or in
IntelliJ Idea). Your project should be based on spring boot. Add telegram
dependency (telegrambots-spring-boot-started). Also you could add JPA
dependency for persisting your users into database (spring-boot-data-jpa
and postgres/mysql dependencies)

вт, 13 окт. 2020 г. в 21:31, MainStar <notifications@github.com>:
