### ISSUE TITLE
This doesn't correspond with Telegram API requirements.

### ISSUE THREAD

**Issue by zundarik** [rubenlagus/TelegramBots#818]
We need to make changes to the line "checkArgument (isAlphanumeric (name), "Method name can only be alpha-numeric", name);" in class Ability.
This doesn't correspond with Telegram API requirements, which are:
"A command must always start with the '/' symbol and may not be longer than 32 characters. Commands can use latin letters, numbers and underscores." (https://core.telegram.org/bots#commands)
It does not accept the underscore.

**Comment by addo37** [comment]
A PR #814  is underway. As a workaround, you may implement a command using the Reply mechanism. Otherwise, we'll get this as soon as Ruben approves the PR. Thanks!

**Comment by addo37** [comment]
@zundarik The change has merged. If there's no other concern, please close this issue.

**Comment by rubenlagus** [comment]
Fixed #814

**Comment by zundarik** [comment]
Thank you very much!
