### ISSUE TITLE
Send message inside reply() using ability extensions?

### ISSUE THREAD

**Issue by Alexius33** [rubenlagus/TelegramBots#824]
Hi, I'm trying to write an ability that supports replies just like the one in the [wiki](https://github.com/rubenlagus/TelegramBots/wiki/Using-Replies#ability-reply) but using `AbilityExtension` just to keep the Bot and the abilities in different classes. 

The problem is that inside `.reply()` I don't have access to any method to send messages (like `silent`) as reply only takes an `Update` and not, for example, a `MessageContext`.

Is there any workaround I could implement or any suggestion? Or maybe am I doing anything wrong?

Oh and while I'm here, what is a possible use case for the command `/claim`? I can't quite figure it out as it only adds the creator to the list of admins, but the creator can already execute admin commands.. so it got me a little confused

Thank you

**Comment by addo37** [comment]
> Is there any workaround I could implement or any suggestion? Or maybe am I doing anything wrong?
Yup, you'll need to pass in the bot to your constructor and then use it in your replies.

> Oh and while I'm here, what is a possible use case for the command /claim?
There's none, it's an old command that's pretty much useless. The initial intention was to not bind the bot to a certain creator ID, but some generic criteria and then use /claim to claim the bot. This will be removed in the future.

**Comment by Alexius33** [comment]
Thank you for your fast response. 
As I'm trying to use spring boot, how could I implement this? Because if I try to inject my bot inside my abilities it then fails to start due to circular dependency (ability depends on bot which depends on ability)

**Comment by addo37** [comment]
Abilities now have a `.bot()` accessor in the context objects, so you could do something like `ctx.bot()` to access the bot.

> Because if I try to inject my bot inside my abilities it then fails to start due to circular dependency (ability depends on bot which depends on ability)

Make sure to use the latest version 4.9.2 as it introduces lazy loading/registration of features and abilities.
