### ISSUE TITLE
i cant use the library

### ISSUE THREAD

**Issue by IlCurci** [rubenlagus/TelegramBots#833]
how to solve
the type org.telegram.telegrambots.meta.generics.longpollingbot cannot be resolved, it is indirectly referenced from required .class files

new using eclipse, btw is it possible to use netbeans? i mean they do both the same thing right?

**Comment by LukasPrediger** [comment]
How are you including the library into your classpath? Are you using maven or gradle?

It seems like you are missing the meta package which is a dependency of the core library
