### ISSUE TITLE
Maven dependency misses library telegrambots

### ISSUE THREAD

**Issue by Antonio112009** [rubenlagus/TelegramBots#836]
I decided to start a new project and imported telegrambots library (5.0.1) via maven. My Intellij downloaded only **telegram-meta:5.0.1**, while **telegrambots:5.0.1** was missing in list of external libraries. I decided to downgrade to 4.9 and the missing library appeared! When I upgraded back to 5.0.1 both libraries upgraded back to 5.0.1.

Steps to see the issue:
1 - open IntelliJ and create new maven project
2 - add dependency with telegrambots 5.0.1 to the pom.xml
3 - see which libraries have been downloaded

If everything is OK, try to add dependency for spring (telegrambots-spring-boot-starter).

My maven dependency:
```xml
<dependency>
     <groupId>org.telegram</groupId>
     <artifactId>telegrambots</artifactId>
     <version>5.0.1</version>
</dependency>
```

My screenshot from my first try (5.0.0 shows because I was doing downgrade)
<img width="469" alt="2020-11-27 в 14 30 21" src="https://user-images.githubusercontent.com/29264726/100459764-ea224a00-30bd-11eb-9c66-f1fca63b052c.png">

**Comment by Antonio112009** [comment]
I suppose that person with issue #833 faced the same problem

**Comment by rubenlagus** [comment]
Not sure what's the issue here. I have tried to create a new project and after doing Maven->reimport it correctly download the corresponding external dependencies

**Comment by Antonio112009** [comment]
Seems like the issue was with Maven. It's almost 2 months past and the issue could be fixed on Maven's side
