### ISSUE TITLE
java.lang.NoClassDefFoundError: org/telegram/telegrambots/meta/generics/LongPollingBot

### ISSUE THREAD

**Issue by Nikotecnology** [rubenlagus/TelegramBots#838]
Hi, when i try starting bot it says this error: java.lang.NoClassDefFoundError: org/telegram/telegrambots/meta/generics/LongPollingBot

**Comment by rubenlagus** [comment]
Make sure you are correctly importing the dependencies as per: https://github.com/rubenlagus/TelegramBots#usage
