### ISSUE TITLE
Lost compatibility

### ISSUE THREAD

**Issue by RakhaHasse** [rubenlagus/TelegramBots#839]
When using the library version 4.9.1, it successfully works with the text of messages and responds to them. When using 5.0.1, the bot does not respond to messages at all. Everything is compiled without errors.

**Comment by whatever-username** [comment]
Bump

**Comment by Chase22** [comment]
Any additional infos in this? Logs? Using webhook or longpolling? Where deployed? Can you verify that no messages are received?

**Comment by rubenlagus** [comment]
Not enough information to investigate anything, please reopen if you get more information of the issue.
