### ISSUE TITLE
How to get user profile pictures

### ISSUE THREAD

**Issue by NezcafeGold** [rubenlagus/TelegramBots#840]
I found the issue #130, but the solution doesn't work. I don't see something like this method: **getUserProfilePhotos()**.
Are there any solutions or what I do wrong?

**Comment by Chase22** [comment]
The way methods are called did change in the meantime. Now create an object of type GetUserProfilePhotos and execute it using the execute() method. 

The execute() call will return the photos.

You can see how it's done using the [Getting Started](https://github.com/rubenlagus/TelegramBots/wiki/Getting-Started) guide
