### ISSUE TITLE
How to receive formatted text in bot

### ISSUE THREAD

**Issue by Artgit** [rubenlagus/TelegramBots#847]
I'm tryint to read the input text message in my bot via `org.telegram.telegrambots.meta.api.objects.Message.getText() `method but provided text doesn't contain formatting.. only plain text. How to get formatting created by user?

**Comment by Chase22** [comment]
The Formatting is passed via MessageEntities. The text field will always be the raw text.
Take a look at the entities field of Message:
https://core.telegram.org/bots/api#messageentity
