### ISSUE TITLE
Doesn't delete messages.

### ISSUE THREAD

**Issue by makeIttBetter** [rubenlagus/TelegramBots#849]
I have the same problem with both api versions 4.0 and 5.0.
In my bot, I send a new message, and then delete the previous one, and so the previous message very often does not disappear, and only ErrorDeletingMessage writes in the console and that's all, there is no additional information about the error. I heard that api only allows 30 requests per second, could the messages not be deleted because the number of requests per second is higher than 30? Or the reason is something else. If this is a bug, please pay attention to it, I will be very grateful)

**Comment by rubenlagus** [comment]
If the problems were the limits, you should have received a 429 error. 

Regarding "ErrorDeletingMessage", I'm not sure where that log line come from, can you please check the stacktrace and confirm it comes from the library?

**Comment by makeIttBetter** [comment]
Oh, yes. That's it, I figured it out. Thanks)
