### ISSUE TITLE
Chat bot

### ISSUE THREAD

**Issue by Abhi-junior** [rubenlagus/TelegramBots#852]
I want to make chat bot

**Comment by Narryel** [comment]
lmao

**Comment by Chase22** [comment]
Please provide some actual information on your problme or question and consul the [Getting Started Guide](https://github.com/rubenlagus/TelegramBots/wiki/Getting-Started)

@rubenlagus this can be closed

**Comment by Abhi-junior** [comment]
> lmao
> 

Huhhh
