### ISSUE TITLE
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".

### ISSUE THREAD

**Issue by sankmr211** [rubenlagus/TelegramBots#856]
problem issue....please help me
![issue](https://user-images.githubusercontent.com/75348192/104835661-1d1ed800-58ce-11eb-8cf5-350bfa032c1a.JPG)

**Comment by andrea-falco** [comment]
SLF4J acts as a facade for different logging frameworks (e.g. java.util.logging, logback, Log4j).
It offers a generic API making the logging independent of the actual implementation.

You need to add an implementation for SLF4J.

For example, for Logback, you can add the following dependency to your POM:
```
<dependency>
    <groupId>ch.qos.logback</groupId>
    <artifactId>logback-classic</artifactId>
    <version>1.2.3</version>
</dependency>
```
