### ISSUE TITLE
setChatID

### ISSUE THREAD

**Issue by gaukler2** [rubenlagus/TelegramBots#866]
If i try your example, i get an error..

SendMessage message = new SendMessage().setChatId(update.getMessage().getChatId()).setText(update.getMessage().getText());

The method setChatid(String) in the type SendMessage is not applicable for the arguments (Long)

**Comment by Flexeus** [comment]
Use String.valueOf method

**Comment by genjiezio** [comment]
@gaukler2 actully, if you just put the **String.valueOf** , I suppose you still can get an error. 
So , I suggest you to use it like this :

SendMessage message = new SendMessage();
           message.setChatId(String.valueOf(update.getMessage().getChatId());
            message.setText(update.getMessage().getText());

**Comment by rubenlagus** [comment]
Check steps to update: https://github.com/rubenlagus/TelegramBots/wiki/How-To-Update#to-version-500, should explain how to solve that problem
