### ISSUE TITLE
Deploy on Maven Central

### ISSUE THREAD

**Issue by fpompermaier** [rubenlagus/TelegramBots#87]
Do you have any plan to deploy release artifacts also on Maven central?
If you want I can take care of it (probably I will just need your help to fill some legal form....)

**Comment by rubenlagus** [comment]
Sure, I just used jitpack because it was easier.

 Feel free to make any necessary changes in the code and contact me if needed. 

Thanks

**Comment by fpompermaier** [comment]
So, the first thing to do is to [Create a JIRA account] (https://issues.sonatype.org/secure/Signup!default.jspa) and [create a new Project ticket] (https://issues.sonatype.org/secure/CreateIssue.jspa?issuetype=21&pid=10134) as explained at http://central.sonatype.org/pages/ossrh-guide.html. You will probably register the group id org.telegram.

Once you've completed these 2 steps just ping me on this issue.

**Comment by rubenlagus** [comment]
The ticket is already open, waiting for the answer.

**Comment by rubenlagus** [comment]
@fpompermaier Done, I had to change the groupId because I needed to have the domain itself (something a bit hard with org.telegram). But it is now approved: https://issues.sonatype.org/browse/OSSRH-22805

**Comment by antonu17** [comment]
I think if this library will be a de facto java telegram bot api library, then it should use groupId org.telegram :)

**Comment by rubenlagus** [comment]
@antonu17 Asking that to telegram will mean that they agree to make it the "official" one, something that I'm not sure they will do. In any case, I can ask support about that.

Regarding the groupId, it make a reference to the origins of all my contributions to Telegram environment code ;)

**Comment by fpompermaier** [comment]
@rubenlagus are you able to make a script to release the project on Maven central following http://central.sonatype.org/pages/apache-maven.html? If you need a hand just add me to your contacts in skype or facebook!

**Comment by rubenlagus** [comment]
@fpompermaier I'm waiting to see if I get answer from support about the usage of org.telegram, I'll done the script once I have an answer

**Comment by Dahu88** [comment]
Hello, I'm beginning to write my own telegram bot using java, and I would appreciate to know if it's available in maven now ?

**Comment by Mit0x2** [comment]
@Dahu88 you can alreay use the library via maven. See instructions [here](https://jitpack.io/#rubenlagus/TelegramBots). Once the library is available in Maven Central, you can remove the reposior part and change the groupId of the library...

**Comment by dvvasilyev** [comment]
@rubenlagus any updates?

**Comment by rubenlagus** [comment]
I have the  `org.bistromathicdrive` version, but I'm still waiting for Telegram people to answer my request to use `org.telegram`as groupId. That's why I didn't made any change.

**Comment by malaki12003** [comment]
May I ask you to deploy the artifact on another repository? if there is problem with maven central, why don't you let  the releases to access through another public repo?

**Comment by Mit0x2** [comment]
What is the state on this one?

**Comment by rubenlagus** [comment]
Done, you should be able to use it with:

```
   <dependency>
        <groupId>org.telegram</groupId>
        <artifactId>telegrambots</artifactId>
        <version>2.4.0</version>
    </dependency>
```
