### ISSUE TITLE
What does "answer" variable correspond to in GetUserProfilePhotos class? 

### ISSUE THREAD

**Issue by Strvm** [rubenlagus/TelegramBots#870]
Hi, i'm trying to get a user's profile picture. I seemed to understand to get it you had to get a UserProfilePhotos object. For this I tried using this:

`GetUserProfilePhotos.builder().userId(update.getMessage().getFrom().getId()).build().deserializeResponse("");`
But I don't seem to understand what i'm supposed to put inside deserializeResponse(). In the source it needs an "answer" variable but there is no explanation on what that could be. Thanks for you help.

**Comment by rubenlagus** [comment]
Duplicate #840
