### ISSUE TITLE
Search from channel or group

### ISSUE THREAD

**Issue by bestDvlpr** [rubenlagus/TelegramBots#879]
Hi there

I wanted to create a bot which by adding it to a group or a channel, it searches some words from that group or channel.
Is there any possibility to do it using this platform?

Thank you in advance

**Comment by rubenlagus** [comment]
Method not supported by the Bots API: https://core.telegram.org/bots/api

**Comment by bestDvlpr** [comment]
Thank you for the reply

I have seen some information in the [link](https://github.com/eternnoir/pyTelegramBotAPI/issues/639#issuecomment-488227292) that if the bot, which is added to a group or a channel, is given admin permissions, then it would have access to all messages in the group/channel using messages.getHistory

Maybe it is possible to implement it in this spring-boot-telegram-starter?
