### ISSUE TITLE
Error:java: error: release version 5 not supported

### ISSUE THREAD

**Issue by ghazal-pouresfandiyar** [rubenlagus/TelegramBots#884]
![image](https://user-images.githubusercontent.com/61365439/112712389-e7f5be00-8eec-11eb-883a-ed4160d78df0.png)
I'm using java 11 and I've got this error. What should I do?
The google didn't help me!

**Comment by Chase22** [comment]
You have to tell maven to compile the module with java 11 by using source and target version attributes. They can be googled

**Comment by centralhardware** [comment]
looks like idea Project language level don't configured properly
