### ISSUE TITLE
Spring boot app with web starter (war deployment) will not shutdown with telegrambots

### ISSUE THREAD

**Issue by chrisj124** [rubenlagus/TelegramBots#894]
Hi - great library

I have Java 11 - Spring boot 2.4.4 with the following starters:  web, data-jpa, tomcat, test, and telegrambots.  The app provides REST services through Spring REST Controllers - and prior to adding telegrambots the app runs and shuts down flawless.

Telegrambots was added and runs fine as per your documentation.  However - when I try to stop the app: either stopping Tomcat server in Eclipse - or stopping my prod tomcat server where the war is deployed - the app will never shutdown.  Eventually I will see an error:
java.lang.NoClassDefFoundError: org/apache/http/pool/PoolStats
cause by:
 Illegal access: this web application instance has been stopped already

However a thread will stay open preventing Tomcat from stopping.  I've tried countless things to try to get telegrambots to shutdown correctly - but no luck.  For now I have to kill processes every time I want to stop / undeploy them.  Which is not always easy in a production environment.

Any ideas?  thanks

**Comment by Chijuk** [comment]
You can still register bot with `registerBot` and not use telegrambots spring starter inside spring environment.
And then on `@PreDestroy` of appropriate bean just stop bot session.

**Comment by chrisj124** [comment]
Thank you Chijuk!
Sometimes the simplest solution is the hardest to see right away.
