### ISSUE TITLE
Is there something in the wiki that talks about this?

### ISSUE THREAD

**Issue by NiceCraftz** [rubenlagus/TelegramBots#897]
Title, i've not seen anything, i've been searching all day on this 
![image](https://user-images.githubusercontent.com/47219477/114445836-d3921080-9bd0-11eb-984a-6f9d9255c129.png)
i am trying to make a bot like that

**Comment by slavino** [comment]
Bold font heading?

**Comment by velosh** [comment]
> Bold font heading?

I guess he mean Inline Search

**Comment by rubenlagus** [comment]
@NiceCraftz  https://core.telegram.org/bots#inline-mode
