### ISSUE TITLE
How to use sendMessage method using String url

### ISSUE THREAD

**Issue by arahnik121** [rubenlagus/TelegramBots#903]
Hi. How i can send photo from remote server by url photo? SendPhoto.setPhoto wait InputFile param. Mayb im blind...

**Comment by rubenlagus** [comment]
https://github.com/rubenlagus/TelegramBots/wiki/FAQ#how-to-send-photos

**Comment by arahnik121** [comment]
> https://github.com/rubenlagus/TelegramBots/wiki/FAQ#how-to-send-photos

Thank you!
