### ISSUE TITLE
editMessageText command returned Empty Message

### ISSUE THREAD

**Issue by flashpress** [rubenlagus/TelegramBots#91]
Hello everybody! Thank you for the excellent library :)

editMessageText command returned Message object:

`Message{messageId=null, from=null, date=null, chat=null, forwardFrom=null, forwardFromChat=null, forwardDate=null, text='null', audio=null, document=null, photo=null, sticker=null, video=null, contact=null, location=null, venue=null, newChatMember=null, leftChatMember=null, newChatTitle='null', newChatPhoto=null, deleteChatPhoto=null, groupchatCreated=null, replyToMessage=null, voice=null, caption=null, superGroupCreated=null, channelChatCreated=null, migrateToChatId=null, migrateFromChatId=null, editDate=null}`

Why is this so?
Thanks.

**Comment by antonu17** [comment]
Hello! @flashpress can you show code? When i used this command it worked as documented.

**Comment by rubenlagus** [comment]
@flashpress Any update?
