### ISSUE TITLE
SendDocument Class

### ISSUE THREAD

**Issue by LucaCamporotondo** [rubenlagus/TelegramBots#916]
Hello,

I noticed that it is not possible to send a document through the file_id as reported in the Telegram documentation, but only through the InputFile class.

Api 5.2.0

**Comment by meirbnb** [comment]
why is the issue closed?

**Comment by LucaCamporotondo** [comment]
Hello,

because it was my mistake in using the API.

Il Mar 22 Giu 2021, 10:15 Meirbek Bolatbekov ***@***.***> ha
scritto:

**Comment by meirbnb** [comment]
Could you elaborate on how you fixed your mistake, seems like I've the same issue?
