### ISSUE TITLE
How to use thenApply() on executeAsync()

### ISSUE THREAD

**Issue by Velosh** [rubenlagus/TelegramBots#919]
Hello people, I was trying to use thenApply() to get better response from API, I don't know If I'm doing it wrong but, It really doesn't have a proper method to execute it, my code:

```
public boolean leaveChat(String chatID) {
        /*
         * Prepare LeaveChat base
         */
        LeaveChat leaveChat = new LeaveChat();
        leaveChat.setChatId(chatID);

        /*
         * Execute execute() method
         */
        try {
            // Can't use async because I can't get a real return, or maybe I'm doing wrong.
            return executeAsync(leaveChat).thenApply(response -> {
                /*
                * Some code here, just for ex
                */
            }).thenApply(); << The problem
        } catch (TelegramApiException telegramApiException) {
            logger.error(telegramApiException.getMessage() + " (CID to leave: " + chatID + ")");
            return false;
        }
    }
```

Is there any appropriately usable method for executing this thenApply()?
![Screenshot_20210517_144908](https://user-images.githubusercontent.com/57292142/118533940-0fb01800-b71f-11eb-95ea-fd10625b6e17.png)

**Comment by Shemplo** [comment]
Do you want to retrieve response and do some transformations on it and then return?

```java
return executeAsync(leaveChat).thenApply(response -> false).get()
```

**Comment by Velosh** [comment]
> ```java
> return executeAsync(leaveChat).thenApply(response -> false).get();
> ```

Yeah, this is enough, thanks!
