### ISSUE TITLE
Change SendPhoto (and same) method for sending new file

### ISSUE THREAD

**Issue by antonu17** [rubenlagus/TelegramBots#92]
Its not intuitive for new users to understand what they need to put in `setNewPhoto(String photo, String photoName)`. What is the second argument `photoName`? [Telegram Bot API sendPhoto documentation](https://core.telegram.org/bots/api#sendphoto) tells us nothing about `photoName`. And same kind of questions for same methods: sendDocument, sendVideo, etc.

**Comment by rubenlagus** [comment]
Closed via #94
