### ISSUE TITLE
telegram sends same message continuously

### ISSUE THREAD

**Issue by azzahrah** [rubenlagus/TelegramBots#926]
what the problem with my script? why telegram send same messages ?
```
 SendMessage message = new SendMessage(); 
                       message.setChatId(msgOut.chatId);
                        message.setText(msgOut.msg);
execute(message);
```

**Comment by Velosh** [comment]
> what the problem with my script? why telegram send same messages ?
> 
> ```
>  SendMessage message = new SendMessage(); 
>                        message.setChatId(msgOut.chatId);
>                         message.setText(msgOut.msg);
> execute(message);
> ```

Try with `executeAsync(message);` instead.

**Comment by Velosh** [comment]
> Try with `executeAsync(message);` instead.

Check that you are not accidentally sending the same message either.

**Comment by azzahrah** [comment]
i have check and  try send to difference destination, first to web browser over websocket and second to telegram, on websocket we receiver right data and telegram we receive duplicate data
