### ISSUE TITLE
No functionality to check if a user is an admin of a group

### ISSUE THREAD

**Issue by tremon36** [rubenlagus/TelegramBots#929]
I think it might be pretty useful to have this functionality in the library.
Sometimes you want some commands only to be executed by group admins, and as far as I know, that is not possible right now

**Comment by Velosh** [comment]
> I think it might be pretty useful to have this functionality in the library.
> Sometimes you want some commands only to be executed by group admins, and as far as I know, that is not possible right now

https://github.com/TrebleExperience/Bot3/blob/stable/src/main/java/com/vegazsdev/bobobot/TelegramBot.java#L289-L321

Check this example.

**Comment by Velosh** [comment]
@tremon36 bump, you can close this issue? If fixed anyway.
