### ISSUE TITLE
Receiving messages from channel

### ISSUE THREAD

**Issue by Dannypeja** [rubenlagus/TelegramBots#932]
I got receiving messages to work. Surely I can send and interact with a direct chat with the bot.
I then wanted to try out to interact with another bot. The API there has it's limitations. 
To overcome this I added the receiver bot in a channel. But sitting in the channel (as admin) it is not receiving anything.

why, what am I missing? 
I am using the common

```java:
public void onUpdateReceived(Update update) {

    if (update.hasMessage() && update.getMessage().hasText()) {
```

**Comment by Shemplo** [comment]
Did you check that your bot is not in privacy mode?
https://core.telegram.org/bots#privacy-mode
