### ISSUE TITLE
There is no 'execute()' method for EditMessageText or EditMessageReplyMarkup

### ISSUE THREAD

**Issue by meghdadp** [rubenlagus/TelegramBots#943]
Hi,
I'm using library version 5.2.0 to develop a webhook bot (My main controller class extends TelegramWebhookBot)
I want to edit the text and InlineKeyboard of an existing message, but there is no __execute()__ method dedicated to these 2 objects in __DefaultAbsSender__ class.
How could I exactly send an __EditMessageText__ or __EditMessageReplyMarkup__ object?

**Comment by rubenlagus** [comment]
No need to have specific methods, you have `execute(Method method)` that should work for most of the cases. Specific methods are only created for those that require an special treatment.
