### ISSUE TITLE
Incorrect Update class structure.

### ISSUE THREAD

**Issue by OZhavi** [rubenlagus/TelegramBots#948]
I managed to intercept request from Telegram (for payment.form, provider side) before it reached this Telegram Java API. And its body is as follows (here I see custom query):
{"update_id":649913187,
"custom_query":{"method":"payments.form","customer_id":396****70,"bot_id":186*****83,"bot_account":"186*****83","bot_owner_id":396****70,"bot_username":"UnlimintTestPayBot","customer_language_code":"en","theme_params":{"button_text_color":"#ffffff","bg_color":"#ffffff","text_color":"#000000","button_color":"#6d839e","link_color":"#6d839e"},"id":"1703291991510559845"}}

Need to add necessary field to this class.

**Comment by rubenlagus** [comment]
Which part from the Payments API is not represented correctly. The library should reflect every field available as per: https://core.telegram.org/bots/api#payments

**Comment by OZhavi** [comment]
Yep, sorry. Open an issue in incorrect project. Will close this one.
