### ISSUE TITLE
does new updates handle in different threads ?

### ISSUE THREAD

**Issue by Serqati** [rubenlagus/TelegramBots#955]

**Comment by MouamleH** [comment]
No, but if you register multiple bots, I think each bot will have its own thread
[Check it here](https://github.com/rubenlagus/TelegramBots/blob/master/telegrambots/src/main/java/org/telegram/telegrambots/updatesreceivers/DefaultBotSession.java)

**Comment by rubenlagus** [comment]
@Serqati You can always override the method and handle them in multiple threads if you want: https://github.com/rubenlagus/TelegramBots/blob/master/telegrambots-meta/src/main/java/org/telegram/telegrambots/meta/generics/LongPollingBot.java#L26
