### ISSUE TITLE
Recurrent typo Replay instead of Reply

### ISSUE THREAD

**Issue by BillyHalley** [rubenlagus/TelegramBots#97]
I noticed using EditMessageText class, it has setReplyMarkup() method, instead SendMessage has setReplayMarkup(). A quick search in the repository showed this is a recurrent "issue".
I know correcting it could be a big problem for everyone using this library, just wanted to know if you're aware and not correcting it to avoid big troubles in users.

**Comment by rubenlagus** [comment]
I'm aware of this. The idea is to add a method with the correct name and deprecate (documenting them correctly) the wrong one. Both of them will be available until next mayor release (regardless how long this mean). Feel free to make a pull request if you have it.

**Comment by BillyHalley** [comment]
Great, when i'll be free from finals i'll try giving a hand ;)

**Comment by BjoernPetersen** [comment]
I'm on it right now. I hope no one else started working on this issue...
