### ISSUE TITLE
Wildfly error deploy WFLYEE0024: Could not configure component Bot

### ISSUE THREAD

**Issue by mrFloony** [rubenlagus/TelegramBots#973]
Hi, I can not deploy to Wildfly (23.0.2) a project created from a TelegramLongPollingBot because of a mistake:

WFLYEE0024: Could not configure component <..>Bot
Caused by: java.lang.VerifyError: JVMVRFY007 переопределен метод final; класс=<..>Bot$$$view1, метод=execute(Lorg/telegram/telegrambots/meta/api/methods/send/SendAudio;)Lorg/telegram/telegrambots/meta/api/objects/Message;, pc=0"},

I want to know if something can be done about this?

**Comment by mrFloony** [comment]
Hi, I tried to remove in methods **execute**, **sendApiMethodAsync** and **sendApiMethod** modifier **final**, after which the code worked on Wildfly. I expect your correction, or I can make changes and add to pull request?

**Comment by rubenlagus** [comment]
Those methods are internal for the library and are made final on purpose since they are not to be overridden.

**Comment by mrFloony** [comment]
Yes, but as it turns out, this imposes restrictions on the use in Wildfly.

Will you keep the current implementation? I've seen on others pull requests, and there the final modifier was removed for some of the methods **execute**
